// SEDENS interface copy. Every key exists in both languages (test/sedens-i18n.test.mjs).
// Copy rules: general fitness only; never diagnose, never promise supervision or
// clinical outcomes; say plainly what is a demonstration or a simulation.

export const STRINGS = {
  en: {
    "brand.company": "SEDENS International",
    "brand.product": "SEDENS AI Private Room",
    "lang.toggle": "한국어",
    "notice.fitness": "SEDENS is a general fitness service. It does not diagnose or treat any condition.",
    "mode.demo_free": "Free demonstration",
    "mode.local_room": "Local room",
    "mode.storage_warning": "Demonstration storage: records and uploads can be erased whenever this server restarts.",
    "home.title": "A private room for your own guided session.",
    "home.lead": "Step into a quiet room at your gym or studio. SEDENS guides a session for you on the screen, without a coach watching.",
    "home.enter": "Enter AI Private Room",
    "home.enter_hint": "Opens the room screen. A room must be paired by your facility.",
    "home.cards": "SEDENS for everyone in the facility",
    "home.passport": "Fitness Passport",
    "home.passport_body": "Your visits, sessions and progress in one place. Arrives in a later phase.",
    "home.creator": "Creator Studio",
    "home.creator_body": "Coaches and professors build structured courses. Profile and facility affiliations are available now.",
    "home.facility": "Facility console",
    "home.facility_body": "Pair room screens, set booking rules and approve creators who want to offer content to your members.",
    "home.workspace": "Coaching workspace",
    "home.workspace_body": "The existing professional workspace: clients, assessments, programs and anatomy.",
    "home.open": "Open",
    "home.code_title": "Room code",
    "home.code_body": "Open this page on your own phone, signed in, and get a code to type on the room screen. You never sign in on the shared screen.",
    "home.code_get": "Get a room code",
    "home.code_value": "Your room code: {code}",
    "home.code_expires": "Use it within 5 minutes, once. It works only at your facility.",
    "home.soon": "Later phase",
    "auth.signin": "Sign in",
    "auth.signout": "Sign out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signed_in_as": "Signed in as {name}",
    "auth.demo_title": "Explore the demonstration",
    "auth.demo_body": "A fictional facility, \"SEDENS Demo Fitness Center\", with simulated room access. Nothing here is a real person or a real transaction.",
    "auth.demo_customer": "Customer",
    "auth.demo_coach": "Coach",
    "auth.demo_admin": "Facility admin",
    "auth.demo_preparing": "Preparing the demonstration. The first opening can take a minute.",
    "auth.creator_signup": "Independent professor or expert? Create a creator studio",
    "auth.name": "Your name",
    "auth.display_name": "Public creator name",
    "auth.creator_type": "Creator type",
    "auth.type_professor": "Professor",
    "auth.type_expert": "Expert",
    "auth.create": "Create creator studio",
    "common.back": "Back to SEDENS home",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading…",
    "common.error": "Something went wrong. Try again.",
    "common.demo": "DEMO",
    "common.simulated": "SIMULATED",
    "facility.title": "Facility console",
    "facility.need_admin": "Sign in as this facility's administrator to manage rooms and creators.",
    "facility.rooms": "Rooms and screens",
    "facility.rooms_hint": "Rooms are created in the coaching workspace under Locations. Pair a screen by entering the code it shows.",
    "facility.no_rooms": "No rooms yet. Add one to a location in the coaching workspace.",
    "facility.pair_code": "Code shown on the room screen",
    "facility.pair_room": "Room",
    "facility.pair_name": "Screen name",
    "facility.pair": "Pair screen",
    "facility.paired": "Screen paired. It will open on the room screen within a few seconds.",
    "facility.revoke": "Unpair",
    "facility.device_active": "Paired",
    "facility.device_waiting": "Waiting for the screen",
    "facility.device_revoked": "Unpaired",
    "facility.last_seen": "Last seen {time}",
    "facility.crm": "Room access rules",
    "facility.crm_provider": "Facility system: {provider}",
    "facility.crm_none": "No CRM connected. Customers sign in on the room screen with their SEDENS account.",
    "facility.crm_demo": "Demonstration CRM (simulated memberships and bookings).",
    "facility.require_booking": "Require a booking for this room",
    "facility.grace": "Early entry allowed (minutes before the booking)",
    "facility.creators": "Creator permissions",
    "facility.creators_hint": "Creator tools let a coach author content. They never change who can see your members' records.",
    "facility.grant": "Allow creator tools",
    "facility.revoke_creator": "Remove creator tools",
    "facility.affiliations": "Creators who want to offer content to your members",
    "facility.affiliations_hint": "Approving lets this creator offer content to your facility. It gives no access to your members or their records.",
    "facility.no_affiliations": "No requests.",
    "facility.approve": "Approve",
    "facility.decline": "Decline",
    "facility.code": "Your facility code for creators: {code}",
    "creator.title": "Creator Studio",
    "creator.need_capability": "Creator tools are not enabled for this account. A facility administrator or SEDENS can enable them.",
    "creator.profile": "Creator profile",
    "creator.display_name": "Public name",
    "creator.bio": "Biography",
    "creator.institution": "Institution",
    "creator.type": "Creator type (self-declared)",
    "creator.verification": "Verification: {state}",
    "creator.verify_request": "Ask SEDENS to verify my profile",
    "creator.state_unverified": "not verified",
    "creator.state_pending": "waiting for SEDENS review",
    "creator.state_verified": "verified by SEDENS",
    "creator.state_rejected": "not approved",
    "creator.state_suspended": "suspended",
    "creator.affiliations": "Facilities you can offer content to",
    "creator.affiliation_hint": "An approved facility lets you offer content to its members. It never gives you access to their records.",
    "creator.request_affiliation": "Request to offer content to a facility",
    "creator.facility_code": "Facility code",
    "creator.request": "Send request",
    "creator.courses_soon": "Course building arrives in the next phase.",
    "account.consents": "Your choices",
    "account.agree": "Agree",
    "account.disagree": "Do not agree",
    "account.current": "Current choice: {choice}",
    "account.none": "not decided",
    "room.title": "AI Private Room",
    "room.not_paired": "This screen is not a SEDENS room yet",
    "room.not_paired_body": "Ask facility staff to pair this screen with a room. Pairing takes under a minute.",
    "room.start_pairing": "Show pairing code",
    "room.pairing_code": "Pairing code",
    "room.pairing_instructions": "A facility administrator enters this code in the SEDENS facility console. The code expires in 10 minutes.",
    "room.pairing_expired": "The code expired. Show a new one.",
    "room.use_demo": "Use a demonstration room (simulated)",
    "room.welcome": "Welcome to {room}",
    "room.facility_line": "{facility} · {location}",
    "room.entry_title": "Start your room session",
    "room.entry_code": "Membership or booking code",
    "room.entry_code_hint": "Type the room code from your phone, or scan or type your facility QR code.",
    "room.entry_member": "Member number",
    "room.entry_pin": "PIN",
    "room.screen_account": "An account is signed in on this shared screen. Sign it out before anyone enters.",
    "room.sign_out_screen": "Sign out this screen",
    "room.enter": "Enter",
    "room.demo_codes": "Demonstration memberships (fictional)",
    "room.demo_booked": "Active · booked for this room",
    "room.demo_no_booking": "Active · no booking",
    "room.demo_inactive": "Inactive membership",
    "room.demo_other_room": "Active · booked for another room",
    "room.session_title": "Hello, {name}",
    "room.session_body": "Your private room session is open until {time}.",
    "room.next_steps": "Your session",
    "room.step_readiness": "A short check that today is a good day to exercise alone",
    "room.step_scan": "A guided camera check from four sides",
    "room.step_session": "A session chosen from the SEDENS exercise library",
    "room.coming": "Arrives in the next phase",
    "room.library_count": "{count} exercises are available in this room. Content not yet reviewed for SEDENS Standard.",
    "room.end": "End session",
    "room.ended": "Session ended. Thank you.",
    "room.help": "Need help? Stop at any time and contact facility staff. In an emergency, call 119.",
    "room.simulated_access": "Room access on this screen is simulated for the demonstration.",
  },
  ko: {
    "brand.company": "SEDENS International",
    "brand.product": "SEDENS AI 프라이빗 룸",
    "lang.toggle": "English",
    "notice.fitness": "SEDENS는 일반 피트니스 서비스이며, 어떤 질환도 진단하거나 치료하지 않습니다.",
    "mode.demo_free": "무료 시연",
    "mode.local_room": "로컬 룸",
    "mode.storage_warning": "시연용 저장소: 서버가 다시 시작되면 기록과 업로드가 삭제될 수 있습니다.",
    "home.title": "나만의 가이드 세션을 위한 프라이빗 룸.",
    "home.lead": "다니는 헬스장이나 스튜디오의 조용한 룸에 들어가세요. 코치가 지켜보지 않아도 SEDENS가 화면에서 세션을 안내합니다.",
    "home.enter": "AI 프라이빗 룸 입장",
    "home.enter_hint": "룸 화면을 엽니다. 룸은 시설에서 페어링해야 합니다.",
    "home.cards": "시설의 모든 분을 위한 SEDENS",
    "home.passport": "피트니스 패스포트",
    "home.passport_body": "방문, 세션, 진행 기록을 한곳에서 봅니다. 이후 단계에서 제공됩니다.",
    "home.creator": "크리에이터 스튜디오",
    "home.creator_body": "코치와 교수가 체계적인 코스를 만듭니다. 프로필과 시설 제휴는 지금 사용할 수 있습니다.",
    "home.facility": "시설 콘솔",
    "home.facility_body": "룸 화면을 페어링하고, 예약 규칙을 정하고, 회원에게 콘텐츠를 제공하려는 크리에이터를 승인합니다.",
    "home.workspace": "코칭 워크스페이스",
    "home.workspace_body": "기존 전문가용 워크스페이스: 고객, 평가, 프로그램, 해부학.",
    "home.open": "열기",
    "home.code_title": "룸 코드",
    "home.code_body": "본인 휴대폰에서 로그인한 상태로 이 페이지를 열고, 룸 화면에 입력할 코드를 받으세요. 공용 화면에서는 로그인하지 않습니다.",
    "home.code_get": "룸 코드 받기",
    "home.code_value": "나의 룸 코드: {code}",
    "home.code_expires": "5분 안에 한 번만 사용할 수 있으며, 내 시설에서만 유효합니다.",
    "home.soon": "이후 단계",
    "auth.signin": "로그인",
    "auth.signout": "로그아웃",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.signed_in_as": "{name} 님으로 로그인됨",
    "auth.demo_title": "시연 둘러보기",
    "auth.demo_body": "가상의 시설 \"SEDENS Demo Fitness Center\"와 시뮬레이션된 룸 출입입니다. 실제 인물이나 실제 거래가 아닙니다.",
    "auth.demo_customer": "고객",
    "auth.demo_coach": "코치",
    "auth.demo_admin": "시설 관리자",
    "auth.demo_preparing": "시연을 준비하고 있습니다. 처음 열 때 1분 정도 걸릴 수 있습니다.",
    "auth.creator_signup": "독립 교수 또는 전문가이신가요? 크리에이터 스튜디오 만들기",
    "auth.name": "이름",
    "auth.display_name": "공개 크리에이터 이름",
    "auth.creator_type": "크리에이터 유형",
    "auth.type_professor": "교수",
    "auth.type_expert": "전문가",
    "auth.create": "크리에이터 스튜디오 만들기",
    "common.back": "SEDENS 홈으로",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.loading": "불러오는 중…",
    "common.error": "문제가 발생했습니다. 다시 시도해 주세요.",
    "common.demo": "시연",
    "common.simulated": "시뮬레이션",
    "facility.title": "시설 콘솔",
    "facility.need_admin": "룸과 크리에이터를 관리하려면 이 시설의 관리자로 로그인하세요.",
    "facility.rooms": "룸과 화면",
    "facility.rooms_hint": "룸은 코칭 워크스페이스의 지점(Locations)에서 만듭니다. 화면에 표시된 코드를 입력해 페어링하세요.",
    "facility.no_rooms": "아직 룸이 없습니다. 코칭 워크스페이스에서 지점에 룸을 추가하세요.",
    "facility.pair_code": "룸 화면에 표시된 코드",
    "facility.pair_room": "룸",
    "facility.pair_name": "화면 이름",
    "facility.pair": "화면 페어링",
    "facility.paired": "화면이 페어링되었습니다. 몇 초 안에 룸 화면이 열립니다.",
    "facility.revoke": "페어링 해제",
    "facility.device_active": "페어링됨",
    "facility.device_waiting": "화면 대기 중",
    "facility.device_revoked": "해제됨",
    "facility.last_seen": "최근 접속 {time}",
    "facility.crm": "룸 출입 규칙",
    "facility.crm_provider": "시설 시스템: {provider}",
    "facility.crm_none": "연결된 CRM이 없습니다. 고객은 룸 화면에서 SEDENS 계정으로 로그인합니다.",
    "facility.crm_demo": "시연용 CRM (시뮬레이션된 회원권과 예약).",
    "facility.require_booking": "이 룸 이용 시 예약 필요",
    "facility.grace": "예약 시간 전 입장 허용 (분)",
    "facility.creators": "크리에이터 권한",
    "facility.creators_hint": "크리에이터 도구는 코치가 콘텐츠를 만들 수 있게 합니다. 회원 기록을 볼 수 있는 사람은 바뀌지 않습니다.",
    "facility.grant": "크리에이터 도구 허용",
    "facility.revoke_creator": "크리에이터 도구 해제",
    "facility.affiliations": "회원에게 콘텐츠를 제공하려는 크리에이터",
    "facility.affiliations_hint": "승인하면 이 크리에이터가 시설에 콘텐츠를 제공할 수 있습니다. 회원이나 회원 기록에 대한 접근 권한은 주어지지 않습니다.",
    "facility.no_affiliations": "요청이 없습니다.",
    "facility.approve": "승인",
    "facility.decline": "거절",
    "facility.code": "크리에이터에게 알려줄 시설 코드: {code}",
    "creator.title": "크리에이터 스튜디오",
    "creator.need_capability": "이 계정에는 크리에이터 도구가 활성화되어 있지 않습니다. 시설 관리자 또는 SEDENS가 활성화할 수 있습니다.",
    "creator.profile": "크리에이터 프로필",
    "creator.display_name": "공개 이름",
    "creator.bio": "소개",
    "creator.institution": "소속 기관",
    "creator.type": "크리에이터 유형 (본인 기재)",
    "creator.verification": "인증: {state}",
    "creator.verify_request": "SEDENS에 프로필 인증 요청",
    "creator.state_unverified": "인증되지 않음",
    "creator.state_pending": "SEDENS 검토 대기 중",
    "creator.state_verified": "SEDENS 인증 완료",
    "creator.state_rejected": "승인되지 않음",
    "creator.state_suspended": "일시 중지됨",
    "creator.affiliations": "콘텐츠를 제공할 수 있는 시설",
    "creator.affiliation_hint": "승인된 시설의 회원에게 콘텐츠를 제공할 수 있습니다. 회원 기록에 대한 접근 권한은 주어지지 않습니다.",
    "creator.request_affiliation": "시설에 콘텐츠 제공 요청",
    "creator.facility_code": "시설 코드",
    "creator.request": "요청 보내기",
    "creator.courses_soon": "코스 제작 기능은 다음 단계에서 제공됩니다.",
    "account.consents": "나의 선택",
    "account.agree": "동의",
    "account.disagree": "동의하지 않음",
    "account.current": "현재 선택: {choice}",
    "account.none": "결정하지 않음",
    "room.title": "AI 프라이빗 룸",
    "room.not_paired": "이 화면은 아직 SEDENS 룸이 아닙니다",
    "room.not_paired_body": "시설 직원에게 이 화면을 룸과 페어링해 달라고 요청하세요. 1분이 채 걸리지 않습니다.",
    "room.start_pairing": "페어링 코드 표시",
    "room.pairing_code": "페어링 코드",
    "room.pairing_instructions": "시설 관리자가 SEDENS 시설 콘솔에 이 코드를 입력합니다. 코드는 10분 후 만료됩니다.",
    "room.pairing_expired": "코드가 만료되었습니다. 새 코드를 표시하세요.",
    "room.use_demo": "시연용 룸 사용 (시뮬레이션)",
    "room.welcome": "{room}에 오신 것을 환영합니다",
    "room.facility_line": "{facility} · {location}",
    "room.entry_title": "룸 세션 시작",
    "room.entry_code": "회원권 또는 예약 코드",
    "room.entry_code_hint": "휴대폰에서 받은 룸 코드를 입력하거나, 시설 QR 코드를 스캔 또는 입력하세요.",
    "room.entry_member": "회원 번호",
    "room.entry_pin": "PIN",
    "room.screen_account": "공용 화면에 계정이 로그인되어 있습니다. 입장 전에 로그아웃하세요.",
    "room.sign_out_screen": "이 화면 로그아웃",
    "room.enter": "입장",
    "room.demo_codes": "시연용 회원권 (가상)",
    "room.demo_booked": "유효 · 이 룸 예약됨",
    "room.demo_no_booking": "유효 · 예약 없음",
    "room.demo_inactive": "만료된 회원권",
    "room.demo_other_room": "유효 · 다른 룸 예약됨",
    "room.session_title": "{name} 님, 안녕하세요",
    "room.session_body": "프라이빗 룸 세션은 {time}까지 열려 있습니다.",
    "room.next_steps": "나의 세션",
    "room.step_readiness": "오늘 혼자 운동해도 괜찮은지 확인하는 짧은 질문",
    "room.step_scan": "네 방향에서 진행하는 카메라 안내 확인",
    "room.step_session": "SEDENS 운동 라이브러리에서 고른 세션",
    "room.coming": "다음 단계에서 제공",
    "room.library_count": "이 룸에서 {count}개의 운동을 이용할 수 있습니다. SEDENS Standard 검토 전 콘텐츠입니다.",
    "room.end": "세션 종료",
    "room.ended": "세션이 종료되었습니다. 감사합니다.",
    "room.help": "도움이 필요하신가요? 언제든 멈추고 시설 직원에게 연락하세요. 응급 상황에서는 119에 전화하세요.",
    "room.simulated_access": "이 화면의 룸 출입은 시연을 위해 시뮬레이션된 것입니다.",
  },
};
