/**
 * What every control and every readout means — twice.
 *
 * `plain` is what it does, in words anyone can act on. `tech` is what it is, in the terms a
 * clinician or an anatomist would use, including where the number comes from. The panel's
 * existing Plain / Clinical / Both register decides which of them a reader sees, so this is
 * not a second vocabulary bolted on — it is the same choice already made for the anatomy,
 * extended to the instrument.
 *
 * The rule for writing an entry: the plain sentence must be true, not merely friendly, and
 * the technical one must say where the thing comes from. Where a control shows something the
 * application computed rather than measured, the entry has to say so — that is the whole
 * reason this file exists rather than a tooltip saying "toggle the scan".
 *
 * Every entry is en + ko. `test/content.test.mjs` walks the table and fails the build on a
 * missing half.
 */
export const HELP = {
  /* ------------------------------------------------------------------ the scan */
  scanPlane: {
    plain: { en: 'Slices the brain with a flat plane, like a bread knife, and lights up the line where the plane meets the surface. The three buttons choose which way the knife is held.',
             ko: '평면으로 뇌를 자르고, 그 평면이 표면과 만나는 선을 밝힙니다. 세 버튼은 자르는 방향을 고릅니다.' },
    tech: { en: 'Lights fragments whose signed distance to the plane is within a narrow band, computed per fragment in the organ’s own frame. Nothing is clipped and no geometry is cut — the visible contour is the intersection of the plane with the model’s surfaces, recomputed as the plane moves.',
            ko: '평면까지의 부호 있는 거리가 좁은 범위 안에 있는 프래그먼트를 밝힙니다. 계산은 장기 자체 좌표계에서 프래그먼트마다 이루어집니다. 잘라내는 것도, 지오메트리를 절단하는 것도 아니며, 보이는 윤곽은 평면과 모델 표면의 교선으로 평면이 움직일 때마다 다시 계산됩니다.' },
  },
  sagittal: {
    plain: { en: 'Cuts from front to back, splitting left from right — the view you would get slicing a head down the middle from the nose to the back of the skull.',
             ko: '앞뒤 방향으로 잘라 좌우를 나눕니다. 코에서 뒤통수까지 머리 한가운데를 가르는 단면입니다.' },
    tech: { en: 'The plane whose normal runs along the left–right (x) axis. Named for the section it produces, not for its own normal.',
            ko: '법선이 좌우(x) 축을 따르는 평면입니다. 평면 자체의 법선이 아니라 만들어지는 단면의 이름을 따릅니다.' },
  },
  coronal: {
    plain: { en: 'Cuts ear to ear, splitting front from back — like a slice taken straight down through a crown.',
             ko: '귀에서 귀로 잘라 앞뒤를 나눕니다. 정수리에서 곧장 아래로 내려 자른 단면입니다.' },
    tech: { en: 'The plane whose normal runs along the anterior–posterior (z) axis. Also called the frontal plane.',
            ko: '법선이 앞뒤(z) 축을 따르는 평면입니다. 전두면이라고도 합니다.' },
  },
  axial: {
    plain: { en: 'Cuts flat across, splitting top from bottom — the view in most brain scans, as if you were looking down at a slice taken off the top of the head.',
             ko: '수평으로 잘라 위아래를 나눕니다. 대부분의 뇌 영상에서 보는 방향으로, 머리 위쪽을 잘라 내려다보는 모습입니다.' },
    tech: { en: 'The plane whose normal runs along the superior–inferior (y) axis. Also called the transverse or horizontal plane; it is the standard orientation for CT and most MRI series.',
            ko: '법선이 위아래(y) 축을 따르는 평면입니다. 횡단면 또는 수평면이라고도 하며, CT와 대부분의 MRI 시리즈의 표준 방향입니다.' },
  },
  sweep: {
    plain: { en: 'Runs the plane slowly from one side of the brain to the other and back again, so you can watch the shape of the cut change instead of dragging it yourself.',
             ko: '평면을 뇌의 한쪽 끝에서 반대쪽까지 천천히 왕복시킵니다. 직접 끌지 않아도 단면의 모양이 변하는 것을 볼 수 있습니다.' },
    tech: { en: 'Drives the plane’s position as a sine of elapsed time across the organ’s full extent. It returns the way it came rather than jumping back, so the series is continuous in both directions.',
            ko: '경과 시간의 사인 함수로 평면 위치를 장기의 전체 범위에 걸쳐 움직입니다. 되돌아갈 때 건너뛰지 않고 왔던 길을 되짚으므로 양방향 모두 연속적입니다.' },
  },
  scanAt: {
    plain: { en: 'Where the cut is, from one side of the brain to the other. The middle of the slider is the middle of the brain.',
             ko: '자르는 위치입니다. 슬라이더의 가운데가 뇌의 가운데입니다.' },
    tech: { en: 'Signed offset along the plane’s normal, normalised to the cortex’s bounding radius: −1 and +1 are the two extremes of the organ, 0 is its centroid.',
            ko: '평면 법선을 따른 부호 있는 오프셋으로, 피질의 경계 반지름으로 정규화됩니다. −1과 +1은 장기의 양 끝, 0은 중심입니다.' },
  },
  sections: {
    plain: { en: 'Five cuts through the brain at five evenly spaced places, so you can see the whole series at once, and the numbers say how far from the middle each one is. The bright lines are where the plane meets a surface — mostly the folded outer sheet of the brain, which is why a cut through the middle looks like tangled ribbon rather than a solid slice. The dark areas are where the plane passes through nothing: the fluid spaces inside the brain, the gaps between folds, and everything outside the head. The words under each one name the structures that cut actually goes through. Click one to move the big plane there.',
             ko: '일정한 간격의 다섯 위치에서 자른 단면으로, 전체 시리즈를 한눈에 봅니다. 각 아래의 숫자는 뇌 중심에서의 거리(밀리미터)입니다. 하나를 클릭하면 큰 평면이 그 위치로 이동합니다.' },
    tech: { en: 'Orthographic renders down the plane’s own normal, lighting only the band within a hair of the plane, so each thumbnail is a true section of the model’s surfaces. Brightness is accumulation: the band is drawn additively with depth off, so a place where several walls of cortex cross the plane close together is brighter than a place where one does. Darkness therefore means an absence of surface at that depth, not an absence of tissue — the ventricles, the space between opposed gyri, and the field outside the brain all read the same way, because this model holds surfaces and not a filled volume. Positions are in fsaverage millimetres from the cortex centroid. These are not imaging data: there is no T1, no segmentation volume and no voxel anywhere in this application, and nothing here has been measured on a person.',
            ko: '평면 법선 방향의 정사영 렌더링으로, 평면에 아주 가까운 띠만 밝히므로 각 썸네일은 모델 표면의 실제 단면입니다. 위치는 피질 중심에서의 fsaverage 밀리미터 값입니다. 영상 데이터가 아닙니다. 이 앱에는 T1도, 분할 볼륨도, 복셀도 없으며, 사람에게서 측정한 것은 아무것도 없습니다.' },
  },

  /* ---------------------------------------------------------------- the looks */
  brainLook: {
    plain: { en: 'Three ways of drawing the same brain. None is more real than the others — they answer different questions. See-through for looking inside, solid for telling regions apart, cells only for watching the activity move.',
             ko: '같은 뇌를 그리는 세 가지 방식입니다. 어느 쪽이 더 진짜인 것은 아니며, 서로 다른 질문에 답합니다. 투과는 안쪽을 보기 위해, 불투명은 영역을 구분하기 위해, 세포만은 활동이 움직이는 것을 보기 위해 쓰입니다.' },
    tech: { en: 'All three use the identical fsaverage geometry and the identical Desikan-Killiany parcellation. Only the material and what is drawn differ; selection, hover, atlas colouring and exercise activation are one shared palette and carry across the switch unchanged.',
            ko: '세 방식 모두 동일한 fsaverage 지오메트리와 동일한 Desikan-Killiany 분할을 사용합니다. 재질과 무엇을 그리는지만 다르며, 선택·호버·아틀라스 색상·운동 활성은 하나의 공유 팔레트를 쓰므로 전환해도 그대로 유지됩니다.' },
  },
  lookTissue: {
    plain: { en: 'See-through, so you can look into the brain and watch the cells fire inside it. Better for depth and for the network. Harder for telling exactly where one region stops.',
             ko: '속이 비쳐 보여 뇌 안쪽과 세포의 발화를 볼 수 있습니다. 깊이와 신경망을 보기에 좋고, 영역의 경계를 정확히 가리기에는 불리합니다.' },
    tech: { en: 'An emission integral: additive blending, depth-write off, both faces drawn, so a ray accumulates every wall of tissue it crosses. Overlapping folds brighten on their own, which is why sulci read as depth with no shadow computed.',
            ko: '발광 적분 방식입니다. 가산 혼합, 깊이 쓰기 끔, 양면 렌더링이므로 광선이 통과하는 모든 조직 벽이 누적됩니다. 겹친 주름이 스스로 밝아지기 때문에 그림자 계산 없이도 뇌구가 깊이로 읽힙니다.' },
  },
  lookAnatomical: {
    plain: { en: 'Solid, with each region a flat block of colour and a hard edge — the way a printed atlas plate looks. Better for telling regions apart. You cannot see inside it, so the network is hidden.',
             ko: '불투명하며 각 영역이 단색 블록과 뚜렷한 경계로 표시됩니다. 인쇄된 해부 아틀라스와 같은 모습입니다. 영역 구분에 좋지만 안쪽은 보이지 않아 신경망은 가려집니다.' },
    tech: { en: 'A lit physical surface with the parcel palette applied to base colour. It is the only look that x-ray and cutaway can act on, because both are properties of a surface with an inside.',
            ko: '광원에 반응하는 물리 기반 표면에 분할 팔레트를 기본 색상으로 적용합니다. 엑스레이와 절개는 안쪽이 있는 표면에서만 의미가 있으므로 이 방식에서만 작동합니다.' },
  },

  lookNeurons: {
    plain: { en: 'The brain’s surface is taken away and only the cells are left, with the sparks of activity running along the threads between them. Each speck is still one patch of tissue in its real place, so the shape you see is the shape of the brain. Hover any speck to find out which region it belongs to and what that region does.',
             ko: '뇌 표면을 걷어내고 세포만 남깁니다. 세포를 잇는 실을 따라 활동의 불꽃이 흐릅니다. 각 점은 여전히 실제 위치에 있는 조직 한 구획이므로, 보이는 형태는 뇌의 형태 그대로입니다. 아무 점에나 마우스를 올리면 어느 영역에 속하고 그 영역이 무슨 일을 하는지 알 수 있습니다.' },
    tech: { en: 'The same node cloud and the same edges as the other looks, with every brain surface hidden. The travelling impulses are not new here — each edge vertex carries how far along its own edge it sits, so the fragment lights where a moving band crosses it, with no per-frame CPU work — they are simply visible now that there is no tissue in front of them. Node size and fibre gain are raised, because values tuned to sit under a cortex read as dust in an empty frame; the point-size clamp stays, since a soma stands for a population far below this model’s resolution and must not grow without limit.',
            ko: '다른 표현과 동일한 노드 구름과 간선을 쓰되, 모든 뇌 표면을 숨깁니다. 이동하는 임펄스는 새로운 것이 아닙니다. 각 간선의 정점은 자신이 간선의 어디쯤에 있는지를 지니고 있어, 움직이는 띠가 지날 때 프래그먼트가 밝아집니다. 프레임마다의 CPU 작업은 없습니다. 앞을 가리는 조직이 사라져 이제 보일 뿐입니다. 노드 크기와 섬유 밝기는 높였습니다. 피질 아래에 놓이도록 맞춘 값은 빈 화면에서는 먼지처럼 보이기 때문입니다. 점 크기 상한은 유지됩니다. 하나의 세포체는 이 모델의 해상도보다 훨씬 작은 집단을 나타내므로 무한정 커져서는 안 됩니다.' },
  },

  /* -------------------------------------------------------------- the network */
  network: {
    plain: { en: 'The bright specks and threads inside the brain. Each speck stands for a patch of brain tissue, placed on the actual surface, and the threads join specks that sit near each other. When you pick a region, the specks in it fire harder.',
             ko: '뇌 안쪽의 밝은 점과 실입니다. 각 점은 실제 표면 위에 놓인 뇌 조직 한 구획을 나타내고, 실은 가까운 점끼리를 잇습니다. 영역을 선택하면 그 안의 점들이 더 강하게 발화합니다.' },
    tech: { en: 'Nodes are sampled from the cortex’s own vertices, so each one carries the Desikan-Killiany parcel it was drawn from and the clusters are anatomical regions rather than a layout. Edges are nearest-neighbour links plus a small fraction of long-range ones. It is a schematic of connectivity, not a connectome: no tractography, no diffusion imaging, and no claim about which region projects to which.',
            ko: '노드는 피질 자체의 정점에서 표본화되므로 각 노드는 추출된 Desikan-Killiany 분할 영역을 그대로 가지며, 군집은 배치가 아니라 실제 해부 영역입니다. 간선은 최근접 이웃 연결과 소수의 장거리 연결입니다. 이는 연결성의 도식이며 커넥톰이 아닙니다. 신경섬유 추적도, 확산 영상도 없고, 어느 영역이 어디로 투사하는지에 대한 주장도 하지 않습니다.' },
  },
  networkDrive: {
    plain: { en: 'How busy the network is right now, on a scale from nothing to one. It rises when you select a region or run a scan, because both make cells fire.',
             ko: '지금 신경망이 얼마나 활발한지를 0에서 1까지로 나타냅니다. 영역을 선택하거나 스캔을 실행하면 세포가 발화하므로 값이 올라갑니다.' },
    tech: { en: 'The same activity scalar the shaders are given, sampled once per frame and traced over time. It is a property of the animation, not a physiological measurement — there is no EEG, no fMRI and no recorded signal anywhere in this application.',
            ko: '셰이더에 전달되는 것과 동일한 활동 스칼라를 프레임마다 한 번 표본화해 시간축으로 그린 것입니다. 애니메이션의 속성이지 생리학적 측정이 아닙니다. 이 앱에는 뇌파도, 기능적 MRI도, 기록된 신호도 없습니다.' },
  },
  cellsRead: {
    plain: { en: 'How many specks are drawn inside the brain at the moment.',
             ko: '현재 뇌 안에 그려진 점의 개수입니다.' },
    tech: { en: 'Node count of the network built from the loaded cortex. A node stands for a population far below the resolution of any model here; it is not a neuron and carries no per-cell measurement.',
            ko: '불러온 피질에서 만들어진 신경망의 노드 수입니다. 한 노드는 이 모델의 해상도보다 훨씬 작은 집단을 나타냅니다. 개별 뉴런이 아니며 세포별 측정값도 없습니다.' },
  },
  regionsRead: {
    plain: { en: 'How many named brain regions this model carries.',
             ko: '이 모델이 담고 있는 이름 붙은 뇌 영역의 수입니다.' },
    tech: { en: 'Parcels of the Desikan-Killiany atlas plus the subcortical structures segmented from aseg.mgz, counted as registered in the structure table.',
            ko: 'Desikan-Killiany 아틀라스의 분할 영역과 aseg.mgz에서 분할한 피질하 구조를, 구조 테이블에 등록된 대로 센 값입니다.' },
  },
  structuresRead: {
    plain: { en: 'How many separate parts of the body are loaded and clickable right now.',
             ko: '지금 불러와져 클릭할 수 있는 신체 부위의 개수입니다.' },
    tech: { en: 'Registered structures across every loaded layer — bones, muscles, organs, nerves and brain regions — each an individually segmented mesh with its own id.',
            ko: '불러온 모든 레이어에 등록된 구조의 수입니다. 뼈·근육·장기·신경·뇌 영역이 포함되며, 각각 고유 id를 가진 개별 분할 메시입니다.' },
  },
  cellProbe: {
    plain: { en: 'Hover a speck inside the brain and it tells you which region it was taken from, what that region does, and how hard it is firing at this instant.',
             ko: '뇌 안의 점 위에 마우스를 올리면 그 점이 어느 영역에서 나왔는지, 그 영역이 무슨 일을 하는지, 지금 얼마나 강하게 발화하는지 알려줍니다.' },
    tech: { en: 'The firing figure is the same value the vertex shader is using to light that node, recomputed on the CPU for the one node under the pointer. There is no per-cell measurement in this application and there will not be: inventing a score for a single cell would look exactly like an instrument reading and would be a fabrication.',
            ko: '표시되는 발화 값은 정점 셰이더가 해당 노드를 밝히는 데 쓰는 값과 동일하며, 포인터 아래 노드 하나에 대해 CPU에서 다시 계산한 것입니다. 이 앱에는 세포별 측정값이 없으며 앞으로도 없을 것입니다. 세포 하나에 점수를 지어내면 계측값처럼 보이지만 그것은 날조입니다.' },
  },

  connectome: {
    plain: { en: 'The same network as a map. Each dot is one region of the brain’s outer surface, drawn where that region actually sits, and its size is how many cells it holds. Lines join regions that have threads running between them. Touch a dot to light it up; click it to select that region in the picture. Structures deep inside the brain are not here, because the cells were sampled from the surface.',
             ko: '같은 신경망을 지도로 나타낸 것입니다. 각 점은 뇌 영역 하나이며 실제 위치에 그려지고, 크기는 담고 있는 세포 수입니다. 선은 서로 실이 이어진 영역을 잇습니다. 점에 마우스를 올리면 강조되고, 클릭하면 그 영역이 화면에서 선택됩니다.' },
    tech: { en: 'One node per cortical parcel at its own centroid, projected onto the sagittal plane, so the layout is anatomy rather than a force simulation. It covers the Desikan-Killiany parcels the node cloud was sampled from — fewer than the region count in the readout at the top left, which also counts the subcortical structures the network does not reach, and no node stands for unparcellated cortex. Node weight is cell count; edge weight is how many axons in this network run between the two parcels, counted out of the buffers the picture is drawn from. It is not a connectome: the edges are nearest-neighbour links plus a small fraction of long-range ones, there is no tractography and no diffusion imaging anywhere in this application, and no claim is made about which region projects to which in a real brain.',
            ko: '분할 영역마다 하나의 노드를 그 중심에 두고 시상면에 투영하므로, 배치는 힘 기반 시뮬레이션이 아니라 해부학적 위치입니다. 노드의 크기는 세포 수이고, 간선의 굵기는 이 신경망에서 두 영역 사이를 지나는 축삭의 수로, 화면을 그리는 버퍼에서 직접 센 값입니다. 커넥톰이 아닙니다. 간선은 최근접 이웃 연결과 소수의 장거리 연결이며, 이 앱에는 신경섬유 추적도 확산 영상도 없고, 실제 뇌에서 어느 영역이 어디로 투사하는지에 대한 주장도 하지 않습니다.' },
  },

  labScreen: {
    plain: { en: 'A full screen for the things the side panel is too narrow to show properly: the network as a ring and as a map, what every joint and every muscle does across the exercise you have chosen, and how strong the evidence behind this application’s brain claims actually is. Each panel says underneath what it is and where its numbers come from. Press Escape or the cross to come back.',
             ko: '옆 패널이 좁아 제대로 보여줄 수 없는 것들을 위한 전체 화면입니다. 신경망을 고리와 지도로, 선택한 운동에서 각 관절과 근육이 무엇을 하는지, 그리고 이 앱의 뇌 관련 주장을 뒷받침하는 근거가 얼마나 강한지를 봅니다. 각 패널 아래에 그것이 무엇이고 숫자가 어디서 왔는지 적혀 있습니다. Esc 키나 닫기 표시를 누르면 돌아옵니다.' },
    tech: { en: 'Six panels over the live application: node and edge counts from the network currently built, per-parcel cell populations, the clip’s own joint coordinates converted from radians to degrees, per-muscle role interpolated between keyframes, and a count of every brain claim by evidence tier. The brief this was built against shows a dashboard of a learner’s weekly assessment scores; there are none in this application, no way to obtain one, and a series invented to fill that space would look exactly like a measurement. Nothing here is that.',
            ko: '실행 중인 앱 위에 놓인 여섯 개의 패널입니다. 현재 구축된 신경망의 노드·간선 수, 영역별 세포 수, 클립의 관절 좌표를 라디안에서 도로 변환한 값, 키프레임 사이를 보간한 근육별 역할, 그리고 근거 등급별 뇌 관련 주장 수를 보여줍니다. 이 화면의 바탕이 된 기획서에는 학습자의 주간 평가 점수 대시보드가 있지만, 이 앱에는 그런 점수가 없고 얻을 방법도 없으며, 그 자리를 채우려고 지어낸 수치는 측정값처럼 보일 것입니다. 여기에는 그런 것이 없습니다.' },
  },

  /* ------------------------------------------------------------ the lab panels */
  labConnectome: {
    plain: { en: 'The network in three dimensions, in the shape of the brain it came from. Every speck is one patch of cortex in its real place; the threads are the wiring between them, with sparks of activity travelling along them. Drag to turn it round, scroll to zoom, and click any speck to select the region it belongs to — the panel on the main view then tells you what that region does. The faint shell around it is the brain’s own outer surface, drawn from the far side so it does not block the view.',
             ko: '신경망을 3차원으로, 그것이 나온 뇌의 형태 그대로 보여줍니다. 각 점은 실제 위치에 있는 피질 한 구획이고, 실은 그 사이의 배선이며 활동의 불꽃이 실을 따라 이동합니다. 드래그로 돌리고, 스크롤로 확대하고, 아무 점이나 클릭하면 그 점이 속한 영역이 선택되어 본 화면 패널에 그 영역이 하는 일이 표시됩니다. 주위의 희미한 껍질은 뇌의 바깥 표면으로, 시야를 가리지 않도록 반대편에서 그렸습니다.' },
    tech: { en: 'The same node cloud and adjacency as the main stage, in the cortex’s own frame, rendered in its own WebGL context with its own orbit camera. Somas are additive points with the point size clamped, because a soma stands for a population far below this model’s resolution; fibres carry a travelling band computed from how far along its own edge a fragment sits, which is the same impulse the main view shows. The surround is the cortex geometry itself, back faces only at low opacity — shared, not copied. Selecting a region lifts its cells and its fibres and drops everything else to a tenth. It is not a connectome in the imaging sense: no tractography, no diffusion data, and no claim about which region projects to which in a real brain.',
            ko: '본 화면과 동일한 노드 구름과 인접 관계를 피질 자체 좌표계에서, 별도의 WebGL 컨텍스트와 궤도 카메라로 렌더링합니다. 세포체는 가산 점으로 그리며 점 크기를 제한합니다. 하나의 세포체는 이 모델의 해상도보다 훨씬 작은 집단을 나타내기 때문입니다. 섬유에는 프래그먼트가 자기 간선의 어디에 있는지로 계산한 이동 띠가 흐르며, 이는 본 화면에 보이는 것과 같은 임펄스입니다. 주위 껍질은 피질 지오메트리 자체로, 뒷면만 낮은 불투명도로 그리며 복사가 아니라 공유합니다. 영역을 선택하면 그 세포와 섬유가 밝아지고 나머지는 10분의 1로 어두워집니다. 영상의학적 의미의 커넥톰이 아닙니다. 신경섬유 추적도, 확산 데이터도, 실제 뇌의 투사 관계에 대한 주장도 없습니다.' },
  },
  labRegionMap: {
    plain: { en: 'The same wiring, with each region drawn where it actually sits, on a picture of the actual brain seen from the side. Front is on the right; the lump at the lower left is the cerebellum and the stalk below it is the brainstem. A bigger dot means more cells in that region; a brighter line between two dots means more wiring between those two regions. Every dot is named in the margin, in its own colour, on a line back to itself. Only the folded outer sheet is mapped this way, because that is where the cells in this model live — the deep structures are drawn but carry no dots. One more thing worth knowing: each dot stands for that region in BOTH halves of the brain, not just the half you can see. This atlas does not split its regions into left and right (except Broca’s and Wernicke’s areas, which are left-sided in most people and are labelled that way), so “frontal lobe” here means the frontal lobe on both sides counted together. The picture behind is the near half’s surface because you are looking at it from one side.',
             ko: '같은 배선을 각 영역이 실제로 있는 위치에 그리되, 옆에서 본 실제 뇌 위에 얹은 것입니다. 오른쪽이 앞이고, 왼쪽 아래의 덩어리가 소뇌, 그 아래로 내려가는 것이 뇌간입니다. 점이 클수록 그 영역의 세포가 많고, 두 점 사이 선이 밝을수록 두 영역 사이 배선이 많습니다. 모든 점은 자기 색으로 여백에 이름이 적히고 선으로 이어집니다. 이 모델의 세포는 접힌 바깥 껍질에만 있으므로 그 부분만 점으로 표시되며, 깊은 구조는 그려지되 점이 없습니다.' },
    tech: { en: 'One node per Desikan-Killiany parcel at its own centroid, projected onto the sagittal plane; node area scales with cell count and edge weight with the number of axons between the pair. The backdrop is an orthographic render of the fsaverage surface and every subcortical mesh, down the left–right axis, by the application’s own renderer from the same GPU buffers the scene draws — the geometry, not an illustration of it, and in the cortex geometry’s own frame, which is the frame the node positions are in, so it is placed rather than fitted. It replaced a silhouette traced from the sampled cells: honest, and a blob, because the hull of a sample of a folded sheet carries none of the shape a reader recognises. Parcels are not lateralised in this build — `build_cortex.py` assigns one id across both hemispheres, the exceptions being Broca’s and Wernicke’s areas, which are taken as left-hemisphere only — so a node is the centroid of that parcel’s cells in both halves and its count is their sum. It exists beside the connectome because the ring throws the anatomy away: a parcel’s place on a circle is an ordering, not a position.',
            ko: '각 Desikan-Killiany 분할 영역마다 하나의 노드를 그 중심에 두고 시상면에 투영합니다. 노드의 면적은 세포 수에, 간선의 굵기는 두 영역 사이 축삭 수에 비례합니다. 배경은 fsaverage 표면과 모든 피질하 메시를 좌우 축 방향에서 정사영으로 렌더링한 것으로, 앱 자체의 렌더러가 장면과 동일한 GPU 버퍼에서 그립니다. 삽화가 아니라 지오메트리 자체이며, 노드 좌표와 같은 프레임에서 측정되므로 맞춰 넣은 것이 아니라 그대로 놓인 것입니다. 이전에는 표본 세포에서 뽑은 실루엣이었는데, 정직하기는 해도 형태가 뭉개져 뇌로 읽히지 않았습니다. 고리는 해부학적 위치를 버리기 때문에 — 원 위의 자리는 순서일 뿐 위치가 아닙니다 — 연결 지도 옆에 이 지도가 필요합니다.' },
  },
  labFibres: {
    plain: { en: 'The whole network as a plot instead of a scene you turn: the brain with real millimetres up the side and along the bottom, measured from the middle of the cortex. Every one of the four thousand cells is a point and every fibre between two of them is a line. Nothing is summarised or thinned, so the places where the page fills in are the places where the wiring is genuinely dense; each colour is the region the fibre leaves from. Move the pointer over it and the cell under it is ringed and named, with its three millimetre coordinates. Scroll to zoom in — the cells grow as you go, so you can pick one out — drag to move around, and Reset puts it back. IMPORTANT about the three buttons: from the side, the left and right halves of the brain land exactly on top of each other, because you are looking straight down the line that separates them. Nothing is missing and no half has been thrown away. From above and from the front they come apart, and you can see both.',
             ko: '돌려 보는 장면이 아니라 그래프로 그린 신경망 전체입니다. 세로축과 가로축은 피질 중심에서 잰 실제 밀리미터입니다. 4천 개 세포가 각각 점 하나, 그 사이의 모든 섬유가 각각 선 하나입니다. 요약하거나 솎아내지 않았으므로 화면이 짙어진 곳은 실제로 배선이 밀집한 곳이며, 색은 섬유가 출발하는 영역입니다. 포인터를 올리면 그 아래 세포가 원으로 표시되고 이름과 세 개의 밀리미터 좌표가 나옵니다. 스크롤로 확대하면 세포도 함께 커져서 하나를 고를 수 있고, 드래그로 이동하며, 초기화로 되돌립니다. 세 개의 버튼에 대해 중요한 점: 옆에서 보면 좌뇌와 우뇌가 정확히 겹칩니다. 둘을 가르는 선을 정면으로 내려다보고 있기 때문입니다. 빠진 것도, 버린 반쪽도 없습니다. 위에서와 앞에서 보면 둘이 나뉘어 양쪽을 모두 볼 수 있습니다.' },
    tech: { en: 'An orthographic scatter of the network’s own buffers — the same node positions and the same edge index pairs the GPU is drawing, handed over uncopied by cellGraph(). Three projections: sagittal (y against z, the two hemispheres superimposed because x is the projection axis), axial (x against z) and coronal (y against x), the last two separating left from right. Lines are composited additively at low alpha, so density is accumulation rather than a binned heat map: nothing is aggregated, and a bright tract is many fibres in register. Axes are fsaverage millimetres from the cortex centroid through FRAME.scale, with the tick interval chosen from the current scale so the labels never collide. Zoom is about the pointer rather than the plot centre, and the point size grows with it under a cap — a soma stands for a population far below this model’s resolution, so its size is a symbol. Picking is nearest-within-radius over all nodes. This is a plot of the model’s network, not tractography: there is no diffusion data in this application, and the fibres are the nearest-neighbour plus long-range construction described under the connectome.',
            ko: '신경망 자체의 버퍼를 정사영으로 뿌린 산점도입니다. GPU가 그리는 것과 동일한 노드 좌표와 간선 색인 쌍을 cellGraph()가 복사 없이 넘겨줍니다. 세 가지 투영이 있습니다. 시상면(z 대 y, 투영축이 x이므로 두 반구가 겹침), 수평면(z 대 x), 관상면(x 대 y)이며 뒤의 둘은 좌우를 분리합니다. 선은 낮은 알파로 가산 합성되므로 밀도는 구간별 히트맵이 아니라 누적입니다. 축은 FRAME.scale로 환산한 피질 중심 기준 fsaverage 밀리미터이며, 눈금 간격은 현재 배율에서 라벨이 겹치지 않도록 선택합니다. 확대는 플롯 중심이 아니라 포인터를 기준으로 하고, 점 크기는 상한 아래에서 함께 커집니다. 세포체는 이 모델의 해상도보다 훨씬 아래의 집단을 나타내므로 그 크기는 상징입니다. 선택은 전체 노드에 대한 반경 내 최근접입니다. 이것은 모델 신경망의 그래프이지 신경로 추적이 아닙니다.' },
  },
  labRegionCells: {
    plain: { en: 'The cells of whichever region you have chosen, on their own, with nothing else drawn — the whole-brain plot above is where you find a region, and this is where you pick a cell inside it. Each dot is one cell, big enough to aim at; hover to name it, click to trace it. Lines between two dots are fibres running inside the region; the short stubs are fibres leaving it, pointing the way they go, with the far end off this panel because it is not in this region. The bar at the bottom is 10 mm, so you can see how big a patch of cortex this actually is — a small region is drawn as large as a big one and only that bar tells them apart.',
             ko: '선택한 영역의 세포만 따로 떼어, 다른 것은 아무것도 그리지 않고 보여줍니다. 위의 전체 뇌 그래프는 영역을 찾는 곳이고, 이 패널은 그 안에서 세포를 고르는 곳입니다. 점 하나가 세포 하나이며 클릭할 수 있을 만큼 큽니다. 마우스를 올리면 이름이 나오고, 클릭하면 추적합니다. 두 점을 잇는 선은 영역 안을 지나는 섬유이고, 짧은 선은 영역을 떠나는 섬유가 향하는 방향입니다. 반대쪽 끝은 이 영역이 아니므로 이 패널에 없습니다. 아래 막대는 10 mm로, 이 피질 조각이 실제로 얼마나 큰지 알 수 있습니다. 작은 영역도 큰 영역과 같은 크기로 그려지므로 그 막대만이 둘을 구분해 줍니다.',
           },
    tech: { en: 'The subset of network nodes carrying the selected Desikan-Killiany label, projected onto the parcel’s own principal plane — the two leading eigenvectors of the covariance of its node positions, found by power iteration with one deflation. A cortical parcel is a sheet, so its principal plane is very nearly the sheet itself and this is the patch face-on rather than a layout invented to fill a box. Positions are not jittered: coincident cells are drawn coincident, because a nudged position would be a lie about a coordinate the readout prints in millimetres. Edges with both ends in the parcel are drawn whole; edges with one end outside are drawn as fixed-length stubs along the true direction to the far node, and counted separately in the readout. The scale bar is 10 mm through FRAME.scale at the panel’s own fitted scale.',
            ko: '선택된 Desikan-Killiany 라벨을 가진 신경망 노드의 부분집합을, 그 영역 자체의 주평면에 투영한 것입니다. 주평면은 노드 좌표 공분산의 상위 고유벡터 두 개이며, 거듭제곱 반복법과 한 번의 디플레이션으로 구합니다. 피질 영역은 시트이므로 주평면은 사실상 그 시트 자체이고, 따라서 이것은 상자를 채우려고 만든 배치가 아니라 조각을 정면에서 본 모습입니다. 좌표에 흔들림을 주지 않습니다. 겹치는 세포는 겹친 채로 그립니다. 위치를 밀어내면 밀리미터로 출력하는 좌표에 대한 거짓이 되기 때문입니다. 양 끝이 영역 안에 있는 간선은 온전히 그리고, 한쪽 끝이 밖에 있는 간선은 반대쪽 노드로 향하는 실제 방향으로 고정 길이의 짧은 선으로 그리며 판독부에 따로 셉니다. 축척 막대는 FRAME.scale을 통한 10 mm입니다.' },
  },
  labSectionsBig: {
    plain: { en: 'The five cuts, at a size you can actually read, with what every part of the picture means listed beneath them. Pick which way to cut with the three buttons: sagittal splits left from right, coronal splits front from back, axial splits top from bottom. Each picture is one flat slice through the model at a stated depth, and the words under it name the structures that slice really passes through. Point at any shape in a picture and it tells you what that shape is; click it and that structure is chosen everywhere in the application. Clicking a picture anywhere else still moves the big plane in the main view to that depth. And if you have a structure selected — the hippocampus, say — the cuts that actually pass through it are outlined, it is ringed inside each of them, and the line under the strip says which cuts those are and how far the structure runs along the direction of the cut. If none of the five happens to land inside it, that line says so too, and tells you what to do about it. The rows underneath answer the question this panel exists for: what a bright line is, why some places are brighter, what the black is, what the colours mean, and what a section is for in the first place.',
             ko: '다섯 개의 절단면을 실제로 읽을 수 있는 크기로 보여주고, 그림의 각 부분이 무엇을 뜻하는지 아래에 정리했습니다. 세 개의 버튼으로 자르는 방향을 고릅니다. 시상면은 좌우를, 관상면은 앞뒤를, 수평면은 위아래를 나눕니다. 각 그림은 지정된 깊이에서 모델을 평면으로 자른 한 장이며, 아래 글자는 그 절단이 실제로 지나는 구조의 이름입니다. 그림 속 아무 모양이나 가리키면 그것이 무엇인지 알려주고, 클릭하면 그 구조가 앱 전체에서 선택됩니다. 그림의 다른 곳을 클릭하면 메인 화면의 큰 평면이 그 깊이로 이동합니다. 그리고 구조를 선택해 두면 — 예를 들어 해마 — 그 구조를 실제로 지나는 단면에 테두리가 생기고 그림 안에서 원으로 표시되며, 띠 아래의 문장이 어느 단면인지와 절단 방향으로 얼마나 뻗어 있는지를 알려줍니다. 다섯 단면 중 어느 것도 그 안에 들어가지 않으면 그것도 알려주고 어떻게 하면 되는지 말해 줍니다. 아래 항목들이 이 패널의 존재 이유인 질문에 답합니다. 밝은 선은 무엇인지, 왜 어떤 곳은 더 밝은지, 검은 부분은 무엇인지, 색은 무엇을 뜻하는지, 그리고 단면이 애초에 무엇에 쓰이는지입니다.' },
    tech: { en: 'The same SectionStrip renders the stage’s own strip uses, at four times the area — orthographic renders down the plane’s own normal, lighting only fragments whose signed distance to the plane falls inside a narrow band, so each thumbnail is a true section of the model’s surfaces. The band is composited additively with depth off, which is why brightness is the number of wall crossings near the plane rather than a density or an intensity. Structure colour comes from each part’s own registry entry through a per-part material clone. Positions are fsaverage millimetres from the cortex centroid via FRAME.scale; contents are computed by straddle — a structure appears in the list when its own vertices span the plane — so the caption is a statement about this geometry and not an atlas lookup. Pointing at a picture goes through SectionStrip.pickAt, which projects every part’s vertices once per axis into the frame draw() renders in, keeps the ones inside the band that cut actually lights, and takes the nearest to the pointer — so it is the real crossing that is picked, not a bounding box and not a colour read back out of the canvas, and a part this cut misses cannot be picked in it however close the pointer is to where it would be. A named deep structure wins a close tie with the cortex around it. A selected structure is located by SectionStrip.locate, which walks that part’s own vertices for its extent along the cut axis and its centroid in the thumbnail’s normalised frame; the ring is placed from the latter and is a DOM element over the canvas rather than a mark painted into it, because the renders are cached and re-blitted only when the plane changes. The camera basis it projects against is rebuilt exactly as draw() builds it — three’s lookAt puts view +Z along eye − target, +X along up × Z, +Y along Z × X — and the two must stay together, because a ring computed against a different basis would sit confidently on the wrong lobe. There is no imaging data anywhere in this application: no T1, no segmentation volume, no voxel, and nothing measured on a person.',
            ko: '무대 옆의 띠와 동일한 SectionStrip 렌더를 네 배 면적으로 보여줍니다. 평면 법선 방향의 정사영 렌더링으로, 평면까지의 부호 있는 거리가 좁은 범위 안에 드는 프래그먼트만 밝히므로 각 썸네일은 모델 표면의 실제 단면입니다. 띠는 깊이 쓰기를 끄고 가산 합성되므로 밝기는 밀도나 강도가 아니라 평면 근처에서 벽을 가로지른 횟수입니다. 구조 색은 파트별 재질 복제본을 통해 각 파트의 레지스트리 항목에서 옵니다. 위치는 FRAME.scale로 환산한 피질 중심 기준 fsaverage 밀리미터이며, 내용은 걸침 판정으로 계산합니다. 그림을 가리키는 동작은 SectionStrip.pickAt을 거칩니다. 축마다 한 번씩 모든 파트의 정점을 draw()가 렌더링하는 좌표계로 투영하고, 그 단면이 실제로 밝히는 띠 안의 점만 남긴 뒤 포인터에 가장 가까운 것을 고릅니다. 따라서 경계 상자나 캔버스에서 읽어낸 색이 아니라 실제 교차가 선택되며, 그 단면이 지나지 않는 파트는 아무리 가까이 가리켜도 선택되지 않습니다. 가까운 경합에서는 이름 있는 심부 구조가 주변 피질을 이깁니다. 선택된 구조는 SectionStrip.locate가 찾습니다. 해당 파트의 정점을 훑어 절단축 방향의 범위와 썸네일 정규 좌표계에서의 중심을 구하고, 원은 후자로 배치합니다. 원은 캔버스에 그린 표시가 아니라 캔버스 위의 DOM 요소입니다. 렌더는 캐시되어 평면이 바뀔 때만 다시 블릿되기 때문입니다. 투영에 쓰는 카메라 기저는 draw()가 만드는 것과 똑같이 재구성합니다. three의 lookAt은 뷰 +Z를 eye − target, +X를 up × Z, +Y를 Z × X로 둡니다. 둘은 반드시 함께 유지되어야 하며, 다른 기저로 계산한 원은 엉뚱한 엽 위에 그럴듯하게 앉게 됩니다. 이 앱에는 영상 데이터가 전혀 없습니다. T1도, 분할 볼륨도, 복셀도 없으며, 사람에게서 측정한 것은 아무것도 없습니다.' },
  },
  labDetail: {
    plain: { en: 'Every structure this exercise works, drawn one at a time, in the order the columns above rank them — the muscles it asks for hardest first, then the joints it travels through, then the nerves and cord levels, then the brain regions its claims are about. It plays through them by itself: you do not have to click each one. The names are along the top in that order, numbered; click any of them to jump there, and the transport on the left steps or stops. Touching either picture stops it too. On the left the thing by itself with everything else taken away; on the right its own system — a bone against the skeleton, a nerve against the nervous system, a brain region in the whole brain — in the pose being held, with a ring on where it sits. Both turn: drag to spin them round, scroll to move in and out, because half of what a muscle is is which way its fibres run and no single fixed angle shows that. Both are the body that is already loaded, rendered again from a different place — not a second model — so what you see here is the same muscle, in the same pose, at the same instant of the same movement. Click a muscle, a nerve, a cord level or a joint above and this follows it. A cord level and a joint are not shapes in this model: a cord level shows you the vertebra at that level, and a joint shows you the bones it moves between and nothing else, marked at the point it turns about — for a region of the spine, every level of that region, because the movement is shared across all of them. The caption says which of those it is doing, every time, because a picture of a vertebra with a nerve root’s name under it would be telling you something untrue.',
             ko: '이 운동이 쓰는 모든 구조를 위 열이 매긴 순서대로 하나씩 그립니다. 가장 많이 쓰는 근육부터, 그다음 움직이는 관절, 신경과 척수 분절, 마지막으로 그 주장이 다루는 뇌 영역입니다. 하나씩 클릭할 필요 없이 저절로 넘어갑니다. 이름이 위쪽에 번호와 함께 순서대로 있고, 아무거나 클릭하면 그 구조로 이동하며 왼쪽 버튼으로 넘기거나 멈출 수 있습니다. 그림을 만져도 멈춥니다. 왼쪽은 나머지를 모두 지우고 그것만, 오른쪽은 그것이 속한 계통 — 뼈는 골격, 신경은 신경계, 뇌 영역은 뇌 전체 — 을 지금 자세 그대로 보여주며 그것이 있는 자리를 원으로 표시합니다. 둘 다 이미 불러온 몸을 다른 위치에서 다시 렌더링한 것이며 두 번째 모델이 아닙니다. 따라서 여기 보이는 것은 같은 근육을, 같은 자세로, 같은 동작의 같은 순간에 본 것입니다. 위에서 근육, 신경, 척수 분절, 관절을 클릭하면 이 패널이 따라옵니다. 척수 분절과 관절은 이 모델의 형상이 아닙니다. 척수 분절은 그 높이의 척추뼈를 보여주고, 관절은 그 관절이 잇는 뼈만을 회전 중심 표시와 함께 보여줍니다. 척추의 부위별 좌표는 그 부위의 모든 분절을 함께 움직이므로 전부 표시됩니다. 어느 쪽을 보여주는지 설명에 매번 적습니다. 신경근의 이름을 붙인 척추뼈 그림은 사실이 아닌 것을 말하는 셈이기 때문입니다.' },
    tech: { en: 'Two calls to renderStructureInto, which renders the live scene through a cloned camera into an offscreen target and blits the readback — the same machinery renderStageInto uses, so the geometry, the skinning, the palette and the clip time are the scene’s own. The close view hides every drawable that is not one of the structure’s meshes (leaves only: hiding a group would take its wanted children with it) and frames it by the same rule flyTo uses, minus clearestDir, which exists to see past occluders that are no longer there. The wide view shows only the structure’s own layer — layerVantage fits the brain on its own posed centroids, everything else frames the rig’s joint cloud through poseVantage with bodyFlesh() as the pad, or BONY_PAD where no flesh is drawn — and projects the structure’s posed centroid through the same camera to place the ring — a DOM element over the canvas, never painted into it, because the renders are cached. frameFor takes the panel’s aspect and skips the console inset: overriding the real camera to fit a panel would reframe the live view, and paying for a console that does not cover an offscreen buffer would push the subject off its own edge. A joint has no mesh, so jointSegments gives it the segment it drives and the parent it swings against — or, for a regional spine coordinate, every level of that region — and only those bones are drawn, framed on their own posed bounding boxes by boneVantage. The ring is placed on the joint node’s world position: the joint node, not the body node, which is the child’s own offset frame and sits elsewhere. Both renders end with the pass three omits for a render target — ACES and the sRGB encode, from finalPass’s own shader — without which the readback is raw linear radiance shown as sRGB and every midtone loses more than half its value. The brain wears its opaque specimen material for the length of a panel render: an additive emission integral seen from outside at panel size is a cloud with the far hemisphere showing through the near one. A cord level resolves to its vertebra by name through the registry, never by id. Both renders are paced against their own measured cost, exactly as the body panel is.',
            ko: 'renderStructureInto를 두 번 호출합니다. 복제한 카메라로 살아 있는 장면을 오프스크린 타깃에 렌더링하고 읽어온 픽셀을 옮겨 그립니다. renderStageInto와 같은 방식이므로 형상, 스키닝, 팔레트, 클립 시각이 모두 장면 자체의 것입니다. 근접 뷰는 해당 구조의 메시가 아닌 모든 그리기 대상을 숨기고(리프만 숨깁니다. 그룹을 숨기면 원하는 자식까지 사라집니다) flyTo와 같은 규칙으로 화면을 잡되, 가림을 피하려고 있는 clearestDir은 쓰지 않습니다. 이제 가릴 것이 없기 때문입니다. 전신 뷰는 poseVantage와 bodyFlesh() 여백으로 리그의 관절 구름을 잡고, 같은 카메라로 구조의 자세 반영 중심을 투영해 원을 놓습니다. 원은 캔버스 위의 DOM 요소이며 캔버스에 그리지 않습니다. 렌더가 캐시되기 때문입니다. frameFor는 패널의 종횡비를 받고 콘솔 여백을 건너뜁니다. 실제 카메라를 패널에 맞추면 라이브 화면이 다시 잡히고, 오프스크린 버퍼를 가리지도 않는 콘솔 폭을 무는 것은 피사체를 화면 밖으로 밀어냅니다. 관절은 메시가 없으므로 jointSegments가 그 관절이 구동하는 세그먼트와 그것이 움직이는 기준이 되는 부모를 — 척추 부위 좌표라면 그 부위의 모든 분절을 — 골라 그 뼈만 그리고, boneVantage가 그 돼들의 자세 반영 경계 상자로 화면을 잡습니다. 원은 joint 노드의 월드 좌표에 놓습니다. body 노드가 아닙니다. 그것은 자식의 오프셋 프레임이라 다른 곳에 있습니다. 척추 부위 좌표는 그 부위 전체를 구동하므로 가운데 레벨로 해석합니다. 척수 분절은 레지스트리에서 이름으로 척추뼈를 찾습니다. 아이디로 찾지 않습니다. 두 렌더 모두 몸 패널과 똑같이 자신이 실제로 든 비용에 맞춰 속도를 조절합니다.' },
  },
  labAnalysis: {
    plain: { en: 'Everything this application can honestly say about what the exercise you have chosen works, in four columns. MUSCLES: which ones the exercise asks for and how hard, with a mark on each saying whether a study actually measured it in this movement or it was worked out from the anatomy. JOINTS: how far each one travels through the movement, in degrees, measured off the animation itself. NERVES AND CORD LEVELS: which nerves supply those muscles and which levels of the spinal cord they come from, quoted from Gray\u2019s Anatomy — this one carries no numbers at all, because nothing here measures a nerve, and a number would be invented. BRAIN REGIONS: which parts of the brain this exercise\u2019s own claims are about, how many of its claims name each, and the strength of the best evidence behind them. The claims themselves are written out underneath, with their papers, so you can check any of it. Clicking a muscle or a region selects it everywhere; the brain regions are also marked in the main view the moment you pick the exercise.',
             ko: '선택한 운동이 무엇을 사용하는지에 대해 이 앱이 정직하게 말할 수 있는 모든 것을 네 개의 열로 보여줍니다. 근육: 어떤 근육을 얼마나 사용하는지, 그리고 각 항목에 그 근육이 이 동작에서 실제로 측정되었는지 해부학적으로 추론되었는지 표시가 붙습니다. 관절: 각 관절이 동작 중 몇 도를 움직이는지, 애니메이션에서 직접 측정한 값입니다. 신경과 척수 분절: 그 근육들을 지배하는 신경과 척수 분절이며 그레이 해부학에서 인용했습니다. 이 열에는 수치가 전혀 없습니다. 이 앱은 신경을 측정하지 않으며, 수치를 붙이면 그것은 지어낸 것이기 때문입니다. 뇌 영역: 이 운동의 주장이 다루는 뇌 부위, 각 부위를 지목하는 주장의 수, 그리고 그중 가장 강한 근거의 등급입니다. 주장 본문과 출처 논문이 아래에 그대로 적혀 있어 직접 확인할 수 있습니다. 근육이나 영역을 클릭하면 어디서나 선택되며, 뇌 영역은 운동을 고르는 순간 메인 화면에도 표시됩니다.' },
    tech: { en: 'Assembled by content/analysis.js from four sources with four different warrants, and the panel prints the warrant over each column because a ranked bar with no provenance beside it is the object this application exists not to be. Muscle share is the mean of the exercise\u2019s authored per-phase activation over 48 samples of the clip — the same scalar the shader lights that muscle with, so the ranking and the picture cannot disagree — carrying the record\u2019s own emg/inferred marker. Joint travel is peak-to-peak of each coordinate over the same sampling, excluding pelvis translations and spine wave positions by the same isAngle test motion.js uses on the way in. Nerves and roots are the union of MUSCLE_INFO[...].innervation over the worked muscles (Standring, Gray\u2019s Anatomy 42nd ed.), rendered without any magnitude: there is no electrophysiology in this repository. Brain regions are the structures named by the exercise\u2019s own EXERCISE_BRAIN keys; the fraction is claims-naming-that-region over claims-for-this-exercise, and the letter is the best tier among them. In the scene those regions are marked at one uniform level rather than in proportion to that fraction — a gradient across regions would read as an activation, and nothing in this application records a brain.',
            ko: 'content/analysis.js가 서로 다른 네 가지 근거를 가진 네 출처에서 조립합니다. 각 열 위에 근거를 명시하는 이유는, 출처 없는 막대 순위표야말로 이 앱이 되지 않으려는 대상이기 때문입니다. 근육 비율은 클립을 48회 표본화해 얻은 운동별 기록 활성값의 평균이며, 셰이더가 그 근육을 밝히는 것과 동일한 스칼라이므로 순위와 그림이 어긋날 수 없습니다. 기록의 emg/inferred 표시가 함께 따라옵니다. 관절 이동량은 동일한 표본화에서 각 좌표의 최대–최소 차이이며, motion.js가 입력 시 쓰는 isAngle 검사로 골반 이동과 척추 파동 위치를 제외합니다. 신경과 분절은 사용된 근육들의 MUSCLE_INFO[...].innervation의 합집합입니다(Standring, Gray\u2019s Anatomy 42판). 크기 값은 전혀 붙이지 않습니다. 이 저장소에는 전기생리학이 없기 때문입니다. 뇌 영역은 운동 자체의 EXERCISE_BRAIN 키가 지목하는 구조이며, 비율은 그 영역을 지목한 주장 수를 이 운동의 전체 주장 수로 나눈 값, 문자는 그중 최고 등급입니다. 장면에서는 이 비율에 비례하지 않고 모두 동일한 세기로 표시합니다. 영역 간 밝기 차이는 활성도로 읽히며, 이 앱은 뇌를 기록하지 않습니다.' },
  },
  labJoints: {
    plain: { en: 'Read it like this: the bottom of the chart is the start of the exercise on the left and the end on the right, and every line is one joint — named underneath in plain words, such as "right hip, thigh forward". Where a line is high, that joint is bent a long way; where it is low, it is near straight; where it is flat, the joint is being held still through that part of the movement. The number up the side is degrees, the same degrees a physiotherapist would measure with a goniometer. A line going up means that joint is bending further; a flat line means it is being held still. The dashed line is zero — the joint’s neutral, straight position. The coloured uprights are where the breath changes. The bright vertical line is where the body on screen has got to.',
             ko: '관절마다 한 개의 선으로, 운동의 매 순간 그 관절이 몇 도로 굽어 있는지 보여줍니다. 왼쪽이 시작, 오른쪽이 끝입니다. 선이 올라가면 그 관절이 더 굽는다는 뜻이고, 평평하면 고정하고 있다는 뜻입니다. 점선은 0도, 즉 관절의 중립 위치입니다. 색이 있는 세로선은 호흡이 바뀌는 지점이고, 밝은 세로선은 화면 속 신체가 도달한 지점입니다.' },
    tech: { en: 'The clip’s own coordinate values, interpolated between keyframes and converted from radians to degrees; only coordinates that move more than 1.5° are drawn, and pelvis translations and spine wave positions are excluded because they are not angles. These are the values driving the rig on screen — hand-keyed against published movement descriptions and the joint definitions of the Rajagopal 2016 model, not motion capture and not inverse kinematics from measured data.',
            ko: '클립 자체의 좌표값을 키프레임 사이에서 보간하고 라디안에서 도로 변환한 값입니다. 1.5도 이상 움직이는 좌표만 그리며, 골반 이동과 척추 웨이브 위치는 각도가 아니므로 제외합니다. 화면의 리그를 구동하는 실제 값이며, 공개된 동작 기술과 Rajagopal 2016 모델의 관절 정의를 바탕으로 수동 입력한 것입니다. 모션캡처도, 측정 데이터로부터의 역운동학도 아닙니다.' },
  },
  labMuscles: {
    plain: { en: 'One line per muscle, showing how much the exercise asks of it at each moment. Higher means it is working harder in that part of the movement. The six busiest are drawn. This describes the exercise, not a person doing it — nobody was measured.',
             ko: '근육마다 한 개의 선으로, 매 순간 운동이 그 근육에 얼마나 요구하는지 보여줍니다. 높을수록 그 구간에서 더 많이 일한다는 뜻입니다. 가장 활발한 여섯 개를 그립니다. 이것은 운동을 기술한 것이지 그것을 하는 사람을 기술한 것이 아닙니다. 측정된 사람은 없습니다.' },
    tech: { en: 'Per-muscle role at each keyframe of the clip, interpolated between them — the same scalar the shader uses to light that muscle in the picture. The vertical axis is the role scale (prime mover, synergist, stabiliser) taken from the exercise record. It is not EMG amplitude, not a percentage of maximum voluntary contraction, and not normalised to anything measured on a person.',
            ko: '클립의 각 키프레임에서의 근육별 역할 값을 보간한 것으로, 셰이더가 화면에서 그 근육을 밝히는 데 쓰는 값과 동일합니다. 세로축은 운동 기록에서 가져온 역할 척도(주동근·협력근·안정근)입니다. 근전도 진폭도, 최대 수의 수축 대비 백분율도 아니며, 사람에게서 측정한 어떤 값으로도 정규화되지 않았습니다.' },
  },
  labCellKey: {
    plain: { en: 'Before you pick anything this is the key: one speck and one thread, drawn big. The speck is a cell body with a few short branches; the thread is a fibre to another cell; the bright band is what travels along it. Click a cell in either plot above and this panel becomes a full trace of that one cell. It then tells you six things. WHICH CELL it is — its number and the region it sits in, with its three millimetre coordinates. WHAT THAT REGION DOES, in the same words the rest of the app uses, and how strong the evidence is for the claims attached to it. WHERE EACH FIBRE GOES — the cell at the other end, its number, its region, and how far away it is in millimetres. HOW FAST the band moves: the real number this application animates with, and beside it the speed a living axon actually conducts at, so you can see the gap. WHY THE FIBRE IS THERE: solid means the build joined this cell to a near neighbour, dashed means it is one of the small minority of long-range fibres, and that is a fact about how this model was made rather than about a brain. Hover a row to light that fibre in the picture; click one to follow it and trace that cell instead.',
             ko: '아무것도 고르지 않았을 때는 범례입니다. 점 하나와 실 하나를 크게 그린 것으로, 점은 짧은 가지가 달린 세포체, 실은 다른 세포로 가는 섬유, 밝은 띠는 그 위를 이동하는 것입니다. 위의 두 그래프 중 어디서든 세포를 클릭하면 이 패널이 그 세포 하나의 완전한 추적으로 바뀌어 여섯 가지를 알려줍니다. 어떤 세포인지 — 번호와 속한 영역, 세 개의 밀리미터 좌표. 그 영역이 무엇을 하는지 — 앱의 다른 곳과 같은 표현으로, 그리고 거기에 연결된 주장의 근거 등급. 각 섬유가 어디로 가는지 — 반대편 세포의 번호, 영역, 밀리미터 거리. 띠가 얼마나 빠른지 — 이 앱이 실제로 애니메이션에 쓰는 숫자와, 그 옆에 살아 있는 축삭이 실제로 전도하는 속도를 나란히 두어 차이를 볼 수 있게 했습니다. 그 섬유가 왜 있는지 — 실선은 가까운 이웃과 이어진 것, 점선은 소수의 장거리 섬유이며, 이는 뇌에 대한 사실이 아니라 이 모델을 만든 방식에 대한 사실입니다. 행에 마우스를 올리면 그림에서 해당 섬유가 켜지고, 클릭하면 그 세포로 따라갑니다.' },
    tech: { en: 'Two states. Unpicked, it is the key: each fibre vertex carries how far along its own edge it sits, and the fragment lights where that value is near a head position advanced from elapsed time — the band is a pure function of position and clock, with no per-frame CPU work and no state. Rate and starting phase are drawn per fibre at build time, so the field never pulses in unison, and a burst gate makes the proportion of fibres conducting at once rise with activity rather than the individual line brightening. Picked, it is a trace of one node: the fibres are that node’s own entries in the edge index pairs, taken in both orderings because the buffer is undirected; targets are the nodes at the other end; lengths are Euclidean distances converted to fsaverage millimetres through FRAME.scale; the traversal time is 1/(rate·BAND_RATE) with BAND_RATE the same constant interpolated into the axon shader, so the printed seconds are the seconds the picture is running at. The stated screen speed follows from that and the fibre’s own length. It is an animation rate and is labelled as one: real cortical axons conduct at roughly 0.5 m/s unmyelinated to 120 m/s myelinated (Kandel et al., Principles of Neural Science, 5th ed.), some six orders of magnitude faster than what is drawn. Dashed edges are the long-range pass of the build, solid the nearest-neighbour pass. None of this is electrophysiology: there is no EEG, no spike train, no conduction velocity and no measured latency anywhere in this application, and direction is from the lower vertex index to the higher and carries no claim about afferent or efferent flow.',
            ko: '두 가지 상태가 있습니다. 선택 전에는 범례입니다. 각 섬유 정점은 자신이 간선의 어디쯤에 있는지를 지니고, 그 값이 경과 시간으로 전진하는 머리 위치에 가까울 때 프래그먼트가 밝아집니다. 띠는 위치와 시계만의 순수 함수이며 프레임마다의 CPU 작업도 상태도 없습니다. 속도와 시작 위상은 생성 시점에 섬유마다 정해지므로 전체가 동시에 맥동하지 않고, 버스트 게이트 덕분에 활동이 높아질수록 개별 선이 밝아지는 대신 동시에 전도 중인 섬유의 비율이 늘어납니다. 선택 후에는 노드 하나의 추적입니다. 섬유는 간선 색인 쌍에서 그 노드가 등장하는 항목들이며 버퍼가 무방향이므로 양쪽 순서를 모두 취합니다. 길이는 FRAME.scale로 환산한 fsaverage 밀리미터이고, 통과 시간은 1/(rate·BAND_RATE)입니다. BAND_RATE는 축삭 셰이더에 그대로 삽입되는 동일한 상수이므로, 출력되는 초는 그림이 실제로 움직이는 초입니다. 화면 속도는 거기서 섬유 길이와 함께 계산됩니다. 이것은 애니메이션 속도이며 그렇게 표시합니다. 실제 피질 축삭은 무수초 약 0.5 m/s에서 유수초 120 m/s까지 전도하며(Kandel 외, Principles of Neural Science 5판), 그려진 것보다 약 여섯 자릿수 빠릅니다. 점선은 장거리 생성 단계, 실선은 최근접 이웃 단계입니다. 이 중 어느 것도 전기생리학이 아니며, 방향은 낮은 정점 색인에서 높은 쪽으로이고 구심성·원심성에 대한 주장을 담지 않습니다.' },
  },
  labRoster: {
    plain: { en: 'The four thousand specks, grouped. Every region the network draws cells in, how many it has, and how that compares with the others — the bar is the count. Bigger regions get more cells because more of the brain’s surface belongs to them, not because they are busier. Click a row to select that region everywhere: in the brain, in the connectome, and in the panel.',
             ko: '4천 개의 점을 묶어서 본 것입니다. 신경망이 세포를 그리는 모든 영역과 각 영역의 세포 수, 그리고 서로 간의 비교입니다. 막대의 길이가 세포 수입니다. 큰 영역에 세포가 많은 것은 더 활발해서가 아니라 뇌 표면에서 차지하는 면적이 넓기 때문입니다. 행을 클릭하면 뇌·연결 지도·패널 어디에서나 그 영역이 선택됩니다.' },
    tech: { en: 'Cell counts per Desikan-Killiany parcel, taken from the node cloud as built. The cloud is a fixed-stride sample of the cortex mesh’s vertices, so a parcel’s count is proportional to its share of the vertices, which for a surface of roughly even tessellation is proportional to its area. It is a measure of how much cortex a parcel occupies in this model and of nothing else — not of neuron density, which varies across cortex and is not represented here, and not of activity.',
            ko: 'Desikan-Killiany 분할 영역별 세포 수로, 생성된 노드 구름에서 직접 센 값입니다. 구름은 피질 메시 정점을 일정 간격으로 표본화한 것이므로, 한 영역의 세포 수는 그 영역이 차지하는 정점 비율에, 다시 말해 대체로 균일한 테셀레이션에서는 면적에 비례합니다. 이 모델에서 한 영역이 차지하는 피질의 넓이를 나타낼 뿐이며, 피질마다 다른 뉴런 밀도(여기에 반영되어 있지 않습니다)나 활동량을 나타내지 않습니다.' },
  },
  labEvidence: {
    plain: { en: 'Every claim this application makes about exercise and the brain, written out in full, sorted by how well it is actually established. Under each grade you get the claim itself, how big the effect was, who was tested, whether it was people or animals, whether it was one session or months of training, what the study does NOT show, and the paper it came from — so you can look it up. The grades run A (several human trials pooled and they agree) down to E (somebody reasoned it out and nobody has tested it). Read this before you trust anything else on this screen.',
             ko: '이 앱이 운동과 뇌에 대해 말하는 모든 주장을 전문 그대로, 근거가 얼마나 확립되어 있는지 순서로 정리했습니다. 각 등급 아래에 주장 자체, 효과의 크기, 시험 대상, 사람인지 동물인지, 단회 운동인지 수 개월 훈련인지, 그 연구로는 말할 수 없는 것, 그리고 출처 논문이 함께 있어 직접 찾아볼 수 있습니다. 등급은 A(사람 대상 시험 여러 건이 일치)부터 E(추론일 뿐 검증되지 않음)까지입니다. 이 화면의 다른 무엇을 믿기 전에 먼저 읽으십시오.' },
    tech: { en: 'Every entry in EXERCISE_BRAIN, grouped by evidence tier A–E, each rendered with its effect size, population, species, timescale, caveat and citation. The build fails if any of those is missing or if an animal-only finding claims a tier above D. It was a bar chart of five counts and that was the wrong object: a count tells you how many claims sit at a grade and nothing about what any of them says, so the number read as decoration. The strip along the top is the same distribution, kept because the shape of it is worth one glance. The panel is deliberately unflattering — a screen of luminous graphs invites a reader to take all of it as established, and this states in the same visual language how much of it is inference.',
            ko: 'EXERCISE_BRAIN의 모든 항목을 A–E 근거 등급별로 묶고, 각각 효과 크기·대상 집단·종·시간 척도·한계·인용 출처와 함께 표시합니다. 그중 하나라도 빠지거나 동물 실험만으로 D등급을 넘는 주장을 하면 빌드가 실패합니다. 이전에는 다섯 개 막대의 개수 그래프였으나 그것은 잘못된 대상이었습니다. 개수는 어느 등급에 몇 건이 있는지만 말할 뿐 각 주장이 무엇을 말하는지는 전혀 말하지 않아 숫자가 장식처럼 읽혔습니다. 위쪽 띠는 같은 분포이며, 그 형태만은 한 번 볼 가치가 있어 남겼습니다. 이 패널은 의도적으로 돋보이지 않습니다. 빛나는 그래프로 가득한 화면은 모든 것이 확립된 사실처럼 믿게 만들고, 이 패널은 그중 얼마나 많은 것이 추론인지를 같은 시각 언어로 말합니다.' },
  },

  /* --------------------------------------------------------------- the rest */
  xray: {
    plain: { en: 'Fades the outer layers so you can see through to what is underneath.',
             ko: '바깥 레이어를 흐리게 하여 그 아래를 들여다볼 수 있게 합니다.' },
    tech: { en: 'Drives per-layer opacity by depth order, and switches the surface term to a fresnel shell so a silhouette stays readable while the interior shows through.',
            ko: '깊이 순서에 따라 레이어별 불투명도를 조절하고, 표면 항을 프레넬 셸로 전환하여 실루엣은 유지하면서 내부가 비쳐 보이게 합니다.' },
  },
  atlasHelp: {
    plain: { en: 'Paints each structure in its own flat colour instead of its tissue colour, so you can tell neighbouring parts apart.',
             ko: '각 구조를 조직 색 대신 고유한 단색으로 칠해, 인접한 부위를 구분할 수 있게 합니다.' },
    tech: { en: 'Mixes the per-region palette into base colour. The colours are identifiers, not measurements — they encode which structure a fragment belongs to and nothing else.',
            ko: '영역별 팔레트를 기본 색상에 혼합합니다. 색은 식별자이지 측정값이 아니며, 프래그먼트가 어느 구조에 속하는지만 나타냅니다.' },
  },
  cutawayHelp: {
    plain: { en: 'Slices the whole body away along a flat plane you can drag, so you can look inside it.',
             ko: '끌 수 있는 평면을 따라 신체 전체를 잘라내어 내부를 볼 수 있게 합니다.' },
    tech: { en: 'A real clipping plane applied by the renderer, so the geometry in front of it is not drawn at all. Unlike the scan, this removes surface rather than lighting an intersection.',
            ko: '렌더러가 적용하는 실제 클리핑 평면으로, 평면 앞의 지오메트리는 아예 그려지지 않습니다. 스캔과 달리 교선을 밝히는 것이 아니라 표면을 제거합니다.' },
  },
  actChartHelp: {
    plain: { en: 'Each line is one muscle across the exercise, from start to finish. Higher means the movement asks more of it. The upright line is where the body on screen has got to.',
             ko: '각 선은 운동 처음부터 끝까지의 근육 하나를 나타냅니다. 높을수록 그 동작이 더 많이 요구한다는 뜻입니다. 세로선은 화면 속 신체가 도달한 지점입니다.' },
    tech: { en: 'Per-muscle role at each keyframe of the clip, interpolated between them — the same value the shader uses to light the muscle. The vertical axis is a role, not an EMG amplitude and not a percentage of maximum, and it describes the exercise rather than any person performing it.',
            ko: '클립의 각 키프레임에서의 근육별 역할 값을 보간한 것으로, 셰이더가 근육을 밝히는 데 쓰는 값과 같습니다. 세로축은 역할이며 근전도 진폭도, 최대치 대비 백분율도 아닙니다. 특정인이 아니라 운동 자체를 기술합니다.' },
  },
};

export const HELP_KEYS = Object.keys(HELP);
