/**
 * MUSCLE_ATLAS — the rest of the named muscles, in the same shape as MUSCLE_INFO.
 *
 * `muscles.js` carries the two dozen muscles the first exercises needed, each with a long
 * `feels` note and a `dysfunction` paragraph. Those stay. This file is the breadth that a
 * library of several hundred Pilates and yoga entries needs: every muscle any entry names
 * has to have something to read when it lights up, or the app hands the user a coloured
 * shape and nothing else.
 *
 * Same contract, enforced by test/content.test.mjs: the key is the base name the build
 * emits into src/generated/structures.json, Latin follows Terminologia Anatomica, `does` is
 * what you would say out loud and `sci` is the same fact in clinical terms, and innervation
 * carries root levels because the roots are what let a click travel into the cord.
 *
 * Attachments and innervation: Standring S (ed.), Gray's Anatomy 42nd ed.; Moore KL,
 * Clinically Oriented Anatomy 8th ed.
 */

export const MUSCLE_ATLAS = {

  /* ------------------------------------------------------------------ hip and thigh */

  'semimembranosus': {
    latin: 'Musculus semimembranosus',
    en: { name: 'Semimembranosus',
          does: 'The innermost hamstring, a broad flat tendon high up that gives it its name. It extends the hip and bends the knee, and because it sits on the inside it also turns the lower leg inward.',
          sci: 'Medial hamstring. Hip extensor and knee flexor with medial rotation of the flexed knee; its distal expansions reinforce the posteromedial knee capsule.' },
    ko: { name: '반막양근',
          does: '가장 안쪽 햄스트링으로, 위쪽의 넓고 납작한 힘줄에서 이름이 왔습니다. 고관절을 펴고 무릎을 굽히며, 안쪽에 있기 때문에 종아리를 안으로 돌리기도 합니다.',
          sci: '내측 햄스트링. 고관절 신전과 슬관절 굴곡을 담당하며 굴곡된 무릎을 내회전시킵니다. 원위 확장부가 후내측 슬관절낭을 보강합니다.' },
    origin: { en: 'Ischial tuberosity, superolateral facet', ko: '좌골결절 상외측면' },
    insertion: { en: 'Posteromedial aspect of the medial tibial condyle', ko: '내측 경골과 후내측면' },
    innervation: { nerves: { en: 'Tibial division of the sciatic nerve', ko: '좌골신경 경골분지' },
                   roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Hip extension, knee flexion, medial rotation of the flexed knee',
               ko: '고관절 신전, 슬관절 굴곡, 굴곡된 무릎의 내회전' },
    synergists: ['semitendinosus', 'biceps femoris', 'gluteus maximus'],
    antagonists: ['rectus femoris', 'psoas major'],
  },

  'gluteus minimus': {
    latin: 'Musculus gluteus minimus',
    en: { name: 'Gluteus minimus',
          does: 'The deepest and smallest of the three glutes, fan-shaped under gluteus medius. It helps hold the pelvis level when you stand on one leg, and its front fibres turn the thigh inward.',
          sci: 'Deepest gluteal. Hip abductor and, through its anterior fibres, medial rotator and flexor; a principal frontal-plane pelvic stabiliser in single-limb stance.' },
    ko: { name: '소둔근',
          does: '세 둔근 중 가장 깊고 작으며 중둔근 아래에 부채꼴로 있습니다. 한 발로 설 때 골반을 수평으로 잡는 데 기여하고, 앞쪽 섬유는 허벅지를 안으로 돌립니다.',
          sci: '최심층 둔근. 고관절 외전근이며 전방 섬유는 내회전과 굴곡에 작용합니다. 단하지 지지에서 관상면 골반 안정의 주요 근육입니다.' },
    origin: { en: 'External surface of the ilium between the anterior and inferior gluteal lines',
              ko: '전둔근선과 하둔근선 사이 장골 외면' },
    insertion: { en: 'Anterior border of the greater trochanter', ko: '대전자 전연' },
    innervation: { nerves: { en: 'Superior gluteal nerve', ko: '상둔신경' }, roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Hip abduction, medial rotation, pelvic stabilisation in stance',
               ko: '고관절 외전, 내회전, 입각기 골반 안정화' },
    synergists: ['gluteus medius', 'tensor fasciae latae'],
    antagonists: ['adductor longus', 'adductor magnus'],
  },

  'tensor fasciae latae': {
    latin: 'Musculus tensor fasciae latae',
    en: { name: 'Tensor fasciae latae',
          does: 'A short muscle at the front of the hip that pulls on the iliotibial band, the thick strap running down the outside of the thigh. It flexes and abducts the hip and helps steady the knee from the side.',
          sci: 'Tensions the iliotibial tract. Hip flexor, abductor and medial rotator; contributes to lateral knee stability through the tract’s attachment at Gerdy’s tubercle.' },
    ko: { name: '대퇴근막장근',
          does: '고관절 앞쪽의 짧은 근육으로, 허벅지 바깥을 따라 내려가는 두꺼운 띠인 장경인대를 당깁니다. 고관절을 굽히고 벌리며 무릎을 옆에서 잡아 줍니다.',
          sci: '장경인대를 긴장시킵니다. 고관절 굴곡·외전·내회전근이며, Gerdy 결절 부착을 통해 슬관절 외측 안정에 기여합니다.' },
    origin: { en: 'Anterior superior iliac spine and anterior iliac crest', ko: '전상장골극 및 장골능 전방' },
    insertion: { en: 'Iliotibial tract, to Gerdy’s tubercle on the lateral tibia', ko: '장경인대를 통해 경골 외측 Gerdy 결절' },
    innervation: { nerves: { en: 'Superior gluteal nerve', ko: '상둔신경' }, roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Hip flexion, abduction and medial rotation; tensions the iliotibial tract',
               ko: '고관절 굴곡·외전·내회전, 장경인대 긴장' },
    synergists: ['gluteus medius', 'gluteus minimus', 'rectus femoris'],
    antagonists: ['gluteus maximus', 'adductor magnus'],
  },

  'piriformis': {
    latin: 'Musculus piriformis',
    en: { name: 'Piriformis',
          does: 'A deep muscle running from the front of the sacrum out to the hip. It turns the thigh outward when the hip is straight — and inward once the hip is bent past about 60 degrees, which is why its job changes depending on the position you are in.',
          sci: 'Deep external rotator. Lateral rotator in hip extension; the line of action reverses toward internal rotation and abduction beyond roughly 60° of hip flexion. The sciatic nerve passes beneath it, and in a minority of people through it.' },
    ko: { name: '이상근',
          does: '천골 앞면에서 고관절로 이어지는 깊은 근육입니다. 고관절이 펴져 있을 때는 허벅지를 바깥으로 돌리지만, 약 60도 이상 굽히면 안으로 돌립니다. 자세에 따라 역할이 바뀌는 이유입니다.',
          sci: '심부 외회전근. 고관절 신전 시 외회전근이며, 약 60도 이상 굴곡에서는 작용선이 내회전·외전 쪽으로 역전됩니다. 좌골신경이 그 아래를 지나가며 소수에서는 근육을 관통합니다.' },
    origin: { en: 'Anterior surface of the sacrum, S2–S4', ko: '천골 전면 S2–S4' },
    insertion: { en: 'Superior border of the greater trochanter', ko: '대전자 상연' },
    innervation: { nerves: { en: 'Nerve to piriformis, from the sacral plexus', ko: '천골신경총에서 나오는 이상근신경' },
                   roots: ['S1', 'S2'] },
    actions: { en: 'Hip lateral rotation in extension, abduction in flexion, sacroiliac stabilisation',
               ko: '신전 시 고관절 외회전, 굴곡 시 외전, 천장관절 안정화' },
    synergists: ['obturator internus', 'quadratus femoris', 'gluteus maximus'],
    antagonists: ['gluteus minimus', 'tensor fasciae latae'],
  },

  'obturator internus': {
    latin: 'Musculus obturator internus',
    en: { name: 'Obturator internus',
          does: 'One of the deep six rotators. It leaves the pelvis through a notch and takes a sharp right-angle turn around the ischium, so its tendon works like a rope over a pulley.',
          sci: 'Deep external rotator. Arises inside the pelvis, turns through 90° at the lesser sciatic notch — an anatomical pulley — to insert on the medial greater trochanter. Shares a fascial relationship with the pelvic floor.' },
    ko: { name: '내폐쇄근',
          does: '심부 6개 회전근 중 하나입니다. 소좌골절흔을 통해 골반을 빠져나오며 좌골에서 직각으로 꺾여, 힘줄이 도르래를 넘는 밧줄처럼 작동합니다.',
          sci: '심부 외회전근. 골반 내에서 기시해 소좌골절흔에서 90도로 꺾이는 해부학적 도르래를 이루며 대전자 내측에 정지합니다. 골반저와 근막으로 연결됩니다.' },
    origin: { en: 'Inner surface of the obturator membrane and surrounding pelvic bone', ko: '폐쇄막 내면과 주변 골반골' },
    insertion: { en: 'Medial surface of the greater trochanter', ko: '대전자 내측면' },
    innervation: { nerves: { en: 'Nerve to obturator internus', ko: '내폐쇄근신경' }, roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Hip lateral rotation, abduction of the flexed hip, femoral head centring',
               ko: '고관절 외회전, 굴곡 시 외전, 대퇴골두 중심화' },
    synergists: ['piriformis', 'quadratus femoris', 'obturator externus'],
    antagonists: ['gluteus minimus'],
  },

  'obturator externus': {
    latin: 'Musculus obturator externus',
    en: { name: 'Obturator externus',
          does: 'Sits on the outer face of the obturator membrane, low in the front of the hip. It rotates the thigh outward and helps hold the head of the femur into its socket.',
          sci: 'Deep rotator on the external aspect of the obturator membrane. Lateral rotator and adductor; passes below the femoral neck, contributing to femoral head stabilisation.' },
    ko: { name: '외폐쇄근',
          does: '폐쇄막 바깥면, 고관절 앞쪽 아래에 있습니다. 허벅지를 바깥으로 돌리고 대퇴골두를 관절와에 붙들어 줍니다.',
          sci: '폐쇄막 외면의 심부 회전근. 외회전·내전근이며 대퇴경부 아래를 지나 대퇴골두 안정에 기여합니다.' },
    origin: { en: 'External surface of the obturator membrane and its bony margins', ko: '폐쇄막 외면과 골연' },
    insertion: { en: 'Trochanteric fossa of the femur', ko: '대퇴골 전자와' },
    innervation: { nerves: { en: 'Obturator nerve, posterior division', ko: '폐쇄신경 후지' }, roots: ['L3', 'L4'] },
    actions: { en: 'Hip lateral rotation and adduction', ko: '고관절 외회전 및 내전' },
    synergists: ['obturator internus', 'quadratus femoris'],
    antagonists: ['gluteus minimus'],
  },

  'quadratus femoris': {
    latin: 'Musculus quadratus femoris',
    en: { name: 'Quadratus femoris',
          does: 'A short square muscle between the sitting bone and the back of the hip. It is the strongest of the deep external rotators.',
          sci: 'Flat quadrilateral deep rotator running from ischial tuberosity to the quadrate tubercle. The most powerful of the deep external rotator group.' },
    ko: { name: '대퇴방형근',
          does: '좌골과 고관절 뒤 사이의 짧은 사각 근육입니다. 심부 외회전근 중 가장 강합니다.',
          sci: '좌골결절에서 방형결절로 이어지는 편평한 사각형 심부 회전근. 심부 외회전근 중 가장 강력합니다.' },
    origin: { en: 'Lateral border of the ischial tuberosity', ko: '좌골결절 외측연' },
    insertion: { en: 'Quadrate tubercle of the intertrochanteric crest', ko: '전자간릉의 방형결절' },
    innervation: { nerves: { en: 'Nerve to quadratus femoris', ko: '대퇴방형근신경' }, roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Hip lateral rotation and adduction', ko: '고관절 외회전 및 내전' },
    synergists: ['piriformis', 'obturator internus'],
    antagonists: ['gluteus minimus'],
  },

  'adductor longus': {
    latin: 'Musculus adductor longus',
    en: { name: 'Adductor longus',
          does: 'The most visible groin muscle, a triangle from the pubic bone to the middle of the thigh bone. It draws the leg toward the midline and is the one most often strained in change-of-direction sport.',
          sci: 'Most anterior of the adductor group. Hip adduction with a flexion moment below about 50° of hip flexion; the commonest site of adductor-related groin pain.' },
    ko: { name: '장내전근',
          does: '가장 눈에 띄는 내전근으로, 치골에서 대퇴골 중앙까지 삼각형으로 이어집니다. 다리를 몸 중심선으로 당기며, 방향 전환이 많은 스포츠에서 가장 흔히 손상됩니다.',
          sci: '내전근군 중 가장 전방. 고관절 내전을 담당하며 약 50도 이하 굴곡에서는 굴곡 모멘트를 만듭니다. 내전근 관련 서혜부 통증의 가장 흔한 부위입니다.' },
    origin: { en: 'Body of the pubis below the pubic crest', ko: '치골능 아래 치골체' },
    insertion: { en: 'Middle third of the linea aspera', ko: '조선 중간 1/3' },
    innervation: { nerves: { en: 'Obturator nerve, anterior division', ko: '폐쇄신경 전지' }, roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Hip adduction, assists flexion and medial rotation', ko: '고관절 내전, 굴곡·내회전 보조' },
    synergists: ['adductor brevis', 'adductor magnus', 'gracilis', 'pectineus'],
    antagonists: ['gluteus medius', 'gluteus minimus'],
  },

  'adductor magnus': {
    latin: 'Musculus adductor magnus',
    en: { name: 'Adductor magnus',
          does: 'A huge fan filling the inside of the thigh, with two different jobs. The front part adducts; the back part behaves like a hamstring and extends the hip, which is why it works hard in a bridge as well as in a squeeze.',
          sci: 'Composite muscle: an adductor portion supplied by the obturator nerve and a hamstring portion supplied by the tibial nerve. The ischiocondylar part is a powerful hip extensor and among the largest muscles in the body by volume.' },
    ko: { name: '대내전근',
          does: '허벅지 안쪽을 채우는 거대한 부채꼴이며 두 가지 역할을 합니다. 앞부분은 내전하고 뒷부분은 햄스트링처럼 고관절을 폅니다. 브리지에서도 모으기에서도 함께 일하는 이유입니다.',
          sci: '복합근. 폐쇄신경이 지배하는 내전부와 경골신경이 지배하는 햄스트링부로 나뉩니다. 좌골과부는 강력한 고관절 신전근이며 체적상 인체에서 가장 큰 근육 중 하나입니다.' },
    origin: { en: 'Inferior pubic ramus, ischial ramus and ischial tuberosity', ko: '치골하지, 좌골지, 좌골결절' },
    insertion: { en: 'Linea aspera along its length and the adductor tubercle of the femur', ko: '조선 전장 및 대퇴골 내전근결절' },
    innervation: { nerves: { en: 'Obturator nerve (adductor part) and tibial division of the sciatic nerve (hamstring part)',
                             ko: '폐쇄신경(내전부), 좌골신경 경골분지(햄스트링부)' },
                   roots: ['L2', 'L3', 'L4', 'L5', 'S1'] },
    actions: { en: 'Hip adduction throughout; hip extension from the ischiocondylar part', ko: '고관절 내전 전반, 좌골과부의 고관절 신전' },
    synergists: ['adductor longus', 'gluteus maximus', 'semitendinosus'],
    antagonists: ['gluteus medius', 'tensor fasciae latae'],
  },

  'adductor brevis': {
    latin: 'Musculus adductor brevis',
    en: { name: 'Adductor brevis',
          does: 'The short adductor, tucked behind pectineus and adductor longus. It draws the thigh in and helps flex the hip from a lengthened position.',
          sci: 'Adductor lying deep to pectineus and adductor longus; the anterior division of the obturator nerve usually passes on its anterior surface.' },
    ko: { name: '단내전근',
          does: '치골근과 장내전근 뒤에 숨은 짧은 내전근입니다. 허벅지를 모으고 늘어난 위치에서 고관절 굴곡을 돕습니다.',
          sci: '치골근·장내전근 심부의 내전근. 폐쇄신경 전지가 대개 그 전면을 지나갑니다.' },
    origin: { en: 'Body and inferior ramus of the pubis', ko: '치골체 및 치골하지' },
    insertion: { en: 'Upper third of the linea aspera', ko: '조선 상부 1/3' },
    innervation: { nerves: { en: 'Obturator nerve', ko: '폐쇄신경' }, roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Hip adduction, assists flexion', ko: '고관절 내전, 굴곡 보조' },
    synergists: ['adductor longus', 'adductor magnus', 'pectineus'],
    antagonists: ['gluteus medius'],
  },

  'gracilis': {
    latin: 'Musculus gracilis',
    en: { name: 'Gracilis',
          does: 'A long thin strap down the very inside of the thigh, the only adductor that crosses the knee. It adducts the hip and helps bend the knee, and it is the muscle that limits a wide-legged straddle.',
          sci: 'Most superficial and medial adductor; the only two-joint muscle of the group. Hip adductor and knee flexor with medial rotation of the flexed knee, inserting into the pes anserinus.' },
    ko: { name: '박근',
          does: '허벅지 가장 안쪽을 따라 내려가는 길고 얇은 근육으로, 무릎을 넘는 유일한 내전근입니다. 고관절을 모으고 무릎 굴곡을 도우며, 다리를 넓게 벌리는 동작을 제한하는 근육입니다.',
          sci: '가장 표층·내측의 내전근이며 유일한 이관절근. 고관절 내전과 슬관절 굴곡·내회전을 담당하고 거위발건에 정지합니다.' },
    origin: { en: 'Body and inferior ramus of the pubis', ko: '치골체 및 치골하지' },
    insertion: { en: 'Medial surface of the proximal tibia, via the pes anserinus', ko: '거위발건을 통해 근위 경골 내측면' },
    innervation: { nerves: { en: 'Obturator nerve, anterior division', ko: '폐쇄신경 전지' }, roots: ['L2', 'L3'] },
    actions: { en: 'Hip adduction, knee flexion, medial rotation of the flexed knee', ko: '고관절 내전, 슬관절 굴곡, 굴곡된 무릎의 내회전' },
    synergists: ['adductor longus', 'semitendinosus'],
    antagonists: ['gluteus medius', 'vastus lateralis'],
  },

  'pectineus': {
    latin: 'Musculus pectineus',
    en: { name: 'Pectineus',
          does: 'A flat rectangle high in the groin, the bridge between the hip flexors and the adductors. It flexes and adducts at once, which is exactly what it does in a leg circle.',
          sci: 'Quadrangular muscle of the femoral triangle floor. Hip flexion and adduction; frequently receives a branch from the femoral nerve and sometimes the obturator as well.' },
    ko: { name: '치골근',
          does: '서혜부 위쪽의 납작한 사각 근육으로, 고관절 굴곡근과 내전근 사이의 다리 역할을 합니다. 굴곡과 내전을 동시에 하며, 레그 서클에서 하는 일이 정확히 그것입니다.',
          sci: '대퇴삼각 바닥의 사각형 근육. 고관절 굴곡과 내전을 담당하며 대퇴신경 분지를, 때로 폐쇄신경 분지도 함께 받습니다.' },
    origin: { en: 'Pecten pubis', ko: '치골즐' },
    insertion: { en: 'Pectineal line of the femur', ko: '대퇴골 치골근선' },
    innervation: { nerves: { en: 'Femoral nerve, sometimes with an obturator branch', ko: '대퇴신경, 때로 폐쇄신경 분지' },
                   roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Hip flexion and adduction', ko: '고관절 굴곡 및 내전' },
    synergists: ['iliacus', 'adductor brevis', 'psoas major'],
    antagonists: ['gluteus maximus'],
  },

  'sartorius': {
    latin: 'Musculus sartorius',
    en: { name: 'Sartorius',
          does: 'The longest muscle in the body, spiralling from the front of the hip bone across to the inside of the knee. It flexes, abducts and turns the hip out all at once — the tailor’s cross-legged sit is its signature.',
          sci: 'Strap muscle crossing hip and knee. Hip flexion, abduction and lateral rotation with knee flexion; forms the lateral border of the femoral triangle and inserts into the pes anserinus.' },
    ko: { name: '봉공근',
          does: '인체에서 가장 긴 근육으로, 장골 앞쪽에서 무릎 안쪽까지 나선형으로 내려갑니다. 고관절을 굽히고 벌리고 바깥으로 돌리는 일을 한 번에 하며, 양반다리가 그 대표 자세입니다.',
          sci: '고관절과 슬관절을 넘는 띠 모양 근육. 고관절 굴곡·외전·외회전과 슬관절 굴곡을 담당하며, 대퇴삼각 외측연을 이루고 거위발건에 정지합니다.' },
    origin: { en: 'Anterior superior iliac spine', ko: '전상장골극' },
    insertion: { en: 'Proximal medial tibia via the pes anserinus', ko: '거위발건을 통한 근위 경골 내측' },
    innervation: { nerves: { en: 'Femoral nerve', ko: '대퇴신경' }, roots: ['L2', 'L3'] },
    actions: { en: 'Hip flexion, abduction and lateral rotation; knee flexion', ko: '고관절 굴곡·외전·외회전, 슬관절 굴곡' },
    synergists: ['iliacus', 'rectus femoris', 'tensor fasciae latae'],
    antagonists: ['gluteus maximus', 'adductor longus'],
  },

  'vastus lateralis': {
    latin: 'Musculus vastus lateralis',
    en: { name: 'Vastus lateralis',
          does: 'The largest of the four quadriceps, on the outside of the thigh. It straightens the knee and, being off to one side, has a sideways pull on the kneecap that the inner quad has to balance.',
          sci: 'Largest quadriceps head. Knee extension; its lateral vector on the patella is opposed by vastus medialis obliquus, and the balance between them shapes patellar tracking.' },
    ko: { name: '외측광근',
          does: '대퇴사두근 중 가장 큰 근육으로 허벅지 바깥에 있습니다. 무릎을 펴며, 옆으로 치우쳐 있어 슬개골을 바깥으로 당기는 힘을 만들고 이를 내측광근이 균형 잡습니다.',
          sci: '대퇴사두근 중 최대 근두. 슬관절 신전을 담당하며 슬개골에 대한 외측 벡터를 내측광근 사근부가 상쇄합니다. 둘의 균형이 슬개골 활주를 결정합니다.' },
    origin: { en: 'Greater trochanter and lateral lip of the linea aspera', ko: '대전자 및 조선 외측순' },
    insertion: { en: 'Patella and tibial tuberosity via the quadriceps and patellar tendons', ko: '사두근건과 슬개건을 통해 슬개골 및 경골조면' },
    innervation: { nerves: { en: 'Femoral nerve', ko: '대퇴신경' }, roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Knee extension', ko: '슬관절 신전' },
    synergists: ['vastus medialis', 'vastus intermedius', 'rectus femoris'],
    antagonists: ['biceps femoris', 'semitendinosus'],
  },

  'vastus medialis': {
    latin: 'Musculus vastus medialis',
    en: { name: 'Vastus medialis',
          does: 'The teardrop just above the inside of the knee. Its lowest fibres run almost sideways and are the ones that keep the kneecap from drifting outward as you straighten.',
          sci: 'Medial quadriceps head. Its distal oblique fibres (vastus medialis obliquus) insert at roughly 50° to the femoral shaft and provide the principal medial restraint to patellar tracking.' },
    ko: { name: '내측광근',
          does: '무릎 안쪽 바로 위의 물방울 모양 근육입니다. 가장 아래 섬유는 거의 옆으로 달리며, 무릎을 펼 때 슬개골이 바깥으로 밀리지 않게 잡아 줍니다.',
          sci: '내측 대퇴사두근두. 원위 사근 섬유는 대퇴골간에 약 50도로 정지하여 슬개골 활주의 주요 내측 제동 역할을 합니다.' },
    origin: { en: 'Intertrochanteric line and medial lip of the linea aspera', ko: '전자간선 및 조선 내측순' },
    insertion: { en: 'Patella and tibial tuberosity via the quadriceps and patellar tendons', ko: '사두근건과 슬개건을 통해 슬개골 및 경골조면' },
    innervation: { nerves: { en: 'Femoral nerve', ko: '대퇴신경' }, roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Knee extension; medial patellar stabilisation', ko: '슬관절 신전, 슬개골 내측 안정화' },
    synergists: ['vastus lateralis', 'vastus intermedius', 'rectus femoris'],
    antagonists: ['biceps femoris'],
  },

  'vastus intermedius': {
    latin: 'Musculus vastus intermedius',
    en: { name: 'Vastus intermedius',
          does: 'The quadriceps you cannot see, lying flat on the front of the thigh bone underneath rectus femoris. It only straightens the knee — it does not cross the hip.',
          sci: 'Deep quadriceps head on the anterior femoral shaft, beneath rectus femoris. Pure knee extensor; its deep fibres form articularis genu, which retracts the suprapatellar bursa.' },
    ko: { name: '중간광근',
          does: '대퇴직근 아래, 대퇴골 앞면에 납작하게 붙어 보이지 않는 사두근입니다. 고관절을 넘지 않으므로 오직 무릎만 폅니다.',
          sci: '대퇴직근 심부, 대퇴골간 전면의 심부 사두근두. 순수 슬관절 신전근이며 심부 섬유가 슬관절근을 이루어 슬개상낭을 견인합니다.' },
    origin: { en: 'Anterior and lateral surfaces of the femoral shaft', ko: '대퇴골간 전면 및 외측면' },
    insertion: { en: 'Patella via the quadriceps tendon', ko: '사두근건을 통한 슬개골' },
    innervation: { nerves: { en: 'Femoral nerve', ko: '대퇴신경' }, roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Knee extension', ko: '슬관절 신전' },
    synergists: ['vastus lateralis', 'vastus medialis'],
    antagonists: ['biceps femoris'],
  },

  'popliteus': {
    latin: 'Musculus popliteus',
    en: { name: 'Popliteus',
          does: 'A small triangle behind the knee that unlocks it. To bend a fully straight knee, something has to rotate the tibia inward first, and this is it.',
          sci: 'Unlocks the extended knee by producing medial tibial rotation on a fixed femur, reversing the screw-home mechanism; also resists posterolateral rotatory instability.' },
    ko: { name: '슬와근',
          does: '무릎 뒤의 작은 삼각형 근육으로 무릎의 잠금을 풉니다. 완전히 편 무릎을 굽히려면 먼저 경골을 안으로 돌려야 하는데 그 일을 합니다.',
          sci: '고정된 대퇴골에 대해 경골을 내회전시켜 신전된 슬관절의 나사잠김 기전을 해제합니다. 후외측 회전 불안정에도 저항합니다.' },
    origin: { en: 'Lateral femoral condyle', ko: '대퇴골 외측과' },
    insertion: { en: 'Posterior surface of the proximal tibia above the soleal line', ko: '가자미근선 위 근위 경골 후면' },
    innervation: { nerves: { en: 'Tibial nerve', ko: '경골신경' }, roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Unlocks the extended knee; assists knee flexion', ko: '신전된 무릎의 잠금 해제, 슬관절 굴곡 보조' },
    synergists: ['semitendinosus', 'gastrocnemius'],
    antagonists: ['vastus intermedius'],
  },

  /* ------------------------------------------------------------------ leg and foot */

  'tibialis anterior': {
    latin: 'Musculus tibialis anterior',
    en: { name: 'Tibialis anterior',
          does: 'The muscle on the front of the shin. It lifts the foot so the toes clear the ground when you walk, and it lowers the foot under control as the heel lands.',
          sci: 'Principal ankle dorsiflexor and inverter. Concentric in swing to clear the toes; eccentric from heel strike to foot-flat, controlling forefoot descent.' },
    ko: { name: '전경골근',
          does: '정강이 앞쪽 근육입니다. 걸을 때 발끝이 바닥에 걸리지 않도록 발을 들어 올리고, 뒤꿈치가 닿은 뒤 발을 조절하며 내려놓습니다.',
          sci: '주 족배굴곡·내번근. 유각기에는 구심성으로 발끝을 들어 올리고, 뒤꿈치 접지부터 전족부 접지까지는 원심성으로 하강을 조절합니다.' },
    origin: { en: 'Lateral condyle and proximal half of the lateral tibia, interosseous membrane', ko: '경골 외측과 및 경골 외측면 근위 1/2, 골간막' },
    insertion: { en: 'Medial cuneiform and base of the first metatarsal', ko: '내측 설상골 및 제1중족골 기저' },
    innervation: { nerves: { en: 'Deep fibular nerve', ko: '심비골신경' }, roots: ['L4', 'L5'] },
    actions: { en: 'Ankle dorsiflexion and inversion', ko: '족배굴곡 및 내번' },
    synergists: ['extensor digitorum longus', 'extensor hallucis longus'],
    antagonists: ['gastrocnemius', 'soleus', 'fibularis longus'],
  },

  'tibialis posterior': {
    latin: 'Musculus tibialis posterior',
    en: { name: 'Tibialis posterior',
          does: 'The deepest muscle of the calf, and the main support of the arch of the foot. It runs behind the inner ankle bone and fans out under the midfoot.',
          sci: 'Deepest posterior compartment muscle and primary dynamic support of the medial longitudinal arch. Ankle plantarflexion and inversion; its insufficiency produces progressive collapsing foot deformity.' },
    ko: { name: '후경골근',
          does: '종아리에서 가장 깊은 근육이며 발 아치를 지탱하는 주된 근육입니다. 안쪽 복사뼈 뒤를 지나 중족부 아래로 부채처럼 퍼집니다.',
          sci: '후방구획 최심부 근육이며 내측 종아치의 주요 동적 지지체. 족저굴곡과 내번을 담당하고, 기능부전 시 진행성 편평족 변형이 나타납니다.' },
    origin: { en: 'Interosseous membrane and adjacent tibia and fibula', ko: '골간막 및 인접 경골·비골' },
    insertion: { en: 'Navicular tuberosity, spreading to cuneiforms, cuboid and metatarsals 2–4', ko: '주상골 조면에서 설상골·입방골·제2–4중족골로 확산' },
    innervation: { nerves: { en: 'Tibial nerve', ko: '경골신경' }, roots: ['L4', 'L5'] },
    actions: { en: 'Ankle plantarflexion, inversion, arch support', ko: '족저굴곡, 내번, 아치 지지' },
    synergists: ['flexor digitorum longus', 'soleus', 'abductor hallucis'],
    antagonists: ['fibularis longus', 'tibialis anterior'],
  },

  'fibularis longus': {
    latin: 'Musculus fibularis longus',
    en: { name: 'Fibularis longus',
          does: 'Runs down the outside of the shin and then crosses under the sole to the far side of the foot. That crossing is what presses the big toe side of the foot into the floor.',
          sci: 'Lateral compartment. Everts and plantarflexes; its tendon crosses the plantar surface to the first metatarsal base, plantarflexing the first ray and supporting the transverse arch.' },
    ko: { name: '장비골근',
          does: '정강이 바깥을 따라 내려간 뒤 발바닥을 가로질러 반대쪽까지 갑니다. 이 교차가 엄지발가락 쪽을 바닥으로 눌러 주는 힘을 만듭니다.',
          sci: '외측구획 근육. 외번과 족저굴곡을 담당하며, 힘줄이 발바닥을 가로질러 제1중족골 기저에 정지해 제1열을 족저굴곡시키고 횡아치를 지지합니다.' },
    origin: { en: 'Head and proximal two-thirds of the lateral fibula', ko: '비골두 및 비골 외측 근위 2/3' },
    insertion: { en: 'Base of the first metatarsal and medial cuneiform, plantar surface', ko: '제1중족골 기저 및 내측 설상골 족저면' },
    innervation: { nerves: { en: 'Superficial fibular nerve', ko: '천비골신경' }, roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Ankle eversion and plantarflexion; first ray plantarflexion', ko: '족부 외번 및 족저굴곡, 제1열 족저굴곡' },
    synergists: ['fibularis brevis', 'soleus'],
    antagonists: ['tibialis posterior', 'tibialis anterior'],
  },

  'fibularis brevis': {
    latin: 'Musculus fibularis brevis',
    en: { name: 'Fibularis brevis',
          does: 'The shorter of the two muscles on the outside of the shin. It is the strongest evertor and the main defence against rolling the ankle outward.',
          sci: 'Lateral compartment. Primary evertor of the foot; its insertion at the fifth metatarsal styloid is the avulsion site in inversion ankle injury.' },
    ko: { name: '단비골근',
          does: '정강이 바깥 두 근육 중 짧은 쪽입니다. 가장 강한 외번근이며 발목이 안쪽으로 접질리는 것을 막는 주된 방어입니다.',
          sci: '외측구획 근육. 주된 외번근이며 제5중족골 경상돌기 정지부는 내번 손상 시 견열 골절 부위입니다.' },
    origin: { en: 'Distal two-thirds of the lateral fibula', ko: '비골 외측 원위 2/3' },
    insertion: { en: 'Styloid process at the base of the fifth metatarsal', ko: '제5중족골 기저 경상돌기' },
    innervation: { nerves: { en: 'Superficial fibular nerve', ko: '천비골신경' }, roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Foot eversion, assists plantarflexion', ko: '족부 외번, 족저굴곡 보조' },
    synergists: ['fibularis longus'],
    antagonists: ['tibialis posterior'],
  },

  'flexor hallucis longus': {
    latin: 'Musculus flexor hallucis longus',
    en: { name: 'Flexor hallucis longus',
          does: 'Bends the big toe and gives the final push at the end of a step. In a relevé or a standing balance it is what stops you toppling forward over the toes.',
          sci: 'Deep posterior compartment. Flexes the hallux and plantarflexes the ankle; provides the terminal push-off moment and dynamic support to the medial arch.' },
    ko: { name: '장무지굴근',
          does: '엄지발가락을 굽히고 걸음의 마지막 밀어내기를 만듭니다. 를르베나 선 균형에서 발끝 위로 넘어지지 않게 잡아 주는 근육입니다.',
          sci: '후방 심부구획. 무지 굴곡과 족저굴곡을 담당하며 최종 밀기 모멘트와 내측 아치의 동적 지지를 제공합니다.' },
    origin: { en: 'Posterior surface of the distal two-thirds of the fibula', ko: '비골 후면 원위 2/3' },
    insertion: { en: 'Base of the distal phalanx of the great toe', ko: '무지 말절골 기저' },
    innervation: { nerves: { en: 'Tibial nerve', ko: '경골신경' }, roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Hallux flexion, ankle plantarflexion, arch support', ko: '무지 굴곡, 족저굴곡, 아치 지지' },
    synergists: ['flexor digitorum longus', 'tibialis posterior'],
    antagonists: ['extensor hallucis longus'],
  },

  'flexor digitorum longus': {
    latin: 'Musculus flexor digitorum longus',
    en: { name: 'Flexor digitorum longus',
          does: 'Curls the four small toes into the floor. In standing balance the toes gripping is often this muscle compensating for a hip that is not doing its job.',
          sci: 'Deep posterior compartment. Flexes the lateral four toes and assists plantarflexion and inversion; excessive activity in stance is a recognised distal compensation for proximal insufficiency.' },
    ko: { name: '장지굴근',
          does: '네 개의 작은 발가락을 바닥 쪽으로 구부립니다. 선 균형에서 발가락으로 움켜쥐는 것은 대개 제 역할을 못 하는 고관절을 이 근육이 보상하는 것입니다.',
          sci: '후방 심부구획. 외측 네 발가락을 굴곡시키고 족저굴곡·내번을 보조합니다. 입각기의 과활성은 근위부 기능부전에 대한 원위 보상으로 알려져 있습니다.' },
    origin: { en: 'Posterior surface of the tibia below the soleal line', ko: '가자미근선 아래 경골 후면' },
    insertion: { en: 'Bases of the distal phalanges of toes two to five', ko: '제2–5지 말절골 기저' },
    innervation: { nerves: { en: 'Tibial nerve', ko: '경골신경' }, roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Toe flexion, ankle plantarflexion and inversion', ko: '족지 굴곡, 족저굴곡 및 내번' },
    synergists: ['flexor hallucis longus', 'tibialis posterior'],
    antagonists: ['extensor digitorum longus'],
  },

  'extensor digitorum longus': {
    latin: 'Musculus extensor digitorum longus',
    en: { name: 'Extensor digitorum longus',
          does: 'Straightens the four small toes and helps lift the foot. When you flex the foot hard in a Pilates leg series, this is the tendon fan you can see on top of the foot.',
          sci: 'Anterior compartment. Extends the lateral four toes at the metatarsophalangeal and interphalangeal joints and assists ankle dorsiflexion and eversion.' },
    ko: { name: '장지신근',
          does: '작은 발가락 네 개를 펴고 발을 드는 것을 돕습니다. 필라테스 레그 시리즈에서 발을 강하게 당길 때 발등에 보이는 힘줄 부채가 이것입니다.',
          sci: '전방구획. 외측 네 발가락을 중족지관절과 지간관절에서 신전시키고 족배굴곡·외번을 보조합니다.' },
    origin: { en: 'Lateral tibial condyle, proximal fibula, interosseous membrane', ko: '경골 외측과, 근위 비골, 골간막' },
    insertion: { en: 'Extensor expansions of toes two to five', ko: '제2–5지 신전건막' },
    innervation: { nerves: { en: 'Deep fibular nerve', ko: '심비골신경' }, roots: ['L5', 'S1'] },
    actions: { en: 'Toe extension, ankle dorsiflexion, assists eversion', ko: '족지 신전, 족배굴곡, 외번 보조' },
    synergists: ['tibialis anterior', 'extensor hallucis longus'],
    antagonists: ['flexor digitorum longus'],
  },

  'extensor hallucis longus': {
    latin: 'Musculus extensor hallucis longus',
    en: { name: 'Extensor hallucis longus',
          does: 'Lifts the big toe. It is the muscle tested first when a nerve root at L5 is in question, because it has an unusually pure root supply.',
          sci: 'Anterior compartment. Extends the hallux and assists dorsiflexion; the standard clinical myotome test for L5.' },
    ko: { name: '장무지신근',
          does: '엄지발가락을 들어 올립니다. L5 신경근을 의심할 때 가장 먼저 검사하는 근육인데, 신경근 지배가 유난히 순수하기 때문입니다.',
          sci: '전방구획. 무지를 신전시키고 족배굴곡을 보조합니다. L5 근절 검사의 표준입니다.' },
    origin: { en: 'Middle of the anterior fibula and interosseous membrane', ko: '비골 전면 중앙 및 골간막' },
    insertion: { en: 'Base of the distal phalanx of the great toe', ko: '무지 말절골 기저' },
    innervation: { nerves: { en: 'Deep fibular nerve', ko: '심비골신경' }, roots: ['L5', 'S1'] },
    actions: { en: 'Hallux extension, ankle dorsiflexion', ko: '무지 신전, 족배굴곡' },
    synergists: ['tibialis anterior', 'extensor digitorum longus'],
    antagonists: ['flexor hallucis longus'],
  },

  'abductor hallucis': {
    latin: 'Musculus abductor hallucis',
    en: { name: 'Abductor hallucis',
          does: 'Runs along the inside edge of the sole. It spreads the big toe away from the others and lifts the inner arch — the muscle behind the "short foot" exercise.',
          sci: 'First-layer plantar intrinsic. Abducts and flexes the hallux and elevates the medial longitudinal arch; the principal target of short-foot and intrinsic foot training.' },
    ko: { name: '무지외전근',
          does: '발바닥 안쪽 가장자리를 따라 있습니다. 엄지발가락을 다른 발가락에서 벌리고 내측 아치를 들어 올리며, 숏풋 운동의 핵심 근육입니다.',
          sci: '족저 제1층 내재근. 무지를 외전·굴곡시키고 내측 종아치를 들어 올립니다. 숏풋 및 내재근 훈련의 주 표적입니다.' },
    origin: { en: 'Medial process of the calcaneal tuberosity and plantar aponeurosis', ko: '종골결절 내측돌기 및 족저건막' },
    insertion: { en: 'Medial side of the base of the proximal phalanx of the great toe', ko: '무지 기절골 기저 내측' },
    innervation: { nerves: { en: 'Medial plantar nerve', ko: '내측족저신경' }, roots: ['S1', 'S2'] },
    actions: { en: 'Hallux abduction and flexion, arch elevation', ko: '무지 외전·굴곡, 아치 거상' },
    synergists: ['tibialis posterior', 'flexor hallucis longus'],
    antagonists: ['fibularis longus'],
  },

  'plantaris': {
    latin: 'Musculus plantaris',
    en: { name: 'Plantaris',
          does: 'A small muscle with a very long thin tendon running down the calf. It contributes almost nothing to force and is thought to be dense in proprioceptive receptors instead.',
          sci: 'Vestigial in force terms; a short belly with a long tendon. High spindle density suggests a proprioceptive role for the triceps surae complex. Absent in roughly 10% of limbs.' },
    ko: { name: '족척근',
          does: '종아리를 따라 아주 길고 얇은 힘줄을 가진 작은 근육입니다. 힘에는 거의 기여하지 않으며 대신 고유감각 수용기가 밀집해 있다고 여겨집니다.',
          sci: '힘 측면에서는 흔적기관. 짧은 근복과 긴 힘줄을 가지며, 높은 근방추 밀도는 하퇴삼두근 복합체의 고유감각 역할을 시사합니다. 약 10%의 사지에서 결손됩니다.' },
    origin: { en: 'Lateral supracondylar line of the femur', ko: '대퇴골 외측 과상선' },
    insertion: { en: 'Calcaneus, medial to the calcaneal tendon', ko: '아킬레스건 내측의 종골' },
    innervation: { nerves: { en: 'Tibial nerve', ko: '경골신경' }, roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Weak knee flexion and ankle plantarflexion; proprioception', ko: '약한 슬관절 굴곡 및 족저굴곡, 고유감각' },
    synergists: ['gastrocnemius', 'soleus'],
    antagonists: ['tibialis anterior'],
  },

  /* ------------------------------------------------------------------ pelvic floor */

  'pubococcygeus': {
    latin: 'Musculus pubococcygeus',
    en: { name: 'Pubococcygeus',
          does: 'The main sheet of the pelvic floor, slung from the pubic bone to the tailbone. It lifts and closes, and it works with the diaphragm and the deep abdominals as one pressure system rather than as a separate muscle.',
          sci: 'Principal component of levator ani. Elevates the pelvic floor, supports the pelvic viscera and contributes to continence; co-activates tonically with transversus abdominis and the diaphragm to regulate intra-abdominal pressure.' },
    ko: { name: '치골미골근',
          does: '치골에서 꼬리뼈까지 걸린 골반저의 주된 판입니다. 들어 올리고 조이며, 별개의 근육이 아니라 횡격막·심부 복부와 함께 하나의 압력 시스템으로 작동합니다.',
          sci: '항문거근의 주 구성부. 골반저를 거상하고 골반 장기를 지지하며 자제에 기여합니다. 복횡근·횡격막과 긴장성으로 동시 활성화되어 복강내압을 조절합니다.' },
    origin: { en: 'Posterior surface of the body of the pubis and the tendinous arch of levator ani', ko: '치골체 후면 및 항문거근 건궁' },
    insertion: { en: 'Coccyx, anococcygeal body and perineal body', ko: '미골, 항문미골체, 회음체' },
    innervation: { nerves: { en: 'Nerve to levator ani, with a pudendal contribution', ko: '항문거근신경, 음부신경 기여' },
                   roots: ['S3', 'S4'] },
    actions: { en: 'Pelvic floor elevation, visceral support, intra-abdominal pressure regulation',
               ko: '골반저 거상, 장기 지지, 복강내압 조절' },
    synergists: ['transversus abdominis', 'diaphragm', 'iliococcygeus'],
    antagonists: [],
    evidence: 'apa_timing',
  },

  'iliococcygeus': {
    latin: 'Musculus iliococcygeus',
    en: { name: 'Iliococcygeus',
          does: 'The wider, flatter part of the pelvic floor, spanning side to side like a hammock behind pubococcygeus.',
          sci: 'Posterolateral component of levator ani, arising from the tendinous arch. Forms the levator plate; supports the pelvic organs against downward pressure.' },
    ko: { name: '장골미골근',
          does: '골반저에서 더 넓고 납작한 부분으로, 치골미골근 뒤에서 해먹처럼 좌우로 걸쳐 있습니다.',
          sci: '건궁에서 기시하는 항문거근의 후외측 구성부. 거근판을 형성하며 하방 압력에 대해 골반 장기를 지지합니다.' },
    origin: { en: 'Tendinous arch of levator ani and ischial spine', ko: '항문거근 건궁 및 좌골극' },
    insertion: { en: 'Anococcygeal raphe and coccyx', ko: '항문미골봉선 및 미골' },
    innervation: { nerves: { en: 'Nerve to levator ani', ko: '항문거근신경' }, roots: ['S3', 'S4'] },
    actions: { en: 'Pelvic floor support and elevation', ko: '골반저 지지 및 거상' },
    synergists: ['pubococcygeus', 'coccygeus'],
    antagonists: [],
  },

  'coccygeus': {
    latin: 'Musculus coccygeus',
    en: { name: 'Coccygeus',
          does: 'The small triangle at the back of the pelvic floor, sharing its fibres with the sacrospinous ligament. It pulls the tailbone forward after defecation and helps steady the sacroiliac joint.',
          sci: 'Posterior part of the pelvic diaphragm, coextensive with the sacrospinous ligament. Flexes the coccyx and contributes to sacroiliac and pelvic-ring stability.' },
    ko: { name: '미골근',
          does: '골반저 뒤쪽의 작은 삼각형으로, 천극인대와 섬유를 공유합니다. 배변 후 꼬리뼈를 앞으로 당기고 천장관절을 안정시키는 데 기여합니다.',
          sci: '골반가로막 후방부로 천극인대와 연속적입니다. 미골을 굴곡시키고 천장관절 및 골반환 안정에 기여합니다.' },
    origin: { en: 'Ischial spine and sacrospinous ligament', ko: '좌골극 및 천극인대' },
    insertion: { en: 'Lateral border of the coccyx and lowest sacrum', ko: '미골 외측연 및 천골 최하부' },
    innervation: { nerves: { en: 'Anterior rami of S4 and S5', ko: 'S4–S5 전지' }, roots: ['S4', 'S5'] },
    actions: { en: 'Coccygeal flexion, pelvic floor support, sacroiliac stabilisation', ko: '미골 굴곡, 골반저 지지, 천장관절 안정화' },
    synergists: ['pubococcygeus', 'iliococcygeus', 'piriformis'],
    antagonists: [],
  },

  /* ------------------------------------------------------------------ trunk and back */

  'iliocostalis thoracis': {
    latin: 'Musculus iliocostalis thoracis',
    en: { name: 'Iliocostalis thoracis',
          does: 'The outermost column of the back extensors at rib level, running rib to rib. It extends and side-bends the thoracic spine and helps pull the ribcage down.',
          sci: 'Lateral column of erector spinae in the thoracic region, spanning the angles of the ribs. Thoracic extension, ipsilateral lateral flexion, and costal depression.' },
    ko: { name: '흉장늑근',
          does: '갈비뼈 높이에서 등 신전근의 가장 바깥 기둥이며 갈비뼈에서 갈비뼈로 이어집니다. 흉추를 펴고 옆으로 굽히며 흉곽을 아래로 당기는 데 기여합니다.',
          sci: '흉부 척주기립근의 외측 기둥으로 늑골각을 잇습니다. 흉추 신전, 동측 측굴, 늑골 하강을 담당합니다.' },
    origin: { en: 'Angles of the lower six ribs', ko: '하위 6개 늑골각' },
    insertion: { en: 'Angles of the upper six ribs and the transverse process of C7', ko: '상위 6개 늑골각 및 C7 횡돌기' },
    innervation: { nerves: { en: 'Posterior rami of thoracic spinal nerves', ko: '흉추 척수신경 후지' },
                   roots: ['T1', 'T6', 'T12'] },
    actions: { en: 'Thoracic extension and ipsilateral lateral flexion', ko: '흉추 신전 및 동측 측굴' },
    synergists: ['longissimus thoracis', 'iliocostalis lumborum', 'spinalis thoracis'],
    antagonists: ['rectus abdominis'],
  },

  'spinalis thoracis': {
    latin: 'Musculus spinalis thoracis',
    en: { name: 'Spinalis thoracis',
          does: 'The innermost column of the erector spinae, running spinous process to spinous process right beside the midline. It is the one that extends the mid-back specifically.',
          sci: 'Medial column of erector spinae, spanning spinous processes of the lower thoracic and upper lumbar to the upper thoracic vertebrae. Thoracic extension with minimal rotational moment.' },
    ko: { name: '흉극근',
          does: '척주기립근의 가장 안쪽 기둥으로, 정중선 바로 옆에서 극돌기와 극돌기를 잇습니다. 특히 등 중간을 펴는 근육입니다.',
          sci: '척주기립근의 내측 기둥. 하부 흉추·상부 요추 극돌기에서 상부 흉추 극돌기로 이어지며 회전 모멘트가 거의 없는 흉추 신전을 담당합니다.' },
    origin: { en: 'Spinous processes of T11–L2', ko: 'T11–L2 극돌기' },
    insertion: { en: 'Spinous processes of T2–T8', ko: 'T2–T8 극돌기' },
    innervation: { nerves: { en: 'Posterior rami of thoracic spinal nerves', ko: '흉추 척수신경 후지' },
                   roots: ['T2', 'T6', 'T11'] },
    actions: { en: 'Thoracic extension', ko: '흉추 신전' },
    synergists: ['longissimus thoracis', 'multifidus', 'semispinalis thoracis'],
    antagonists: ['rectus abdominis'],
  },

  'semispinalis thoracis': {
    latin: 'Musculus semispinalis thoracis',
    en: { name: 'Semispinalis thoracis',
          does: 'Crosses four to six vertebrae at a shallow angle, so it extends the thoracic spine and turns it the opposite way at the same time.',
          sci: 'Transversospinalis layer spanning 4–6 segments from transverse to spinous processes. Thoracic extension with contralateral rotation.' },
    ko: { name: '흉반극근',
          does: '얕은 각도로 네다섯 마디를 건너므로 흉추를 펴는 동시에 반대쪽으로 돌립니다.',
          sci: '횡돌기에서 극돌기로 4–6분절을 건너는 횡돌기극근층. 흉추 신전과 반대측 회전을 담당합니다.' },
    origin: { en: 'Transverse processes of T6–T10', ko: 'T6–T10 횡돌기' },
    insertion: { en: 'Spinous processes of C6–T4', ko: 'C6–T4 극돌기' },
    innervation: { nerves: { en: 'Medial branches of the posterior rami', ko: '후지 내측분지' },
                   roots: ['T1', 'T4', 'T8'] },
    actions: { en: 'Thoracic extension and contralateral rotation', ko: '흉추 신전 및 반대측 회전' },
    synergists: ['multifidus', 'spinalis thoracis'],
    antagonists: ['external oblique'],
  },

  'thoracic rotator': {
    latin: 'Musculi rotatores thoracis',
    en: { name: 'Rotatores (thoracic)',
          does: 'The deepest and shortest back muscles, crossing one or two vertebrae. They are so short that they produce very little turning force, and are thought to act mostly as position sensors for the spine.',
          sci: 'Deepest transversospinalis, spanning one to two segments. Very small moment arm; exceptionally high muscle spindle density suggests a proprioceptive rather than a prime-mover role.' },
    ko: { name: '흉회전근',
          does: '한두 마디만 건너는 가장 깊고 짧은 등 근육입니다. 너무 짧아 회전력은 거의 만들지 못하며, 주로 척추의 위치 감지기로 작용한다고 여겨집니다.',
          sci: '한두 분절을 건너는 최심부 횡돌기극근. 모멘트암이 매우 작고 근방추 밀도가 예외적으로 높아 주동근보다 고유감각 역할이 시사됩니다.' },
    origin: { en: 'Transverse processes of the thoracic vertebrae', ko: '흉추 횡돌기' },
    insertion: { en: 'Lamina and spinous process one or two segments above', ko: '한두 분절 위 추궁판 및 극돌기' },
    innervation: { nerves: { en: 'Medial branches of the thoracic posterior rami, segmentally', ko: '흉추 후지 내측분지, 분절별' },
                   roots: ['T1', 'T6', 'T12'] },
    actions: { en: 'Segmental proprioception; small contralateral rotation moment', ko: '분절 고유감각, 소폭의 반대측 회전' },
    synergists: ['multifidus', 'semispinalis thoracis'],
    antagonists: [],
  },

  'lumbar rotator': {
    latin: 'Musculi rotatores lumborum',
    en: { name: 'Rotatores (lumbar)',
          does: 'The same very short deep muscles at lumbar level. The lumbar spine barely rotates at all, so these are almost entirely about sensing where each segment is.',
          sci: 'Deepest transversospinalis of the lumbar region. Given that segmental lumbar axial rotation is roughly 2° per level, the functional contribution is proprioceptive rather than kinetic.' },
    ko: { name: '요회전근',
          does: '요추 높이의 같은 계열의 아주 짧은 심부 근육입니다. 요추는 회전이 거의 없으므로 사실상 각 분절의 위치를 감지하는 역할이 전부입니다.',
          sci: '요추부 최심부 횡돌기극근. 요추 분절 축회전이 분절당 약 2도에 불과하므로 기능적 기여는 운동보다 고유감각입니다.' },
    origin: { en: 'Mamillary processes of the lumbar vertebrae', ko: '요추 유두돌기' },
    insertion: { en: 'Lamina of the vertebra one or two segments above', ko: '한두 분절 위 추궁판' },
    innervation: { nerves: { en: 'Medial branches of the lumbar posterior rami', ko: '요추 후지 내측분지' },
                   roots: ['L1', 'L3', 'L5'] },
    actions: { en: 'Segmental proprioception and stiffness', ko: '분절 고유감각 및 강성' },
    synergists: ['multifidus'],
    antagonists: [],
  },

  'serratus posterior inferior': {
    latin: 'Musculus serratus posterior inferior',
    en: { name: 'Serratus posterior inferior',
          does: 'A thin sheet across the lower ribs at the back. It pulls the last four ribs down and back, and is usually described as helping the mechanics of a forced exhale.',
          sci: 'Thin respiratory-accessory sheet from the thoracolumbar fascia to ribs 9–12. Depresses the lower ribs, resisting the upward pull of the diaphragm on its costal attachments.' },
    ko: { name: '하후거근',
          does: '등 아래 갈비뼈를 가로지르는 얇은 판입니다. 마지막 네 갈비뼈를 아래·뒤로 당기며, 강제 호기의 역학을 돕는 근육으로 설명됩니다.',
          sci: '흉요근막에서 제9–12늑골로 가는 얇은 호흡 보조판. 하위 늑골을 하강시켜 횡격막이 늑골 부착부를 위로 당기는 힘에 저항합니다.' },
    origin: { en: 'Spinous processes of T11–L2 via the thoracolumbar fascia', ko: '흉요근막을 통한 T11–L2 극돌기' },
    insertion: { en: 'Inferior borders of ribs 9–12', ko: '제9–12늑골 하연' },
    innervation: { nerves: { en: 'Anterior rami of T9–T12', ko: 'T9–T12 전지' }, roots: ['T9', 'T10', 'T11', 'T12'] },
    actions: { en: 'Depression of the lower ribs; accessory expiration', ko: '하위 늑골 하강, 보조 호기' },
    synergists: ['internal intercostal muscle', 'quadratus lumborum'],
    antagonists: ['diaphragm'],
  },

  'external intercostal muscle': {
    latin: 'Musculi intercostales externi',
    en: { name: 'External intercostals',
          does: 'The outer layer between the ribs, fibres running down and forward. They lift the ribs on an inhale — the reason a wide lateral breath is possible at all.',
          sci: 'Outer intercostal layer, fibres directed inferoanteriorly. Elevate the ribs during inspiration, increasing the anteroposterior and transverse thoracic diameters.' },
    ko: { name: '외늑간근',
          does: '갈비뼈 사이의 바깥층으로 섬유가 아래·앞으로 달립니다. 들이쉴 때 갈비뼈를 들어 올리며, 넓은 측방 호흡이 가능한 이유입니다.',
          sci: '외측 늑간층으로 섬유가 하전방으로 주행합니다. 흡기 시 늑골을 거상하여 흉곽의 전후경과 횡경을 늘립니다.' },
    origin: { en: 'Inferior border of the rib above', ko: '위쪽 늑골 하연' },
    insertion: { en: 'Superior border of the rib below', ko: '아래쪽 늑골 상연' },
    innervation: { nerves: { en: 'Intercostal nerves', ko: '늑간신경' },
                   roots: ['T1', 'T4', 'T8', 'T11'] },
    actions: { en: 'Rib elevation; inspiration', ko: '늑골 거상, 흡기' },
    synergists: ['diaphragm', 'scalenus anterior'],
    antagonists: ['internal intercostal muscle'],
  },

  'internal intercostal muscle': {
    latin: 'Musculi intercostales interni',
    en: { name: 'Internal intercostals',
          does: 'The layer underneath, fibres running the opposite way. They pull the ribs down on a forced exhale — the half of the breath Pilates spends most of its attention on.',
          sci: 'Inner intercostal layer with fibres perpendicular to the external layer. Depress the ribs in forced expiration; the interchondral portion assists inspiration.' },
    ko: { name: '내늑간근',
          does: '그 아래층이며 섬유가 반대 방향으로 달립니다. 강제 호기에서 갈비뼈를 아래로 당기며, 필라테스가 가장 주의를 기울이는 호흡의 절반입니다.',
          sci: '외층과 수직인 섬유 방향의 내측 늑간층. 강제 호기 시 늑골을 하강시키며, 연골간부는 흡기를 보조합니다.' },
    origin: { en: 'Costal groove of the rib above', ko: '위쪽 늑골의 늑골구' },
    insertion: { en: 'Superior border of the rib below', ko: '아래쪽 늑골 상연' },
    innervation: { nerves: { en: 'Intercostal nerves', ko: '늑간신경' },
                   roots: ['T1', 'T4', 'T8', 'T11'] },
    actions: { en: 'Rib depression; forced expiration', ko: '늑골 하강, 강제 호기' },
    synergists: ['external oblique', 'transversus abdominis'],
    antagonists: ['external intercostal muscle', 'diaphragm'],
  },

  'transversus thoracis': {
    latin: 'Musculus transversus thoracis',
    en: { name: 'Transversus thoracis',
          does: 'A thin fan on the inside of the front of the chest wall, spreading from the sternum to the rib cartilages. It draws the front ribs down.',
          sci: 'Innermost layer on the posterior surface of the anterior thoracic wall. Depresses the costal cartilages; probably contributes proprioceptive information about rib position.' },
    ko: { name: '흉횡근',
          does: '가슴 앞벽 안쪽의 얇은 부채꼴로, 흉골에서 늑연골로 퍼집니다. 앞쪽 갈비뼈를 아래로 당깁니다.',
          sci: '전흉벽 후면의 최심층. 늑연골을 하강시키며 늑골 위치에 대한 고유감각 정보를 제공할 것으로 여겨집니다.' },
    origin: { en: 'Posterior surface of the lower sternum and xiphoid process', ko: '흉골 하부 및 검상돌기 후면' },
    insertion: { en: 'Costal cartilages 2–6', ko: '제2–6늑연골' },
    innervation: { nerves: { en: 'Intercostal nerves', ko: '늑간신경' }, roots: ['T2', 'T4', 'T6'] },
    actions: { en: 'Depression of the costal cartilages', ko: '늑연골 하강' },
    synergists: ['internal intercostal muscle'],
    antagonists: ['diaphragm'],
  },

  'pyramidalis': {
    latin: 'Musculus pyramidalis',
    en: { name: 'Pyramidalis',
          does: 'A small triangle in front of the lowest part of rectus abdominis. It tenses the linea alba and is missing altogether in about a fifth of people.',
          sci: 'Small triangular muscle anterior to the lower rectus abdominis within the rectus sheath. Tenses the linea alba; absent in roughly 20% of individuals.' },
    ko: { name: '추체근',
          does: '복직근 최하부 앞의 작은 삼각형 근육입니다. 백선을 긴장시키며 약 5분의 1의 사람에게는 아예 없습니다.',
          sci: '복직근초 내, 하부 복직근 전면의 작은 삼각근. 백선을 긴장시키며 약 20%에서 결손됩니다.' },
    origin: { en: 'Pubic crest and pubic symphysis', ko: '치골능 및 치골결합' },
    insertion: { en: 'Linea alba, below the umbilicus', ko: '배꼽 아래 백선' },
    innervation: { nerves: { en: 'Subcostal nerve', ko: '늑하신경' }, roots: ['T12'] },
    actions: { en: 'Tenses the linea alba', ko: '백선 긴장' },
    synergists: ['rectus abdominis'],
    antagonists: [],
  },

  /* ------------------------------------------------------------ shoulder girdle */

  'rhomboid major': {
    latin: 'Musculus rhomboideus major',
    en: { name: 'Rhomboid major',
          does: 'Runs from the spine down and out to the inner edge of the shoulder blade. It draws the shoulder blades together and tips the socket downward.',
          sci: 'Scapular retractor from T2–T5 spinous processes to the medial scapular border below the spine. Retraction with downward rotation and elevation of the medial border.' },
    ko: { name: '대능형근',
          does: '척추에서 아래·바깥으로 견갑골 안쪽 모서리까지 이어집니다. 견갑골을 모으고 관절와를 아래로 기울입니다.',
          sci: 'T2–T5 극돌기에서 견갑극 아래 견갑골 내측연으로 가는 견갑 후인근. 후인과 하방회전, 내측연 거상을 담당합니다.' },
    origin: { en: 'Spinous processes of T2–T5', ko: 'T2–T5 극돌기' },
    insertion: { en: 'Medial border of the scapula below the spine of the scapula', ko: '견갑극 아래 견갑골 내측연' },
    innervation: { nerves: { en: 'Dorsal scapular nerve', ko: '견갑배신경' }, roots: ['C4', 'C5'] },
    actions: { en: 'Scapular retraction, downward rotation, elevation', ko: '견갑골 후인, 하방회전, 거상' },
    synergists: ['rhomboid minor', 'levator scapulae', 'trapezius'],
    antagonists: ['serratus anterior', 'pectoralis minor'],
  },

  'rhomboid minor': {
    latin: 'Musculus rhomboideus minor',
    en: { name: 'Rhomboid minor',
          does: 'The smaller band just above rhomboid major, doing the same job at the level of the scapular spine.',
          sci: 'Superior rhomboid from C7–T1 spinous processes to the medial scapular border at the root of the spine. Retraction and downward rotation.' },
    ko: { name: '소능형근',
          does: '대능형근 바로 위의 작은 띠로, 견갑극 높이에서 같은 일을 합니다.',
          sci: 'C7–T1 극돌기에서 견갑극 기시부의 견갑골 내측연으로 가는 상부 능형근. 후인과 하방회전을 담당합니다.' },
    origin: { en: 'Spinous processes of C7 and T1', ko: 'C7–T1 극돌기' },
    insertion: { en: 'Medial border of the scapula at the root of the spine', ko: '견갑극 기시부의 견갑골 내측연' },
    innervation: { nerves: { en: 'Dorsal scapular nerve', ko: '견갑배신경' }, roots: ['C4', 'C5'] },
    actions: { en: 'Scapular retraction and downward rotation', ko: '견갑골 후인 및 하방회전' },
    synergists: ['rhomboid major', 'trapezius'],
    antagonists: ['serratus anterior'],
  },

  'levator scapulae': {
    latin: 'Musculus levator scapulae',
    en: { name: 'Levator scapulae',
          does: 'From the side of the neck to the top corner of the shoulder blade. It lifts the shoulder blade and is the muscle that aches when shoulders live up around the ears.',
          sci: 'From the transverse processes of C1–C4 to the superior angle of the scapula. Scapular elevation and downward rotation; with the scapula fixed, ipsilateral cervical lateral flexion and rotation.' },
    ko: { name: '견갑거근',
          does: '목 옆에서 견갑골 위쪽 모서리까지 이어집니다. 견갑골을 들어 올리며, 어깨가 귀 근처에 머무를 때 뻐근해지는 근육입니다.',
          sci: 'C1–C4 횡돌기에서 견갑골 상각으로 이어집니다. 견갑골 거상과 하방회전을 담당하고, 견갑골이 고정되면 동측 경추 측굴·회전을 만듭니다.' },
    origin: { en: 'Transverse processes of C1–C4', ko: 'C1–C4 횡돌기' },
    insertion: { en: 'Superior angle and upper medial border of the scapula', ko: '견갑골 상각 및 상부 내측연' },
    innervation: { nerves: { en: 'Dorsal scapular nerve and branches of C3–C4', ko: '견갑배신경 및 C3–C4 분지' },
                   roots: ['C3', 'C4', 'C5'] },
    actions: { en: 'Scapular elevation and downward rotation; cervical lateral flexion', ko: '견갑골 거상 및 하방회전, 경추 측굴' },
    synergists: ['trapezius', 'rhomboid major'],
    antagonists: ['serratus anterior', 'latissimus dorsi'],
  },

  'pectoralis minor': {
    latin: 'Musculus pectoralis minor',
    en: { name: 'Pectoralis minor',
          does: 'A small muscle under pectoralis major, from the ribs to the front hook of the shoulder blade. When it is short it tips the shoulder blade forward, which is what a rounded-shoulder posture looks like from the inside.',
          sci: 'From ribs 3–5 to the coracoid process. Protraction, depression and anterior tilt of the scapula; shortening is associated with reduced subacromial space and altered scapulohumeral rhythm.' },
    ko: { name: '소흉근',
          does: '대흉근 아래의 작은 근육으로 갈비뼈에서 견갑골 앞 갈고리까지 이어집니다. 짧아지면 견갑골을 앞으로 기울이며, 이것이 둥근 어깨 자세의 안쪽 모습입니다.',
          sci: '제3–5늑골에서 오훼돌기로 이어집니다. 견갑골 전인·하강·전방경사를 담당하며, 단축은 견봉하 공간 감소 및 견갑상완 리듬 변화와 연관됩니다.' },
    origin: { en: 'Anterior surfaces of ribs 3–5', ko: '제3–5늑골 전면' },
    insertion: { en: 'Coracoid process of the scapula', ko: '견갑골 오훼돌기' },
    innervation: { nerves: { en: 'Medial pectoral nerve', ko: '내측흉근신경' }, roots: ['C8', 'T1'] },
    actions: { en: 'Scapular protraction, depression and anterior tilt; accessory inspiration', ko: '견갑골 전인·하강·전방경사, 보조 흡기' },
    synergists: ['serratus anterior'],
    antagonists: ['trapezius', 'rhomboid major'],
  },

  'supraspinatus': {
    latin: 'Musculus supraspinatus',
    en: { name: 'Supraspinatus',
          does: 'Sits in the hollow above the spine of the shoulder blade and starts the arm lifting away from the body. It also pulls the head of the arm bone into the socket, which is the rotator cuff’s real job.',
          sci: 'Rotator cuff. Initiates glenohumeral abduction and provides a compressive, centring force on the humeral head throughout elevation. The commonest site of rotator cuff tear.' },
    ko: { name: '극상근',
          does: '견갑극 위 오목한 곳에 있으며 팔을 몸에서 벌리는 동작을 시작합니다. 상완골두를 관절와로 눌러 넣는 일도 하며, 그것이 회전근개의 본래 역할입니다.',
          sci: '회전근개. 견관절 외전을 개시하고 거상 전 구간에서 상완골두에 압박·중심화 힘을 제공합니다. 회전근개 파열의 가장 흔한 부위입니다.' },
    origin: { en: 'Supraspinous fossa of the scapula', ko: '견갑골 극상와' },
    insertion: { en: 'Superior facet of the greater tubercle of the humerus', ko: '상완골 대결절 상면' },
    innervation: { nerves: { en: 'Suprascapular nerve', ko: '견갑상신경' }, roots: ['C5', 'C6'] },
    actions: { en: 'Glenohumeral abduction; humeral head centring', ko: '견관절 외전, 상완골두 중심화' },
    synergists: ['deltoid', 'infraspinatus muscle', 'subscapularis'],
    antagonists: ['latissimus dorsi', 'pectoralis major'],
  },

  'subscapularis': {
    latin: 'Musculus subscapularis',
    en: { name: 'Subscapularis',
          does: 'The rotator cuff muscle on the front of the shoulder blade, between it and the ribs. It turns the arm inward and is the main check against the shoulder sliding forward.',
          sci: 'Only anterior rotator cuff muscle, filling the subscapular fossa. Internal rotation and the principal dynamic anterior restraint of the glenohumeral joint.' },
    ko: { name: '견갑하근',
          does: '견갑골 앞면, 갈비뼈와의 사이에 있는 회전근개입니다. 팔을 안으로 돌리며 어깨가 앞으로 미끄러지는 것을 막는 주된 제동입니다.',
          sci: '견갑하와를 채우는 유일한 전방 회전근개. 내회전을 담당하며 견관절의 주된 동적 전방 제동입니다.' },
    origin: { en: 'Subscapular fossa on the costal surface of the scapula', ko: '견갑골 늑골면의 견갑하와' },
    insertion: { en: 'Lesser tubercle of the humerus', ko: '상완골 소결절' },
    innervation: { nerves: { en: 'Upper and lower subscapular nerves', ko: '상·하 견갑하신경' }, roots: ['C5', 'C6', 'C7'] },
    actions: { en: 'Humeral internal rotation; anterior glenohumeral stability', ko: '상완골 내회전, 견관절 전방 안정' },
    synergists: ['pectoralis major', 'latissimus dorsi', 'teres major'],
    antagonists: ['infraspinatus muscle', 'teres minor'],
  },

  'teres minor': {
    latin: 'Musculus teres minor',
    en: { name: 'Teres minor',
          does: 'The small rotator cuff muscle below infraspinatus. It turns the arm outward and pulls the head of the humerus downward as the arm rises, which is what keeps it from jamming under the acromion.',
          sci: 'Rotator cuff. External rotation with an inferior glide moment on the humeral head during elevation, resisting superior migration.' },
    ko: { name: '소원근',
          does: '극하근 아래의 작은 회전근개입니다. 팔을 바깥으로 돌리고 팔을 들 때 상완골두를 아래로 당겨, 견봉 아래에 끼이지 않게 합니다.',
          sci: '회전근개. 외회전을 담당하며 거상 시 상완골두에 하방 활주 모멘트를 만들어 상방 이동에 저항합니다.' },
    origin: { en: 'Upper two-thirds of the lateral border of the scapula', ko: '견갑골 외측연 상부 2/3' },
    insertion: { en: 'Inferior facet of the greater tubercle of the humerus', ko: '상완골 대결절 하면' },
    innervation: { nerves: { en: 'Axillary nerve', ko: '액와신경' }, roots: ['C5', 'C6'] },
    actions: { en: 'Humeral external rotation; inferior glide during elevation', ko: '상완골 외회전, 거상 시 하방 활주' },
    synergists: ['infraspinatus muscle', 'deltoid'],
    antagonists: ['subscapularis', 'pectoralis major'],
  },

  'teres major': {
    latin: 'Musculus teres major',
    en: { name: 'Teres major',
          does: 'From the bottom corner of the shoulder blade to the front of the arm bone. It is not a rotator cuff muscle: it works with latissimus dorsi to pull the arm down and back.',
          sci: 'Not part of the rotator cuff. Adduction, extension and internal rotation of the humerus, functionally paired with latissimus dorsi.' },
    ko: { name: '대원근',
          does: '견갑골 아래 모서리에서 상완골 앞쪽까지 이어집니다. 회전근개가 아니며, 광배근과 함께 팔을 아래·뒤로 당깁니다.',
          sci: '회전근개에 속하지 않습니다. 상완골 내전·신전·내회전을 담당하며 광배근과 기능적으로 짝을 이룹니다.' },
    origin: { en: 'Inferior angle and lower lateral border of the scapula', ko: '견갑골 하각 및 외측연 하부' },
    insertion: { en: 'Medial lip of the intertubercular groove of the humerus', ko: '상완골 결절간구 내측순' },
    innervation: { nerves: { en: 'Lower subscapular nerve', ko: '하견갑하신경' }, roots: ['C5', 'C6', 'C7'] },
    actions: { en: 'Humeral adduction, extension and internal rotation', ko: '상완골 내전·신전·내회전' },
    synergists: ['latissimus dorsi', 'subscapularis'],
    antagonists: ['deltoid', 'supraspinatus'],
  },

  'coracobrachialis': {
    latin: 'Musculus coracobrachialis',
    en: { name: 'Coracobrachialis',
          does: 'A slender muscle from the coracoid process down the inside of the upper arm. It flexes and adducts the shoulder, and the musculocutaneous nerve pierces it on its way down.',
          sci: 'From the coracoid process to the medial humeral shaft. Glenohumeral flexion and adduction; pierced by the musculocutaneous nerve.' },
    ko: { name: '오훼완근',
          does: '오훼돌기에서 위팔 안쪽으로 내려가는 가느다란 근육입니다. 어깨를 굽히고 모으며, 근피신경이 이 근육을 관통해 내려갑니다.',
          sci: '오훼돌기에서 상완골 내측면으로 이어집니다. 견관절 굴곡과 내전을 담당하며 근피신경이 관통합니다.' },
    origin: { en: 'Coracoid process of the scapula', ko: '견갑골 오훼돌기' },
    insertion: { en: 'Middle of the medial surface of the humeral shaft', ko: '상완골간 내측면 중앙' },
    innervation: { nerves: { en: 'Musculocutaneous nerve', ko: '근피신경' }, roots: ['C5', 'C6', 'C7'] },
    actions: { en: 'Shoulder flexion and adduction', ko: '어깨 굴곡 및 내전' },
    synergists: ['pectoralis major', 'biceps brachii'],
    antagonists: ['latissimus dorsi', 'deltoid'],
  },

  /* ------------------------------------------------------------------------ arm */

  'biceps brachii': {
    latin: 'Musculus biceps brachii',
    en: { name: 'Biceps brachii',
          does: 'Crosses both the shoulder and the elbow with two heads. It bends the elbow, but it is a stronger supinator than flexor — it is the muscle that turns a screwdriver.',
          sci: 'Two-headed muscle crossing shoulder and elbow. Most powerful supinator of the forearm and a strong elbow flexor, maximally effective with the elbow near 90°; the long head contributes to glenohumeral stability.' },
    ko: { name: '상완이두근',
          does: '두 개의 갈래로 어깨와 팔꿈치를 모두 넘습니다. 팔꿈치를 굽히지만 굴곡보다 회외에 더 강하며, 드라이버를 돌리는 근육입니다.',
          sci: '어깨와 팔꿈치를 넘는 두갈래근. 전완의 가장 강한 회외근이자 강한 주관절 굴곡근으로 팔꿈치 90도 부근에서 효율이 최대입니다. 장두는 견관절 안정에 기여합니다.' },
    origin: { en: 'Long head from the supraglenoid tubercle; short head from the coracoid process',
              ko: '장두: 관절상결절, 단두: 오훼돌기' },
    insertion: { en: 'Radial tuberosity and, via the bicipital aponeurosis, the forearm fascia', ko: '요골조면 및 이두건막을 통한 전완근막' },
    innervation: { nerves: { en: 'Musculocutaneous nerve', ko: '근피신경' }, roots: ['C5', 'C6'] },
    actions: { en: 'Forearm supination, elbow flexion, weak shoulder flexion', ko: '전완 회외, 주관절 굴곡, 약한 어깨 굴곡' },
    synergists: ['brachialis', 'brachioradialis', 'supinator'],
    antagonists: ['triceps brachii', 'anconeus'],
  },

  'triceps brachii': {
    latin: 'Musculus triceps brachii',
    en: { name: 'Triceps brachii',
          does: 'The back of the upper arm, in three heads. It straightens the elbow, and its long head also pulls the arm backward because it crosses the shoulder as well.',
          sci: 'Sole significant elbow extensor. The long head crosses the glenohumeral joint and contributes to shoulder extension and adduction; the medial head is the workhorse at low loads.' },
    ko: { name: '상완삼두근',
          does: '위팔 뒤쪽의 세 갈래 근육입니다. 팔꿈치를 펴며, 장두는 어깨도 넘기 때문에 팔을 뒤로 당깁니다.',
          sci: '유일한 주요 주관절 신전근. 장두는 견관절을 넘어 어깨 신전·내전에 기여하며, 낮은 부하에서는 내측두가 주로 작동합니다.' },
    origin: { en: 'Long head from the infraglenoid tubercle; lateral and medial heads from the posterior humerus',
              ko: '장두: 관절하결절, 외측두·내측두: 상완골 후면' },
    insertion: { en: 'Olecranon of the ulna', ko: '척골 주두' },
    innervation: { nerves: { en: 'Radial nerve', ko: '요골신경' }, roots: ['C6', 'C7', 'C8'] },
    actions: { en: 'Elbow extension; shoulder extension and adduction from the long head', ko: '주관절 신전, 장두의 어깨 신전·내전' },
    synergists: ['anconeus', 'latissimus dorsi'],
    antagonists: ['biceps brachii', 'brachialis'],
  },

  'brachialis': {
    latin: 'Musculus brachialis',
    en: { name: 'Brachialis',
          does: 'Lies underneath biceps and crosses only the elbow. It is the true workhorse of elbow bending, and unlike biceps its pull does not change with forearm rotation.',
          sci: 'Pure elbow flexor inserting on the ulnar tuberosity, so its moment arm is independent of forearm rotation. The principal flexor by cross-sectional area.' },
    ko: { name: '상완근',
          does: '이두근 아래에 있으며 팔꿈치만 넘습니다. 팔꿈치 굴곡의 실질적 주역이며, 이두근과 달리 전완 회전에 따라 힘이 달라지지 않습니다.',
          sci: '척골조면에 정지하는 순수 주관절 굴곡근으로 모멘트암이 전완 회전과 무관합니다. 단면적 기준 주 굴곡근입니다.' },
    origin: { en: 'Distal half of the anterior humerus', ko: '상완골 전면 원위 1/2' },
    insertion: { en: 'Ulnar tuberosity and coronoid process', ko: '척골조면 및 구상돌기' },
    innervation: { nerves: { en: 'Musculocutaneous nerve, with a radial contribution', ko: '근피신경, 요골신경 기여' },
                   roots: ['C5', 'C6', 'C7'] },
    actions: { en: 'Elbow flexion', ko: '주관절 굴곡' },
    synergists: ['biceps brachii', 'brachioradialis'],
    antagonists: ['triceps brachii'],
  },

  'brachioradialis': {
    latin: 'Musculus brachioradialis',
    en: { name: 'Brachioradialis',
          does: 'The ridge that stands up on the forearm when you lift something with the thumb pointing up. It bends the elbow best in that mid-rotated position.',
          sci: 'Radial-nerve-supplied elbow flexor despite lying in the anterior compartment. Most effective in neutral forearm rotation; also returns the forearm toward neutral from either extreme.' },
    ko: { name: '완요골근',
          does: '엄지를 위로 향한 채 무언가를 들 때 전완에 도드라지는 능선입니다. 그 중립 회전 위치에서 팔꿈치 굴곡에 가장 효율적입니다.',
          sci: '전방구획에 있으면서도 요골신경 지배를 받는 주관절 굴곡근. 전완 중립 회전에서 가장 효율적이며 양극단에서 중립으로 되돌립니다.' },
    origin: { en: 'Lateral supracondylar ridge of the humerus', ko: '상완골 외측 과상능' },
    insertion: { en: 'Lateral surface of the distal radius above the styloid process', ko: '요골 경상돌기 위 원위 외측면' },
    innervation: { nerves: { en: 'Radial nerve', ko: '요골신경' }, roots: ['C5', 'C6'] },
    actions: { en: 'Elbow flexion in neutral rotation', ko: '중립 회전에서의 주관절 굴곡' },
    synergists: ['biceps brachii', 'brachialis'],
    antagonists: ['triceps brachii'],
  },

  'anconeus': {
    latin: 'Musculus anconeus',
    en: { name: 'Anconeus',
          does: 'A small triangle on the outside of the elbow, continuous with triceps. It assists extension and steadies the joint as the ulna rotates slightly.',
          sci: 'Small extensor continuous with the triceps. Assists elbow extension and stabilises the ulna during pronation and supination.' },
    ko: { name: '주근',
          does: '팔꿈치 바깥의 작은 삼각형으로 삼두근과 연속됩니다. 신전을 보조하고 척골이 미세하게 회전할 때 관절을 안정시킵니다.',
          sci: '삼두근과 연속된 작은 신전근. 주관절 신전을 보조하고 회내·회외 시 척골을 안정시킵니다.' },
    origin: { en: 'Lateral epicondyle of the humerus', ko: '상완골 외측상과' },
    insertion: { en: 'Lateral olecranon and proximal posterior ulna', ko: '주두 외측 및 근위 척골 후면' },
    innervation: { nerves: { en: 'Radial nerve', ko: '요골신경' }, roots: ['C7', 'C8'] },
    actions: { en: 'Elbow extension; ulnar stabilisation', ko: '주관절 신전, 척골 안정화' },
    synergists: ['triceps brachii'],
    antagonists: ['biceps brachii'],
  },

  'flexor carpi ulnaris': {
    latin: 'Musculus flexor carpi ulnaris',
    en: { name: 'Flexor carpi ulnaris',
          does: 'Bends the wrist toward the little-finger side. In a weight-bearing yoga pose it is part of what stops the wrist collapsing outward.',
          sci: 'Superficial flexor compartment. Wrist flexion with ulnar deviation; the only forearm flexor supplied by the ulnar nerve.' },
    ko: { name: '척측수근굴근',
          does: '손목을 새끼손가락 쪽으로 굽힙니다. 체중을 싣는 요가 자세에서 손목이 바깥으로 무너지는 것을 막는 요소입니다.',
          sci: '표층 굴곡구획. 손목 굴곡과 척측 편위를 담당하며, 전완 굴곡근 중 유일하게 척골신경의 지배를 받습니다.' },
    origin: { en: 'Medial epicondyle and the olecranon and posterior ulna', ko: '내측상과, 주두 및 척골 후면' },
    insertion: { en: 'Pisiform, hook of hamate and base of the fifth metacarpal', ko: '두상골, 유구골구, 제5중수골 기저' },
    innervation: { nerves: { en: 'Ulnar nerve', ko: '척골신경' }, roots: ['C7', 'C8', 'T1'] },
    actions: { en: 'Wrist flexion and ulnar deviation', ko: '손목 굴곡 및 척측 편위' },
    synergists: ['flexor carpi radialis', 'palmaris longus'],
    antagonists: ['extensor carpi radialis longus'],
  },

  'flexor carpi radialis': {
    latin: 'Musculus flexor carpi radialis',
    en: { name: 'Flexor carpi radialis',
          does: 'Bends the wrist toward the thumb side. Its tendon is the landmark next to the pulse at the wrist.',
          sci: 'Superficial flexor compartment. Wrist flexion with radial deviation; its tendon is the medial landmark to the radial artery at the wrist.' },
    ko: { name: '요측수근굴근',
          does: '손목을 엄지 쪽으로 굽힙니다. 손목에서 맥박 옆으로 만져지는 힘줄이 이것입니다.',
          sci: '표층 굴곡구획. 손목 굴곡과 요측 편위를 담당하며, 손목에서 요골동맥의 내측 지표가 됩니다.' },
    origin: { en: 'Medial epicondyle of the humerus', ko: '상완골 내측상과' },
    insertion: { en: 'Bases of the second and third metacarpals', ko: '제2–3중수골 기저' },
    innervation: { nerves: { en: 'Median nerve', ko: '정중신경' }, roots: ['C6', 'C7'] },
    actions: { en: 'Wrist flexion and radial deviation', ko: '손목 굴곡 및 요측 편위' },
    synergists: ['flexor carpi ulnaris', 'palmaris longus'],
    antagonists: ['extensor carpi radialis brevis'],
  },

  'extensor carpi radialis longus': {
    latin: 'Musculus extensor carpi radialis longus',
    en: { name: 'Extensor carpi radialis longus',
          does: 'Straightens the wrist and pulls it toward the thumb. It is loaded hard in every hand-supported pose, which is why wrists complain in plank and downward dog.',
          sci: 'Posterior compartment wrist extensor. Extension with radial deviation; heavily loaded in closed-chain wrist extension, where it works isometrically against body weight.' },
    ko: { name: '장요측수근신근',
          does: '손목을 펴고 엄지 쪽으로 당깁니다. 손으로 지지하는 모든 자세에서 크게 부하를 받으며, 플랭크와 다운독에서 손목이 불편해지는 이유입니다.',
          sci: '후방구획 손목 신전근. 신전과 요측 편위를 담당하며, 폐쇄사슬 손목 신전에서 체중에 대해 등척성으로 크게 부하를 받습니다.' },
    origin: { en: 'Lateral supracondylar ridge of the humerus', ko: '상완골 외측 과상능' },
    insertion: { en: 'Base of the second metacarpal', ko: '제2중수골 기저' },
    innervation: { nerves: { en: 'Radial nerve', ko: '요골신경' }, roots: ['C6', 'C7'] },
    actions: { en: 'Wrist extension and radial deviation', ko: '손목 신전 및 요측 편위' },
    synergists: ['extensor carpi radialis brevis', 'extensor digitorum'],
    antagonists: ['flexor carpi radialis'],
  },

  'extensor carpi radialis brevis': {
    latin: 'Musculus extensor carpi radialis brevis',
    en: { name: 'Extensor carpi radialis brevis',
          does: 'The shorter wrist extensor, attaching at the outside of the elbow. Its origin is the classic site of tennis elbow.',
          sci: 'Common extensor origin at the lateral epicondyle; the principal site of lateral epicondylalgia. Wrist extension with slight radial deviation.' },
    ko: { name: '단요측수근신근',
          does: '팔꿈치 바깥에 붙는 짧은 손목 신전근입니다. 그 기시부가 테니스 엘보의 전형적인 부위입니다.',
          sci: '외측상과의 총신전근 기시부로 외측상과통의 주된 부위입니다. 손목 신전과 약간의 요측 편위를 담당합니다.' },
    origin: { en: 'Lateral epicondyle via the common extensor origin', ko: '총신전근건을 통한 외측상과' },
    insertion: { en: 'Base of the third metacarpal', ko: '제3중수골 기저' },
    innervation: { nerves: { en: 'Radial nerve, deep branch', ko: '요골신경 심지' }, roots: ['C7', 'C8'] },
    actions: { en: 'Wrist extension', ko: '손목 신전' },
    synergists: ['extensor carpi radialis longus', 'extensor digitorum'],
    antagonists: ['flexor carpi radialis'],
  },

  /* ------------------------------------------------------------------------ neck */

  'splenius capitis': {
    latin: 'Musculus splenius capitis',
    en: { name: 'Splenius capitis',
          does: 'A strap running up and out from the upper spine to the base of the skull. Working on one side it turns the head to the same side; on both sides it extends the neck.',
          sci: 'Superficial posterior cervical muscle. Unilaterally, ipsilateral cervical rotation and lateral flexion; bilaterally, cervical and head extension.' },
    ko: { name: '두판상근',
          does: '위쪽 척추에서 두개골 기저로 위·바깥으로 달리는 띠입니다. 한쪽만 작용하면 같은 쪽으로 고개를 돌리고, 양쪽이 함께 작용하면 목을 폅니다.',
          sci: '표층 후경부 근육. 편측 작용 시 동측 경추 회전과 측굴, 양측 작용 시 경추 및 두부 신전을 만듭니다.' },
    origin: { en: 'Ligamentum nuchae and spinous processes of C7–T3', ko: '항인대 및 C7–T3 극돌기' },
    insertion: { en: 'Mastoid process and lateral superior nuchal line', ko: '유양돌기 및 상항선 외측' },
    innervation: { nerves: { en: 'Posterior rami of middle cervical spinal nerves', ko: '중부 경추 척수신경 후지' },
                   roots: ['C3', 'C4', 'C5'] },
    actions: { en: 'Head and neck extension; ipsilateral rotation and lateral flexion', ko: '두경부 신전, 동측 회전 및 측굴' },
    synergists: ['semispinalis capitis', 'trapezius', 'levator scapulae'],
    antagonists: ['sternocleidomastoid', 'longus colli'],
  },

  'semispinalis capitis': {
    latin: 'Musculus semispinalis capitis',
    en: { name: 'Semispinalis capitis',
          does: 'A thick column either side of the back of the neck running straight up to the skull. It is the main extensor of the head and the muscle most loaded by a forward head position.',
          sci: 'Principal extensor of the head, running vertically from thoracic and cervical transverse processes to the occiput. Sustained loading in forward head posture is a common source of cervicogenic symptoms.' },
    ko: { name: '두반극근',
          does: '목 뒤 양옆에서 두개골까지 곧게 올라가는 두꺼운 기둥입니다. 머리의 주된 신전근이며 거북목 자세에서 가장 크게 부하를 받는 근육입니다.',
          sci: '흉추·경추 횡돌기에서 후두골로 수직 주행하는 두부의 주 신전근. 전방두부자세에서의 지속 부하는 경인성 증상의 흔한 원인입니다.' },
    origin: { en: 'Transverse processes of C7–T6 and articular processes of C4–C6', ko: 'C7–T6 횡돌기 및 C4–C6 관절돌기' },
    insertion: { en: 'Between the superior and inferior nuchal lines of the occipital bone', ko: '후두골 상·하항선 사이' },
    innervation: { nerves: { en: 'Posterior rami of cervical spinal nerves, including the greater occipital nerve',
                             ko: '경추 척수신경 후지, 대후두신경 포함' },
                   roots: ['C1', 'C2', 'C3', 'C4', 'C5'] },
    actions: { en: 'Head extension; contralateral rotation', ko: '두부 신전, 반대측 회전' },
    synergists: ['splenius capitis', 'trapezius'],
    antagonists: ['longus capitis', 'sternocleidomastoid'],
  },

  'longus colli': {
    latin: 'Musculus longus colli',
    en: { name: 'Longus colli',
          does: 'A deep muscle on the front of the cervical spine, the neck’s equivalent of the deep abdominals. It flattens the neck curve and holds the head over the ribcage rather than in front of it.',
          sci: 'Deep cervical flexor on the anterior vertebral bodies. Produces cervical flexion with segmental support; delayed or reduced activity is the hallmark finding in neck-pain populations, with compensatory sternocleidomastoid over-activity.' },
    ko: { name: '경장근',
          does: '경추 앞면의 심부 근육이며 목의 심부 복부근에 해당합니다. 목의 곡선을 펴고 머리가 흉곽 앞이 아니라 그 위에 놓이게 잡아 줍니다.',
          sci: '추체 전면의 심부 경부 굴곡근. 분절 지지를 동반한 경추 굴곡을 만듭니다. 경부 통증군에서 활성 지연·감소와 흉쇄유돌근 과활성이 특징적 소견입니다.' },
    origin: { en: 'Anterior bodies and transverse processes of C3–T3', ko: 'C3–T3 추체 전면 및 횡돌기' },
    insertion: { en: 'Anterior tubercle of the atlas and bodies of C2–C4', ko: '환추 전결절 및 C2–C4 추체' },
    innervation: { nerves: { en: 'Anterior rami of cervical spinal nerves', ko: '경추 척수신경 전지' },
                   roots: ['C2', 'C3', 'C4', 'C5', 'C6'] },
    actions: { en: 'Cervical flexion and segmental support', ko: '경추 굴곡 및 분절 지지' },
    synergists: ['longus capitis', 'scalenus anterior'],
    antagonists: ['semispinalis capitis', 'splenius capitis'],
  },

  'longus capitis': {
    latin: 'Musculus longus capitis',
    en: { name: 'Longus capitis',
          does: 'Runs from the neck vertebrae to the base of the skull in front. It nods the head — the small "yes" movement that a chin tuck asks for.',
          sci: 'Deep cervical flexor from the C3–C6 transverse processes to the basilar occiput. Produces craniocervical flexion, the movement targeted by the chin-tuck test and retraining.' },
    ko: { name: '두장근',
          does: '경추에서 두개골 앞쪽 기저까지 이어집니다. 머리를 끄덕이게 하며, 턱 당기기가 요구하는 작은 "예" 동작입니다.',
          sci: 'C3–C6 횡돌기에서 후두골 기저부로 가는 심부 경부 굴곡근. 두경부 굴곡을 만들며 턱 당기기 검사와 재훈련의 표적입니다.' },
    origin: { en: 'Anterior tubercles of the transverse processes of C3–C6', ko: 'C3–C6 횡돌기 전결절' },
    insertion: { en: 'Basilar part of the occipital bone', ko: '후두골 기저부' },
    innervation: { nerves: { en: 'Anterior rami of C1–C3', ko: 'C1–C3 전지' }, roots: ['C1', 'C2', 'C3'] },
    actions: { en: 'Craniocervical flexion', ko: '두경부 굴곡' },
    synergists: ['longus colli'],
    antagonists: ['semispinalis capitis', 'rectus capitis posterior major'],
  },

  'scalenus anterior': {
    latin: 'Musculus scalenus anterior',
    en: { name: 'Scalenus anterior',
          does: 'From the neck vertebrae down to the first rib. It lifts the first rib when you breathe in hard, and the brachial plexus and subclavian artery pass right behind it.',
          sci: 'Accessory inspiratory muscle elevating the first rib; also produces ipsilateral cervical lateral flexion. Forms the anterior boundary of the interscalene triangle through which the brachial plexus and subclavian artery pass.' },
    ko: { name: '전사각근',
          does: '경추에서 제1늑골까지 이어집니다. 힘껏 들이쉴 때 제1늑골을 들어 올리며, 그 바로 뒤로 상완신경총과 쇄골하동맥이 지나갑니다.',
          sci: '제1늑골을 거상하는 보조 흡기근이며 동측 경추 측굴을 만듭니다. 상완신경총과 쇄골하동맥이 지나는 사각근간 삼각의 전방 경계를 이룹니다.' },
    origin: { en: 'Anterior tubercles of the transverse processes of C3–C6', ko: 'C3–C6 횡돌기 전결절' },
    insertion: { en: 'Scalene tubercle of the first rib', ko: '제1늑골 사각근결절' },
    innervation: { nerves: { en: 'Anterior rami of C4–C6', ko: 'C4–C6 전지' }, roots: ['C4', 'C5', 'C6'] },
    actions: { en: 'First rib elevation; ipsilateral cervical lateral flexion', ko: '제1늑골 거상, 동측 경추 측굴' },
    synergists: ['scalenus medius', 'sternocleidomastoid', 'external intercostal muscle'],
    antagonists: ['internal intercostal muscle'],
  },

  'scalenus medius': {
    latin: 'Musculus scalenus medius',
    en: { name: 'Scalenus medius',
          does: 'The largest of the three scalenes, behind the nerve bundle to the arm. It also lifts the first rib on a hard inhale.',
          sci: 'Largest scalene, forming the posterior boundary of the interscalene triangle. Elevates the first rib in forced inspiration and laterally flexes the cervical spine.' },
    ko: { name: '중사각근',
          does: '세 사각근 중 가장 크며 팔로 가는 신경다발 뒤에 있습니다. 힘껏 들이쉴 때 제1늑골을 함께 들어 올립니다.',
          sci: '가장 큰 사각근으로 사각근간 삼각의 후방 경계를 이룹니다. 강제 흡기 시 제1늑골을 거상하고 경추를 측굴시킵니다.' },
    origin: { en: 'Posterior tubercles of the transverse processes of C2–C7', ko: 'C2–C7 횡돌기 후결절' },
    insertion: { en: 'Superior surface of the first rib behind the subclavian groove', ko: '쇄골하구 뒤 제1늑골 상면' },
    innervation: { nerves: { en: 'Anterior rami of C3–C8', ko: 'C3–C8 전지' }, roots: ['C3', 'C4', 'C5', 'C6', 'C7'] },
    actions: { en: 'First rib elevation; cervical lateral flexion', ko: '제1늑골 거상, 경추 측굴' },
    synergists: ['scalenus anterior', 'scalenus posterior'],
    antagonists: ['internal intercostal muscle'],
  },

  'rectus capitis posterior major': {
    latin: 'Musculus rectus capitis posterior major',
    en: { name: 'Rectus capitis posterior major',
          does: 'One of the four suboccipital muscles at the very top of the neck. They are tiny, extraordinarily densely innervated, and they are how the brain knows where the head is relative to the body.',
          sci: 'Suboccipital muscle from the spinous process of the axis to the occiput. Spindle density among the highest in the body; the suboccipital group functions primarily as a head-position sensor feeding the vestibulo-ocular and cervico-ocular reflexes.' },
    ko: { name: '대후두직근',
          does: '목 최상부 네 개의 후두하근 중 하나입니다. 아주 작지만 신경 분포가 극히 조밀하며, 뇌가 몸에 대한 머리의 위치를 아는 통로입니다.',
          sci: '축추 극돌기에서 후두골로 가는 후두하근. 근방추 밀도가 인체 최고 수준이며, 후두하근군은 전정안반사·경부안반사에 정보를 공급하는 머리 위치 감지기로 기능합니다.' },
    origin: { en: 'Spinous process of the axis', ko: '축추 극돌기' },
    insertion: { en: 'Lateral part of the inferior nuchal line of the occipital bone', ko: '후두골 하항선 외측부' },
    innervation: { nerves: { en: 'Suboccipital nerve', ko: '후두하신경' }, roots: ['C1'] },
    actions: { en: 'Head extension and ipsilateral rotation; craniocervical proprioception', ko: '두부 신전 및 동측 회전, 두경부 고유감각' },
    synergists: ['rectus capitis posterior minor', 'obliquus capitis inferior', 'semispinalis capitis'],
    antagonists: ['longus capitis'],
  },

  'obliquus capitis inferior': {
    latin: 'Musculus obliquus capitis inferior',
    en: { name: 'Obliquus capitis inferior',
          does: 'The suboccipital muscle that turns the atlas on the axis — the joint that provides half of all head rotation. It is the only one of the four that does not attach to the skull.',
          sci: 'Suboccipital muscle from the spinous process of the axis to the transverse process of the atlas. Produces ipsilateral atlantoaxial rotation, the joint responsible for roughly 50% of cervical axial rotation.' },
    ko: { name: '하두사근',
          does: '환추를 축추 위에서 돌리는 후두하근으로, 이 관절이 머리 회전의 절반을 담당합니다. 네 근육 중 유일하게 두개골에 붙지 않습니다.',
          sci: '축추 극돌기에서 환추 횡돌기로 가는 후두하근. 경추 축회전의 약 50%를 담당하는 환축관절의 동측 회전을 만듭니다.' },
    origin: { en: 'Spinous process of the axis', ko: '축추 극돌기' },
    insertion: { en: 'Transverse process of the atlas', ko: '환추 횡돌기' },
    innervation: { nerves: { en: 'Suboccipital nerve', ko: '후두하신경' }, roots: ['C1'] },
    actions: { en: 'Ipsilateral atlantoaxial rotation; craniocervical proprioception', ko: '동측 환축관절 회전, 두경부 고유감각' },
    synergists: ['rectus capitis posterior major', 'splenius capitis'],
    antagonists: ['longus colli'],
  },
};
