/**
 * MUSCLE_INFO — one entry per named muscle, keyed by the same base name the build emits
 * into src/generated/structures.json, which is where the region id comes from. Keying by
 * name rather than id means a rebuild that renumbers cannot silently detach the content
 * from the geometry; test/content.test.mjs checks every key resolves.
 *
 * Same dual-register shape as REGION_INFO: `does` is what you would say out loud, `sci` is
 * the same fact in clinical terms, `detail` is the collapsed clinician block. Every string
 * is en + ko.
 *
 * `innervation` carries nerve root levels because that is the anatomical bridge to the
 * nervous system: it is what lets a user click a muscle and travel up into the cord and
 * into the brain. Nothing else on the market does that traversal, and it is the whole
 * reason the roots are recorded rather than just the nerve name.
 *
 * Sources for attachments and innervation: Standring S (ed.), Gray's Anatomy 42nd ed.;
 * Moore KL, Clinically Oriented Anatomy 8th ed. Latin follows Terminologia Anatomica.
 */

import { MUSCLE_ATLAS } from './muscleAtlas.js';

const M = (o) => o;

/** The muscles the first exercises needed, written long. The rest are in muscleAtlas.js. */
const CORE = {
  'transversus abdominis': M({
    latin: 'Musculus transversus abdominis',
    en: { name: 'Transversus abdominis',
          does: 'The deepest abdominal layer. Its fibres run sideways like a belt, so when it shortens it narrows your waist rather than bending you. In healthy people it switches on a fraction of a second before you move a limb.',
          sci: 'Deepest of the anterolateral abdominal wall. Transverse fibre orientation; contraction increases intra-abdominal pressure and tensions the thoracolumbar fascia rather than producing trunk flexion.',
          feels: 'A quiet, low tightening below the navel that does not pull your ribs down. If your ribs move or you cannot talk, something bigger has taken over.' },
    ko: { name: '복횡근',
          does: '가장 깊은 복부 층입니다. 섬유가 벨트처럼 옆으로 달려서, 수축하면 몸을 굽히는 것이 아니라 허리둘레를 좁힙니다. 건강한 사람에서는 팔다리를 움직이기 직전에 먼저 켜집니다.',
          sci: '전외측 복벽의 최심층. 횡방향 섬유 주행으로, 수축 시 체간 굴곡이 아니라 복강내압 증가와 흉요근막 긴장을 만듭니다.',
          feels: '배꼽 아래가 조용히 조여드는 낮은 느낌이며, 갈비뼈가 아래로 당겨지지 않습니다. 갈비뼈가 움직이거나 말을 못 하면 더 큰 근육이 대신하고 있는 것입니다.' },
    origin: { en: 'Inner lip of iliac crest, thoracolumbar fascia, inner surfaces of costal cartilages 7–12, lateral third of inguinal ligament',
              ko: '장골능 내순, 흉요근막, 7–12번 늑연골 내면, 서혜인대 외측 1/3' },
    insertion: { en: 'Linea alba via the aponeurosis, pubic crest and pecten pubis',
                 ko: '건막을 통한 백선, 치골능 및 치골즐' },
    innervation: { nerves: { en: 'Thoracoabdominal (T7–T11), subcostal (T12), iliohypogastric and ilioinguinal (L1)',
                             ko: '흉복부신경 (T7–T11), 늑하신경 (T12), 장골하복·장골서혜신경 (L1)' },
                   roots: ['T7', 'T8', 'T9', 'T10', 'T11', 'T12', 'L1'] },
    actions: { en: 'Compresses the abdomen, raises intra-abdominal pressure, tensions thoracolumbar fascia',
               ko: '복부 압박, 복강내압 증가, 흉요근막 긴장' },
    synergists: ['internal oblique', 'diaphragm', 'multifidus'],
    antagonists: [],
    dysfunction: { en: 'Onset is delayed relative to limb movement in people with recurrent low back pain (Hodges & Richardson 1996). The delay is an association with pain, not a proven cause of it, and retraining the timing has not reliably beaten general exercise in trials.',
                   ko: '재발성 요통이 있는 사람에서 팔다리 움직임에 대한 활성 시점이 지연됩니다(Hodges & Richardson 1996). 이 지연은 통증과의 연관이지 입증된 원인이 아니며, 타이밍 재훈련이 일반 운동보다 우수하다는 결과는 일관되지 않습니다.' },
    evidence: 'apa_timing',
  }),

  'multifidus': M({
    latin: 'Musculus multifidus',
    en: { name: 'Multifidus',
          does: 'Short, thick muscles bridging two to four vertebrae at a time, packed into the groove either side of the spine. They control one joint at a time rather than moving the whole back, and they are thickest in the lower back.',
          sci: 'Deepest of the transversospinales. Spans 2–4 segments from transverse process to spinous process; provides segmental stiffness and contributes roughly two-thirds of the increase in lumbar segmental stiffness.',
          feels: 'Almost nothing, which is the difficulty. It is a deep steadiness low in the back rather than a squeeze you can find on purpose.' },
    ko: { name: '다열근',
          does: '척추 양옆 고랑에 채워져 두세 마디에서 네 마디씩 걸쳐 있는 짧고 두꺼운 근육입니다. 등 전체를 움직이기보다 한 번에 한 관절을 제어하며, 허리에서 가장 두껍습니다.',
          sci: '횡돌기극근 중 최심층. 횡돌기에서 극돌기까지 2–4분절을 연결하며 분절 강성을 제공하고, 요추 분절 강성 증가의 약 2/3를 담당합니다.',
          feels: '거의 느껴지지 않는다는 점이 어렵습니다. 일부러 조일 수 있는 감각이 아니라 허리 깊은 곳의 안정감입니다.' },
    origin: { en: 'Sacrum, erector spinae aponeurosis, mamillary processes of lumbar vertebrae, transverse processes of thoracic vertebrae',
              ko: '천골, 척주기립근 건막, 요추 유두돌기, 흉추 횡돌기' },
    insertion: { en: 'Spinous processes two to four segments above',
                 ko: '2–4분절 위쪽 극돌기' },
    innervation: { nerves: { en: 'Medial branches of the posterior rami of spinal nerves, segmentally',
                             ko: '척수신경 후지 내측분지, 분절별' },
                   roots: ['C3', 'T1', 'T6', 'L1', 'L3', 'L5', 'S1'] },
    actions: { en: 'Segmental stabilisation; small contributions to extension and contralateral rotation',
               ko: '분절 안정화, 신전 및 반대측 회전에 소폭 기여' },
    synergists: ['transversus abdominis', 'diaphragm', 'longissimus thoracis'],
    antagonists: ['rectus abdominis'],
    dysfunction: { en: 'Rapid, segment-specific atrophy on the painful side within days of a first episode of back pain, and it does not recover spontaneously when the pain settles (Hides et al. 1996).',
                   ko: '첫 요통 발생 후 며칠 내에 통증 쪽 해당 분절에서 빠르게 위축되며, 통증이 가라앉아도 자연 회복되지 않습니다(Hides 외, 1996).' },
    evidence: 'apa_timing',
  }),

  'diaphragm': M({
    latin: 'Diaphragma',
    en: { name: 'Diaphragm',
          does: 'The dome of muscle under your lungs. It is the main breathing muscle, and it is also part of the container that stabilises your trunk — which is why breath pattern is not decoration in Pilates but part of the mechanics.',
          sci: 'Musculotendinous septum between thoracic and abdominal cavities. Principal muscle of inspiration; also a postural muscle, co-activating tonically with transversus abdominis and pelvic floor to modulate intra-abdominal pressure.',
          feels: 'Ribs widening sideways and back on the inhale, without the chest lifting or the belly ballooning.' },
    ko: { name: '횡격막',
          does: '폐 아래의 돔 모양 근육입니다. 주된 호흡근이면서, 체간을 안정시키는 용기의 일부이기도 합니다. 필라테스에서 호흡 패턴이 장식이 아니라 역학의 일부인 이유입니다.',
          sci: '흉강과 복강 사이의 근건성 격막. 주 흡기근이자 자세근으로, 복횡근·골반저와 함께 긴장성으로 동시 활성화되어 복강내압을 조절합니다.',
          feels: '들이쉴 때 가슴이 들리거나 배가 부풀지 않으면서 갈비뼈가 옆과 뒤로 넓어지는 느낌.' },
    origin: { en: 'Xiphoid process, inner surfaces of costal cartilages 7–12, lumbar vertebrae via right and left crura',
              ko: '검상돌기, 7–12번 늑연골 내면, 좌·우 각을 통한 요추' },
    insertion: { en: 'Central tendon', ko: '중심건' },
    innervation: { nerves: { en: 'Phrenic nerve (C3, C4, C5) — "C3, 4, 5 keeps the diaphragm alive"',
                             ko: '횡격신경 (C3, C4, C5)' },
                   roots: ['C3', 'C4', 'C5'] },
    actions: { en: 'Inspiration; modulates intra-abdominal pressure for trunk stiffness',
               ko: '흡기, 체간 강성을 위한 복강내압 조절' },
    synergists: ['transversus abdominis', 'external intercostal muscle'],
    antagonists: [],
    dysfunction: { en: 'Under a postural challenge the diaphragm has to do two jobs at once; when breathing demand rises its postural contribution falls off, which is one reason held-breath bracing is not a strategy that scales.',
                   ko: '자세 부하가 걸리면 횡격막은 두 가지 일을 동시에 해야 합니다. 호흡 요구가 커지면 자세 기여가 줄어드는데, 숨을 참고 버티는 전략이 확장되지 않는 이유 중 하나입니다.' },
    evidence: 'interoception_breath',
  }),

  'rectus abdominis': M({
    latin: 'Musculus rectus abdominis',
    en: { name: 'Rectus abdominis',
          does: 'The long strap down the front of the abdomen — the one that shows as a "six pack". It bends you forward. It is a mover, not a stabiliser, and in most Pilates work it should be doing less than you expect.',
          sci: 'Paired vertical strap muscle within the rectus sheath, segmented by three or more tendinous intersections. Prime trunk flexor; poor segmental stabiliser because its line of action spans the whole lumbar spine.',
          feels: 'A hard ridge down the front, and the ribs pulling toward the pelvis. If this is the loudest thing you feel in a Hundred, the deep layer is not doing its share.' },
    ko: { name: '복직근',
          does: '복부 앞면을 세로로 지나는 긴 띠 근육으로, 이른바 "식스팩"입니다. 몸을 앞으로 굽힙니다. 안정근이 아니라 운동근이며, 대부분의 필라테스 동작에서는 예상보다 덜 일해야 합니다.',
          sci: '복직근초 내의 쌍을 이루는 수직 띠 근육으로 3개 이상의 건획으로 분절됩니다. 주된 체간 굴곡근이며, 작용선이 요추 전체를 가로지르므로 분절 안정화에는 부적합합니다.',
          feels: '앞면의 단단한 융기와 갈비뼈가 골반 쪽으로 당겨지는 느낌. 헌드레드에서 이것이 가장 크게 느껴진다면 심부층이 제 몫을 하지 않는 것입니다.' },
    origin: { en: 'Pubic crest and pubic symphysis', ko: '치골능 및 치골결합' },
    insertion: { en: 'Xiphoid process and costal cartilages 5–7', ko: '검상돌기 및 5–7번 늑연골' },
    innervation: { nerves: { en: 'Thoracoabdominal nerves (T7–T11), subcostal (T12)',
                             ko: '흉복부신경 (T7–T11), 늑하신경 (T12)' },
                   roots: ['T7', 'T8', 'T9', 'T10', 'T11', 'T12'] },
    actions: { en: 'Trunk flexion, posterior pelvic tilt, raises intra-abdominal pressure',
               ko: '체간 굴곡, 골반 후방경사, 복강내압 증가' },
    synergists: ['external oblique', 'internal oblique'],
    antagonists: ['multifidus', 'longissimus thoracis'],
    dysfunction: { en: 'Dominance over the deeper layer is the common fault, not weakness. Doming of the abdominal wall during flexion work indicates the load has exceeded what the deep system is controlling.',
                   ko: '흔한 문제는 약화가 아니라 심부층에 대한 과우세입니다. 굴곡 동작 중 복벽이 돔처럼 솟는 것은 부하가 심부 체계의 조절 범위를 넘었다는 신호입니다.' },
  }),

  'internal oblique': M({
    latin: 'Musculus obliquus internus abdominis',
    en: { name: 'Internal oblique',
          does: 'The middle abdominal layer, running up and forward like hands in your front pockets. It turns you toward the same side and helps compress the abdomen.',
          sci: 'Middle layer of the anterolateral abdominal wall; fibres run superomedially, perpendicular to external oblique. Ipsilateral rotation, lateral flexion, and with transversus abdominis a contributor to intra-abdominal pressure.',
          feels: 'A diagonal pull from the hip toward the opposite ribcage when you rotate.' },
    ko: { name: '내복사근',
          does: '중간 복부 층으로, 앞주머니에 손을 넣은 방향처럼 위앞쪽으로 달립니다. 몸을 같은 쪽으로 돌리고 복부 압박을 돕습니다.',
          sci: '전외측 복벽 중간층. 섬유가 외복사근과 수직으로 위내측을 향합니다. 동측 회전, 측굴, 복횡근과 함께 복강내압에 기여합니다.',
          feels: '회전할 때 골반에서 반대쪽 갈비뼈로 이어지는 대각선 당김.' },
    origin: { en: 'Thoracolumbar fascia, anterior two-thirds of iliac crest, lateral half of inguinal ligament',
              ko: '흉요근막, 장골능 전방 2/3, 서혜인대 외측 1/2' },
    insertion: { en: 'Inferior borders of ribs 10–12, linea alba, pecten pubis',
                 ko: '10–12번 늑골 하연, 백선, 치골즐' },
    innervation: { nerves: { en: 'Thoracoabdominal (T7–T11), subcostal (T12), iliohypogastric and ilioinguinal (L1)',
                             ko: '흉복부신경 (T7–T11), 늑하신경 (T12), 장골하복·장골서혜신경 (L1)' },
                   roots: ['T7', 'T8', 'T9', 'T10', 'T11', 'T12', 'L1'] },
    actions: { en: 'Ipsilateral rotation and lateral flexion, trunk flexion, abdominal compression',
               ko: '동측 회전 및 측굴, 체간 굴곡, 복부 압박' },
    synergists: ['transversus abdominis', 'external oblique'],
    antagonists: ['external oblique'],
    dysfunction: null,
  }),

  'external oblique': M({
    latin: 'Musculus obliquus externus abdominis',
    en: { name: 'External oblique',
          does: 'The outermost side-abdominal layer, running down and forward. It turns you toward the opposite side — so the right one turns you left.',
          sci: 'Most superficial of the anterolateral abdominal wall; fibres run inferomedially. Contralateral rotation, ipsilateral lateral flexion, trunk flexion, and a strong contributor to posterior pelvic tilt.',
          feels: 'A broad diagonal down the side of the ribcage toward the opposite hip.' },
    ko: { name: '외복사근',
          does: '가장 바깥쪽 측복부 층으로, 아래앞쪽으로 달립니다. 몸을 반대쪽으로 돌립니다. 오른쪽 근육이 몸을 왼쪽으로 돌립니다.',
          sci: '전외측 복벽의 최표층. 섬유가 아래내측을 향합니다. 반대측 회전, 동측 측굴, 체간 굴곡을 담당하며 골반 후방경사에 크게 기여합니다.',
          feels: '갈비뼈 옆면에서 반대쪽 골반으로 이어지는 넓은 대각선.' },
    origin: { en: 'External surfaces of ribs 5–12', ko: '5–12번 늑골 외면' },
    insertion: { en: 'Anterior half of iliac crest, linea alba via aponeurosis, inguinal ligament',
                 ko: '장골능 전방 1/2, 건막을 통한 백선, 서혜인대' },
    innervation: { nerves: { en: 'Thoracoabdominal nerves (T7–T11), subcostal (T12)',
                             ko: '흉복부신경 (T7–T11), 늑하신경 (T12)' },
                   roots: ['T7', 'T8', 'T9', 'T10', 'T11', 'T12'] },
    actions: { en: 'Contralateral rotation, ipsilateral lateral flexion, trunk flexion, posterior pelvic tilt',
               ko: '반대측 회전, 동측 측굴, 체간 굴곡, 골반 후방경사' },
    synergists: ['internal oblique', 'rectus abdominis'],
    antagonists: ['internal oblique'],
    dysfunction: null,
  }),

  'psoas major': M({
    latin: 'Musculus psoas major',
    en: { name: 'Psoas major',
          does: 'Runs from the lumbar spine, through the pelvis, to the inside of the thigh bone. It is the strongest hip flexor and the only muscle connecting spine directly to leg — which is why leg work is spine work.',
          sci: 'Originates from T12–L5 vertebral bodies, transverse processes and intervertebral discs; joins iliacus to insert on the lesser trochanter. Primary hip flexor; segmental attachments give it a direct compressive and shear influence on the lumbar spine.',
          feels: 'Deep in the front of the hip and low abdomen, well behind the muscles you can touch.' },
    ko: { name: '대요근',
          does: '요추에서 골반을 지나 대퇴골 안쪽까지 이어집니다. 가장 강한 고관절 굴곡근이며 척추와 다리를 직접 연결하는 유일한 근육입니다. 다리 운동이 곧 척추 운동인 이유입니다.',
          sci: 'T12–L5 추체, 횡돌기, 추간판에서 기시하여 장골근과 합쳐져 소전자에 정지합니다. 주된 고관절 굴곡근이며, 분절 부착으로 요추에 직접적인 압박·전단 영향을 줍니다.',
          feels: '만질 수 있는 근육보다 훨씬 뒤쪽, 고관절 앞과 아랫배 깊은 곳.' },
    origin: { en: 'Bodies, transverse processes and intervertebral discs of T12–L5',
              ko: 'T12–L5의 추체, 횡돌기, 추간판' },
    insertion: { en: 'Lesser trochanter of femur', ko: '대퇴골 소전자' },
    innervation: { nerves: { en: 'Anterior rami of L1–L3 directly (not via the femoral nerve)',
                             ko: 'L1–L3 전지에서 직접 (대퇴신경 경유 아님)' },
                   roots: ['L1', 'L2', 'L3'] },
    actions: { en: 'Hip flexion, external rotation of hip; with the femur fixed, lumbar flexion and lateral flexion',
               ko: '고관절 굴곡 및 외회전, 대퇴 고정 시 요추 굴곡·측굴' },
    synergists: ['iliacus', 'rectus femoris'],
    antagonists: ['gluteus maximus'],
    dysfunction: { en: 'In double-leg lowering work an unsupported psoas pulls the lumbar spine into extension; the deep abdominal layer has to hold the pelvis before the legs are worth loading.',
                   ko: '양다리 내리기 동작에서 제어되지 않은 대요근은 요추를 신전 방향으로 당깁니다. 다리에 부하를 주기 전에 심부 복부층이 골반을 잡아야 합니다.' },
  }),

  'gluteus maximus': M({
    latin: 'Musculus gluteus maximus',
    en: { name: 'Gluteus maximus',
          does: 'The biggest muscle in the body. It extends the hip — driving you up out of a squat, forward in a sprint, and upward in a bridge.',
          sci: 'Largest muscle by mass. Coarse fascicles from ilium, sacrum, coccyx and sacrotuberous ligament; upper fibres to the iliotibial tract, lower fibres to the gluteal tuberosity. Powerful hip extensor and external rotator, most active above about 60 degrees of hip flexion.',
          feels: 'A broad squeeze across the back of the hip, not a pinch at the tailbone.' },
    ko: { name: '대둔근',
          does: '인체에서 가장 큰 근육입니다. 고관절을 폅니다. 스쿼트에서 일어서고, 스프린트에서 앞으로 나아가고, 브릿지에서 골반을 들어 올립니다.',
          sci: '질량 기준 최대 근육. 장골·천골·미골·천결절인대에서 기시하는 굵은 근속으로, 상부 섬유는 장경인대, 하부 섬유는 둔근조면에 정지합니다. 강력한 고관절 신전·외회전근이며 고관절 굴곡 약 60도 이상에서 가장 활발합니다.',
          feels: '꼬리뼈를 조이는 느낌이 아니라 엉덩이 뒤쪽 전체가 넓게 조여드는 느낌.' },
    origin: { en: 'Posterior gluteal line of ilium, posterior sacrum and coccyx, sacrotuberous ligament',
              ko: '장골 후둔근선, 천골·미골 후면, 천결절인대' },
    insertion: { en: 'Iliotibial tract and gluteal tuberosity of femur', ko: '장경인대 및 대퇴골 둔근조면' },
    innervation: { nerves: { en: 'Inferior gluteal nerve (L5, S1, S2)', ko: '하둔신경 (L5, S1, S2)' },
                   roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Hip extension, external rotation, upper fibres abduct; stabilises the extended knee via the IT tract',
               ko: '고관절 신전·외회전, 상부 섬유는 외전. 장경인대를 통해 신전된 무릎을 안정화' },
    synergists: ['biceps femoris', 'semitendinosus', 'adductor magnus'],
    antagonists: ['psoas major', 'iliacus'],
    dysfunction: { en: 'Commonly substituted for by the hamstrings in bridging; a cramping hamstring during a shoulder bridge usually means the hip extensor of first resort has not been recruited.',
                   ko: '브릿지에서 흔히 햄스트링이 대신합니다. 숄더 브릿지 중 햄스트링에 쥐가 나는 것은 보통 일차 고관절 신전근이 동원되지 않았다는 뜻입니다.' },
  }),

  'quadratus lumborum': M({
    latin: 'Musculus quadratus lumborum',
    en: { name: 'Quadratus lumborum',
          does: 'A flat sheet between the last rib and the pelvis, at the back of the waist. It hikes the hip up and holds the ribcage steady over the pelvis when you stand on one leg.',
          sci: 'Quadrilateral muscle from iliac crest and iliolumbar ligament to rib 12 and lumbar transverse processes. Lateral flexion, elevation of the ilium, and stabilisation of rib 12 during forced expiration.',
          feels: 'A deep band at the side of the low back that shortens when you lean sideways.' },
    ko: { name: '요방형근',
          does: '허리 뒤쪽, 마지막 갈비뼈와 골반 사이의 납작한 판입니다. 골반을 위로 끌어올리고, 한 발로 설 때 흉곽을 골반 위에 고정합니다.',
          sci: '장골능·장요인대에서 12번 늑골과 요추 횡돌기로 이어지는 사변형 근육. 측굴, 장골 거상, 강제 호기 시 12번 늑골 고정을 담당합니다.',
          feels: '옆으로 기울일 때 짧아지는 허리 옆 깊은 띠.' },
    origin: { en: 'Iliac crest and iliolumbar ligament', ko: '장골능 및 장요인대' },
    insertion: { en: 'Rib 12 and transverse processes of L1–L4', ko: '12번 늑골 및 L1–L4 횡돌기' },
    innervation: { nerves: { en: 'Subcostal nerve (T12) and anterior rami of L1–L4',
                             ko: '늑하신경 (T12) 및 L1–L4 전지' },
                   roots: ['T12', 'L1', 'L2', 'L3', 'L4'] },
    actions: { en: 'Lateral flexion of trunk, elevation of ipsilateral ilium, fixes rib 12',
               ko: '체간 측굴, 동측 장골 거상, 12번 늑골 고정' },
    synergists: ['internal oblique', 'external oblique'],
    antagonists: ['quadratus lumborum'],
    dysfunction: null,
  }),

  'serratus anterior': M({
    latin: 'Musculus serratus anterior',
    en: { name: 'Serratus anterior',
          does: 'Wraps from the ribs around to the underside of the shoulder blade. It holds the shoulder blade flat against the ribcage — without it the blade wings off the back.',
          sci: 'Fleshy digitations from ribs 1–8/9 to the costal surface of the medial border of the scapula. Protracts and upwardly rotates the scapula; the primary stabiliser holding the scapula against the thoracic wall.',
          feels: 'A wide spread across the side of the ribs, and the shoulder blade lying flat rather than lifting.' },
    ko: { name: '전거근',
          does: '갈비뼈에서 견갑골 아래면까지 감싸 돌아갑니다. 견갑골을 흉곽에 밀착시키며, 없으면 견갑골이 등에서 날개처럼 뜹니다.',
          sci: '1–8/9번 늑골에서 견갑골 내측연 늑골면까지 이어지는 육질 지상돌기. 견갑골 전인 및 상방회전을 담당하며 견갑골을 흉벽에 고정하는 주 안정근입니다.',
          feels: '갈비뼈 옆면이 넓게 퍼지고 견갑골이 들리지 않고 납작하게 놓이는 느낌.' },
    origin: { en: 'External surfaces of ribs 1–8 or 1–9', ko: '1–8 또는 1–9번 늑골 외면' },
    insertion: { en: 'Costal surface of the medial border of the scapula', ko: '견갑골 내측연 늑골면' },
    innervation: { nerves: { en: 'Long thoracic nerve (C5, C6, C7)', ko: '장흉신경 (C5, C6, C7)' },
                   roots: ['C5', 'C6', 'C7'] },
    actions: { en: 'Scapular protraction and upward rotation; holds the scapula against the thorax',
               ko: '견갑골 전인 및 상방회전, 견갑골을 흉곽에 밀착' },
    synergists: ['trapezius'],
    antagonists: ['rhomboid major', 'trapezius'],
    dysfunction: { en: 'Long thoracic nerve palsy produces the classic winged scapula — a visible, unambiguous demonstration that a nerve lesion and a muscle failure look the same from outside.',
                   ko: '장흉신경 마비는 전형적인 익상견갑을 만듭니다. 신경 병변과 근육 기능 부전이 겉으로 같아 보인다는 것을 명확히 보여줍니다.' },
  }),

  'trapezius': M({
    latin: 'Musculus trapezius',
    en: { name: 'Trapezius',
          does: 'The big diamond across the upper back and neck, in three parts that pull in three different directions. The upper part shrugs, the middle draws the blades together, the lower pulls them down.',
          sci: 'Three functional divisions — descending, transverse and ascending — from the occiput and spinous processes C7–T12 to the lateral clavicle, acromion and scapular spine. Together with serratus anterior forms the force couple producing scapular upward rotation.',
          feels: 'Upper: the shrug. Lower: a downward slide of the shoulder blade toward the opposite back pocket.' },
    ko: { name: '승모근',
          does: '등 윗부분과 목을 덮는 큰 마름모로, 세 부분이 서로 다른 방향으로 당깁니다. 상부는 으쓱, 중부는 견갑골을 모으고, 하부는 아래로 내립니다.',
          sci: '하행·수평·상행 세 기능 구획. 후두골과 C7–T12 극돌기에서 쇄골 외측·견봉·견갑극으로 이어집니다. 전거근과 함께 견갑골 상방회전의 짝힘을 만듭니다.',
          feels: '상부는 으쓱하는 느낌, 하부는 견갑골이 반대쪽 뒷주머니를 향해 미끄러져 내려가는 느낌.' },
    origin: { en: 'External occipital protuberance, nuchal ligament, spinous processes C7–T12',
              ko: '외후두융기, 항인대, C7–T12 극돌기' },
    insertion: { en: 'Lateral third of clavicle, acromion, spine of scapula',
                 ko: '쇄골 외측 1/3, 견봉, 견갑극' },
    innervation: { nerves: { en: 'Accessory nerve (CN XI) for motor; C3–C4 for proprioception',
                             ko: '운동은 부신경 (CN XI), 고유감각은 C3–C4' },
                   roots: ['CN XI', 'C3', 'C4'] },
    actions: { en: 'Upper: scapular elevation. Middle: retraction. Lower: depression and upward rotation.',
               ko: '상부: 견갑골 거상. 중부: 후인. 하부: 하강 및 상방회전.' },
    synergists: ['serratus anterior', 'rhomboid major', 'levator scapulae'],
    antagonists: ['serratus anterior'],
    dysfunction: { en: 'Upper-dominant, lower-quiet is the usual pattern at a desk, and it shows up as shoulders rising during any overhead or supported work.',
                   ko: '책상 생활에서 흔한 패턴은 상부 우세·하부 저활성이며, 머리 위 동작이나 지지 동작에서 어깨가 올라가는 형태로 나타납니다.' },
  }),

  'latissimus dorsi': M({
    latin: 'Musculus latissimus dorsi',
    en: { name: 'Latissimus dorsi',
          does: 'The broad fan of the back that pulls the arm down and backward — the muscle of a pull-up, and the reason a big back moves your arm.',
          sci: 'Broad triangular muscle from the thoracolumbar fascia, spinous processes T7–L5, iliac crest and lower ribs to the intertubercular groove of the humerus. Extends, adducts and medially rotates the humerus; via the thoracolumbar fascia it links arm force into the opposite hip.',
          feels: 'A wide pull under the armpit that reaches all the way to the low back.' },
    ko: { name: '광배근',
          does: '팔을 아래·뒤로 당기는 등의 넓은 부채꼴 근육입니다. 턱걸이의 근육이며, 넓은 등이 팔을 움직이는 이유입니다.',
          sci: '흉요근막, T7–L5 극돌기, 장골능, 하부 늑골에서 상완골 결절간구로 이어지는 넓은 삼각형 근육. 상완골의 신전·내전·내회전을 담당하며, 흉요근막을 통해 팔의 힘을 반대쪽 고관절로 전달합니다.',
          feels: '겨드랑이 아래에서 허리까지 이어지는 넓은 당김.' },
    origin: { en: 'Thoracolumbar fascia, spinous processes T7–L5, iliac crest, ribs 9–12, inferior angle of scapula',
              ko: '흉요근막, T7–L5 극돌기, 장골능, 9–12번 늑골, 견갑골 하각' },
    insertion: { en: 'Floor of the intertubercular groove of the humerus', ko: '상완골 결절간구 바닥' },
    innervation: { nerves: { en: 'Thoracodorsal nerve (C6, C7, C8)', ko: '흉배신경 (C6, C7, C8)' },
                   roots: ['C6', 'C7', 'C8'] },
    actions: { en: 'Humeral extension, adduction and medial rotation; assists trunk extension',
               ko: '상완골 신전·내전·내회전, 체간 신전 보조' },
    synergists: ['trapezius'],
    antagonists: ['deltoid'],
    dysfunction: null,
  }),

  'iliacus': M({
    latin: 'Musculus iliacus',
    en: { name: 'Iliacus',
          does: 'Lines the inside of the pelvic bowl and joins the psoas to flex the hip. Together they are usually called iliopsoas.',
          sci: 'Fan-shaped muscle from the iliac fossa converging with psoas major into the iliopsoas tendon at the lesser trochanter. Hip flexor without direct spinal attachment.',
          feels: 'Deep inside the front of the pelvis rather than at the crease of the hip.' },
    ko: { name: '장골근',
          does: '골반 안쪽 면을 덮으며 대요근과 합쳐져 고관절을 굽힙니다. 둘을 합쳐 장요근이라 부릅니다.',
          sci: '장골와에서 부채꼴로 기시해 대요근과 합류하여 소전자의 장요근건을 이룹니다. 척추에 직접 부착이 없는 고관절 굴곡근입니다.',
          feels: '고관절 접히는 부위가 아니라 골반 앞쪽 깊은 안쪽.' },
    origin: { en: 'Iliac fossa, ala of sacrum, anterior sacroiliac ligaments', ko: '장골와, 천골익, 전천장인대' },
    insertion: { en: 'Lesser trochanter of femur, via the iliopsoas tendon', ko: '장요근건을 통한 대퇴골 소전자' },
    innervation: { nerves: { en: 'Femoral nerve (L2, L3)', ko: '대퇴신경 (L2, L3)' },
                   roots: ['L2', 'L3'] },
    actions: { en: 'Hip flexion; anterior pelvic tilt with the femur fixed', ko: '고관절 굴곡, 대퇴 고정 시 골반 전방경사' },
    synergists: ['psoas major', 'rectus femoris'],
    antagonists: ['gluteus maximus'],
    dysfunction: null,
  }),

  'rectus femoris': M({
    latin: 'Musculus rectus femoris',
    en: { name: 'Rectus femoris',
          does: 'The only one of the four quadriceps that crosses both the hip and the knee, so it both straightens the knee and lifts the thigh.',
          sci: 'Biarticular head of the quadriceps femoris from the anterior inferior iliac spine to the patella via the quadriceps tendon. Knee extension and hip flexion; length-dependent force sharing with the vasti.',
          feels: 'Down the middle of the front of the thigh, from hip to kneecap.' },
    ko: { name: '대퇴직근',
          does: '네 갈래 대퇴사두근 중 유일하게 고관절과 무릎을 모두 지나므로, 무릎을 펴는 동시에 허벅지를 들어 올립니다.',
          sci: '전하장골극에서 대퇴사두건을 통해 슬개골로 이어지는 이관절 두. 슬관절 신전과 고관절 굴곡을 담당하며, 광근들과 길이 의존적으로 힘을 분담합니다.',
          feels: '고관절에서 무릎뼈까지 허벅지 앞면 한가운데.' },
    origin: { en: 'Anterior inferior iliac spine and the groove above the acetabulum',
              ko: '전하장골극 및 관골구 상방 고랑' },
    insertion: { en: 'Patella, then tibial tuberosity via the patellar ligament',
                 ko: '슬개골, 이후 슬개인대를 통해 경골조면' },
    innervation: { nerves: { en: 'Femoral nerve (L2, L3, L4)', ko: '대퇴신경 (L2, L3, L4)' },
                   roots: ['L2', 'L3', 'L4'] },
    actions: { en: 'Knee extension, hip flexion', ko: '슬관절 신전, 고관절 굴곡' },
    synergists: ['vastus lateralis', 'psoas major'],
    antagonists: ['biceps femoris', 'semitendinosus'],
    dysfunction: null,
  }),

  'biceps femoris': M({
    latin: 'Musculus biceps femoris',
    en: { name: 'Biceps femoris',
          does: 'The outer hamstring. Bends the knee and extends the hip, and it is the hamstring most often torn in sprinting.',
          sci: 'Two heads: long head from the ischial tuberosity (biarticular), short head from the linea aspera. Inserts on the fibular head. Knee flexion, hip extension, and external rotation of the flexed knee.',
          feels: 'The outer cord at the back of the thigh, standing out behind the knee when you bend it.' },
    ko: { name: '대퇴이두근',
          does: '바깥쪽 햄스트링입니다. 무릎을 굽히고 고관절을 펴며, 스프린트에서 가장 자주 파열되는 햄스트링입니다.',
          sci: '두 갈래로, 장두는 좌골결절(이관절), 단두는 조선에서 기시하여 비골두에 정지합니다. 슬관절 굴곡, 고관절 신전, 굴곡된 무릎의 외회전을 담당합니다.',
          feels: '허벅지 뒤 바깥쪽 줄기이며, 무릎을 굽히면 무릎 뒤로 도드라집니다.' },
    origin: { en: 'Long head: ischial tuberosity. Short head: linea aspera and lateral supracondylar line.',
              ko: '장두: 좌골결절. 단두: 조선 및 외측과상선.' },
    insertion: { en: 'Head of the fibula', ko: '비골두' },
    innervation: { nerves: { en: 'Long head: tibial division of sciatic (L5, S1, S2). Short head: common fibular division (L5, S1, S2).',
                             ko: '장두: 좌골신경 경골분지 (L5, S1, S2). 단두: 총비골분지 (L5, S1, S2).' },
                   roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Knee flexion, hip extension, lateral rotation of the flexed knee',
               ko: '슬관절 굴곡, 고관절 신전, 굴곡된 무릎의 외회전' },
    synergists: ['semitendinosus', 'gluteus maximus'],
    antagonists: ['rectus femoris', 'vastus lateralis'],
    dysfunction: { en: 'The long head is the commonest site of hamstring strain, typically during the late swing phase of sprinting when it is lengthening under load.',
                   ko: '장두는 햄스트링 좌상이 가장 흔한 부위이며, 주로 스프린트의 유각기 후반에 부하를 받으며 늘어날 때 발생합니다.' },
  }),

  'deltoid': M({
    latin: 'Musculus deltoideus',
    en: { name: 'Deltoid',
          does: 'The cap of the shoulder, in three parts. The front lifts the arm forward, the side lifts it out, the back pulls it behind you.',
          sci: 'Clavicular, acromial and spinal parts from the lateral clavicle, acromion and scapular spine to the deltoid tuberosity. Abduction beyond about 15 degrees is chiefly acromial; flexion and extension are the anterior and posterior parts.',
          feels: 'A rounded ache over the point of the shoulder.' },
    ko: { name: '삼각근',
          does: '어깨를 덮는 세 부분의 근육입니다. 앞쪽은 팔을 앞으로, 옆쪽은 옆으로, 뒤쪽은 뒤로 보냅니다.',
          sci: '쇄골부·견봉부·극부가 쇄골 외측, 견봉, 견갑극에서 삼각근조면으로 이어집니다. 약 15도 이상의 외전은 주로 견봉부가, 굴곡·신전은 전·후부가 담당합니다.',
          feels: '어깨 끝 부분의 둥근 뻐근함.' },
    origin: { en: 'Lateral third of clavicle, acromion, spine of scapula', ko: '쇄골 외측 1/3, 견봉, 견갑극' },
    insertion: { en: 'Deltoid tuberosity of humerus', ko: '상완골 삼각근조면' },
    innervation: { nerves: { en: 'Axillary nerve (C5, C6)', ko: '액와신경 (C5, C6)' },
                   roots: ['C5', 'C6'] },
    actions: { en: 'Abduction; anterior part flexes and medially rotates, posterior part extends and laterally rotates',
               ko: '외전. 전부는 굴곡·내회전, 후부는 신전·외회전' },
    synergists: ['supraspinatus', 'trapezius'],
    antagonists: ['latissimus dorsi'],
    dysfunction: null,
  }),

  'pectoralis major': M({
    latin: 'Musculus pectoralis major',
    en: { name: 'Pectoralis major',
          does: 'The chest muscle. Brings the arm across the body and forward — the pressing muscle.',
          sci: 'Clavicular and sternocostal heads to the lateral lip of the intertubercular groove, with the two heads twisting so the clavicular fibres insert inferiorly. Adduction, medial rotation, and flexion from the clavicular head.',
          feels: 'A broad squeeze across the front of the chest toward the breastbone.' },
    ko: { name: '대흉근',
          does: '가슴 근육입니다. 팔을 몸 앞으로, 안쪽으로 가져옵니다. 미는 동작의 근육입니다.',
          sci: '쇄골두와 흉늑두가 결절간구 외측순에 정지하며, 두 갈래가 꼬여 쇄골부 섬유가 아래쪽에 부착합니다. 내전·내회전과 쇄골두에 의한 굴곡을 담당합니다.',
          feels: '가슴 앞면이 복장뼈 쪽으로 넓게 조여드는 느낌.' },
    origin: { en: 'Medial clavicle, sternum, costal cartilages 1–6, aponeurosis of external oblique',
              ko: '쇄골 내측, 흉골, 1–6번 늑연골, 외복사근 건막' },
    insertion: { en: 'Lateral lip of the intertubercular groove of the humerus', ko: '상완골 결절간구 외측순' },
    innervation: { nerves: { en: 'Lateral pectoral (C5, C6, C7) and medial pectoral (C8, T1) nerves',
                             ko: '외측흉근신경 (C5, C6, C7) 및 내측흉근신경 (C8, T1)' },
                   roots: ['C5', 'C6', 'C7', 'C8', 'T1'] },
    actions: { en: 'Adduction and medial rotation of the humerus; clavicular head flexes, sternocostal head extends from flexion',
               ko: '상완골 내전·내회전. 쇄골두는 굴곡, 흉늑두는 굴곡 위치에서 신전' },
    synergists: ['deltoid', 'triceps brachii'],
    antagonists: ['trapezius', 'latissimus dorsi'],
    dysfunction: null,
  }),

  'sternocleidomastoid': M({
    latin: 'Musculus sternocleidomastoideus',
    en: { name: 'Sternocleidomastoid',
          does: 'The rope down the side of the neck. Turns the head to the opposite side and, when both fire, pokes the chin forward — which is exactly the fault you see in an unsupported Hundred.',
          sci: 'Sternal and clavicular heads to the mastoid process and superior nuchal line. Unilateral: contralateral rotation with ipsilateral lateral flexion. Bilateral: cervical flexion, but upper cervical extension if the deep flexors do not hold.',
          feels: 'A hard cord at the front-side of the neck, and a burning that arrives early when the head is unsupported.' },
    ko: { name: '흉쇄유돌근',
          does: '목 옆면의 줄기입니다. 머리를 반대쪽으로 돌리고, 양쪽이 함께 작용하면 턱을 앞으로 내밉니다. 지지 없는 헌드레드에서 흔히 보이는 바로 그 오류입니다.',
          sci: '흉골두와 쇄골두가 유양돌기와 상항선에 정지합니다. 편측 작용은 반대측 회전과 동측 측굴, 양측 작용은 경추 굴곡이지만 심부 굴곡근이 버티지 못하면 상부 경추 신전이 됩니다.',
          feels: '목 앞옆의 단단한 줄기와, 머리를 받치지 않았을 때 일찍 찾아오는 타는 느낌.' },
    origin: { en: 'Manubrium of sternum and medial third of clavicle', ko: '흉골병 및 쇄골 내측 1/3' },
    insertion: { en: 'Mastoid process and lateral superior nuchal line', ko: '유양돌기 및 상항선 외측' },
    innervation: { nerves: { en: 'Accessory nerve (CN XI) for motor; C2–C3 for proprioception',
                             ko: '운동은 부신경 (CN XI), 고유감각은 C2–C3' },
                   roots: ['CN XI', 'C2', 'C3'] },
    actions: { en: 'Contralateral head rotation, ipsilateral lateral flexion, cervical flexion when bilateral',
               ko: '반대측 두부 회전, 동측 측굴, 양측 작용 시 경추 굴곡' },
    synergists: [],
    antagonists: ['multifidus'],
    dysfunction: { en: 'Dominance over the deep cervical flexors is the standard neck fault in supine flexion work. Support the head and the fault disappears — which tells you it was a control problem, not a strength one.',
                   ko: '누워서 하는 굴곡 동작에서 심부 경부 굴곡근보다 우세해지는 것이 전형적인 목 오류입니다. 머리를 받치면 사라지므로, 근력이 아니라 조절의 문제임을 알 수 있습니다.' },
  }),

  'longissimus thoracis': M({
    latin: 'Musculus longissimus thoracis',
    en: { name: 'Longissimus thoracis',
          does: 'The long middle column of the back extensors, running most of the length of the spine. It straightens you up and controls the speed at which you bend forward.',
          sci: 'Intermediate column of erector spinae from the sacrum, iliac crest and lumbar transverse processes to thoracic transverse processes and ribs. Extension and lateral flexion; eccentric control of trunk flexion.',
          feels: 'Two long ropes either side of the spine that fire as you come back up from bending.' },
    ko: { name: '흉최장근',
          does: '척주기립근의 긴 중간 기둥으로 척추 대부분을 따라 달립니다. 몸을 일으켜 세우고 앞으로 굽히는 속도를 조절합니다.',
          sci: '천골·장골능·요추 횡돌기에서 흉추 횡돌기와 늑골로 이어지는 척주기립근 중간 기둥. 신전과 측굴, 체간 굴곡의 원심성 제어를 담당합니다.',
          feels: '척추 양옆의 두 긴 줄기가 굽혔다 일어설 때 작동하는 느낌.' },
    origin: { en: 'Sacrum, iliac crest, lumbar transverse and spinous processes via the erector spinae aponeurosis',
              ko: '척주기립근 건막을 통한 천골, 장골능, 요추 횡돌기·극돌기' },
    insertion: { en: 'Transverse processes of thoracic vertebrae and ribs 2–12',
                 ko: '흉추 횡돌기 및 2–12번 늑골' },
    innervation: { nerves: { en: 'Lateral branches of the posterior rami of spinal nerves, segmentally',
                             ko: '척수신경 후지 외측분지, 분절별' },
                   roots: ['C1', 'T1', 'T6', 'L1', 'L5'] },
    actions: { en: 'Trunk and neck extension, ipsilateral lateral flexion, eccentric control of flexion',
               ko: '체간·경부 신전, 동측 측굴, 굴곡의 원심성 제어' },
    synergists: ['iliocostalis lumborum', 'multifidus'],
    antagonists: ['rectus abdominis'],
    dysfunction: null,
  }),

  'iliocostalis lumborum': M({
    latin: 'Musculus iliocostalis lumborum',
    en: { name: 'Iliocostalis lumborum',
          does: 'The outermost column of the back extensors, furthest from the spine, so it has the best leverage for bending sideways.',
          sci: 'Lateral column of erector spinae from the iliac crest and sacrum to the angles of the lower ribs. Greatest moment arm for lateral flexion of the three erector columns.',
          feels: 'The outer edge of the low back, above the pelvis.' },
    ko: { name: '요장늑근',
          does: '척주기립근 중 가장 바깥 기둥으로 척추에서 가장 멀어, 옆으로 굽히는 데 가장 좋은 지렛대를 가집니다.',
          sci: '장골능·천골에서 하부 늑골각으로 이어지는 척주기립근 외측 기둥. 세 기둥 중 측굴 모멘트암이 가장 큽니다.',
          feels: '골반 위쪽, 허리 바깥 가장자리.' },
    origin: { en: 'Iliac crest, sacrum, erector spinae aponeurosis', ko: '장골능, 천골, 척주기립근 건막' },
    insertion: { en: 'Angles of ribs 7–12', ko: '7–12번 늑골각' },
    innervation: { nerves: { en: 'Lateral branches of the posterior rami of lumbar spinal nerves',
                             ko: '요부 척수신경 후지 외측분지' },
                   roots: ['L1', 'L2', 'L3', 'L4'] },
    actions: { en: 'Trunk extension and lateral flexion', ko: '체간 신전 및 측굴' },
    synergists: ['longissimus thoracis'],
    antagonists: ['rectus abdominis'],
    dysfunction: null,
  }),

  'gluteus medius': M({
    latin: 'Musculus gluteus medius',
    en: { name: 'Gluteus medius',
          does: 'On the side of the hip. Its real job is not lifting the leg out but stopping the pelvis dropping when you stand on one foot.',
          sci: 'From the outer ilium between the anterior and posterior gluteal lines to the greater trochanter. Hip abduction; in single-leg stance it holds the contralateral hemipelvis level.',
          feels: 'A deep burn on the side of the standing hip, not in the thigh.' },
    ko: { name: '중둔근',
          does: '고관절 옆면에 있습니다. 실제 역할은 다리를 옆으로 드는 것이 아니라 한 발로 섰을 때 골반이 떨어지지 않게 잡는 것입니다.',
          sci: '전·후둔근선 사이의 장골 외면에서 대전자로 이어집니다. 고관절 외전을 담당하며, 한 발 지지 시 반대쪽 반골반을 수평으로 유지합니다.',
          feels: '허벅지가 아니라 딛고 선 쪽 고관절 옆면 깊은 곳의 타는 느낌.' },
    origin: { en: 'Outer surface of ilium between the anterior and posterior gluteal lines',
              ko: '전·후둔근선 사이 장골 외면' },
    insertion: { en: 'Lateral surface of the greater trochanter', ko: '대전자 외측면' },
    innervation: { nerves: { en: 'Superior gluteal nerve (L4, L5, S1)', ko: '상둔신경 (L4, L5, S1)' },
                   roots: ['L4', 'L5', 'S1'] },
    actions: { en: 'Hip abduction; anterior fibres medially rotate, posterior fibres laterally rotate; pelvic stabilisation in single-leg stance',
               ko: '고관절 외전, 전방 섬유는 내회전·후방 섬유는 외회전, 한 발 지지 시 골반 안정화' },
    synergists: ['tensor fasciae latae', 'gluteus maximus'],
    antagonists: ['adductor magnus'],
    dysfunction: { en: 'A positive Trendelenburg sign — the opposite hip dropping in single-leg stance — is the visible test, and the muscle is often controlling rather than weak.',
                   ko: '한 발로 설 때 반대쪽 골반이 떨어지는 트렌델렌부르크 징후가 눈으로 보는 검사입니다. 근력 저하가 아니라 조절 문제인 경우가 많습니다.' },
  }),

  'semitendinosus': M({
    latin: 'Musculus semitendinosus',
    en: { name: 'Semitendinosus',
          does: 'The inner hamstring with the long tendon. Bends the knee, extends the hip, and turns the bent knee inward.',
          sci: 'From the ischial tuberosity to the medial tibia as part of the pes anserinus. Knee flexion, hip extension, medial rotation of the flexed knee.',
          feels: 'The inner cord at the back of the thigh.' },
    ko: { name: '반건양근',
          does: '긴 힘줄을 가진 안쪽 햄스트링입니다. 무릎을 굽히고 고관절을 펴며 굽힌 무릎을 안쪽으로 돌립니다.',
          sci: '좌골결절에서 거위발건의 일부로 경골 내측에 정지합니다. 슬관절 굴곡, 고관절 신전, 굴곡된 무릎의 내회전을 담당합니다.',
          feels: '허벅지 뒤 안쪽 줄기.' },
    origin: { en: 'Ischial tuberosity', ko: '좌골결절' },
    insertion: { en: 'Medial surface of the tibia, via the pes anserinus', ko: '거위발건을 통한 경골 내측면' },
    innervation: { nerves: { en: 'Tibial division of the sciatic nerve (L5, S1, S2)',
                             ko: '좌골신경 경골분지 (L5, S1, S2)' },
                   roots: ['L5', 'S1', 'S2'] },
    actions: { en: 'Knee flexion, hip extension, medial rotation of the flexed knee',
               ko: '슬관절 굴곡, 고관절 신전, 굴곡된 무릎의 내회전' },
    synergists: ['biceps femoris', 'gluteus maximus'],
    antagonists: ['rectus femoris'],
    dysfunction: null,
  }),

  'gastrocnemius': M({
    latin: 'Musculus gastrocnemius',
    en: { name: 'Gastrocnemius',
          does: 'The visible bulge of the calf. Points the foot down and helps bend the knee — it crosses both joints, so a straight knee makes it stronger at the ankle.',
          sci: 'Two heads from the femoral condyles joining soleus at the calcaneal tendon. Biarticular: plantarflexion is strongest with the knee extended.',
          feels: 'High in the calf, and much stronger with a straight leg than a bent one.' },
    ko: { name: '비복근',
          does: '눈에 보이는 종아리 볼록입니다. 발끝을 아래로 밀고 무릎 굽힘을 돕습니다. 두 관절을 지나므로 무릎을 펴면 발목에서 더 강해집니다.',
          sci: '대퇴과에서 기시한 두 갈래가 가자미근과 함께 종골건을 이룹니다. 이관절근으로, 무릎을 편 상태에서 족저굴곡이 가장 강합니다.',
          feels: '종아리 윗부분. 무릎을 폈을 때가 굽혔을 때보다 훨씬 강합니다.' },
    origin: { en: 'Medial and lateral femoral condyles', ko: '대퇴골 내·외측과' },
    insertion: { en: 'Calcaneus via the calcaneal (Achilles) tendon', ko: '종골건(아킬레스건)을 통한 종골' },
    innervation: { nerves: { en: 'Tibial nerve (S1, S2)', ko: '경골신경 (S1, S2)' },
                   roots: ['S1', 'S2'] },
    actions: { en: 'Plantarflexion of the ankle, assists knee flexion', ko: '발목 족저굴곡, 슬관절 굴곡 보조' },
    synergists: ['soleus'],
    antagonists: ['tibialis anterior'],
    dysfunction: null,
  }),

  'soleus': M({
    latin: 'Musculus soleus',
    en: { name: 'Soleus',
          does: 'The flat muscle underneath the calf bulge. It only crosses the ankle, so it does the work when your knee is bent — and it is the muscle that holds you upright all day.',
          sci: 'From the posterior tibia and fibula to the calcaneal tendon. Monoarticular plantarflexor, predominantly slow-twitch; a principal antigravity muscle in quiet standing.',
          feels: 'Deep and low in the calf, most obvious in a bent-knee calf raise.' },
    ko: { name: '가자미근',
          does: '종아리 볼록 아래의 납작한 근육입니다. 발목만 지나므로 무릎이 굽혀진 상태에서 일하며, 하루 종일 몸을 세워 두는 근육입니다.',
          sci: '경골·비골 후면에서 종골건으로 이어집니다. 단관절 족저굴곡근으로 지근 섬유가 우세하며, 조용한 기립에서 주된 항중력근입니다.',
          feels: '종아리 아래 깊은 곳. 무릎을 굽힌 카프레이즈에서 가장 뚜렷합니다.' },
    origin: { en: 'Soleal line of tibia, head and posterior fibula', ko: '경골 가자미근선, 비골두 및 비골 후면' },
    insertion: { en: 'Calcaneus via the calcaneal tendon', ko: '종골건을 통한 종골' },
    innervation: { nerves: { en: 'Tibial nerve (S1, S2)', ko: '경골신경 (S1, S2)' },
                   roots: ['S1', 'S2'] },
    actions: { en: 'Plantarflexion; postural control of forward sway in standing',
               ko: '족저굴곡, 기립 시 전방 동요의 자세 제어' },
    synergists: ['gastrocnemius'],
    antagonists: ['tibialis anterior'],
    dysfunction: null,
  }),

  'infraspinatus muscle': M({
    latin: 'Musculus infraspinatus',
    en: { name: 'Infraspinatus',
          does: 'One of the four rotator cuff muscles. Turns the arm outward and, more importantly, holds the ball of the shoulder centred in its socket while bigger muscles move it.',
          sci: 'From the infraspinous fossa to the middle facet of the greater tubercle. Principal external rotator; with the rest of the cuff provides dynamic glenohumeral compression.',
          feels: 'Behind and below the shoulder blade spine, not at the shoulder joint itself.' },
    ko: { name: '극하근',
          does: '네 개의 회전근개 중 하나입니다. 팔을 바깥으로 돌리고, 더 중요하게는 큰 근육들이 팔을 움직이는 동안 어깨 공이 관절와 중심에 머물게 합니다.',
          sci: '극하와에서 대결절 중간면으로 이어집니다. 주된 외회전근이며, 다른 회전근개와 함께 견관절의 동적 압박을 제공합니다.',
          feels: '어깨 관절 자체가 아니라 견갑극 아래·뒤쪽.' },
    origin: { en: 'Infraspinous fossa of the scapula', ko: '견갑골 극하와' },
    insertion: { en: 'Middle facet of the greater tubercle of the humerus', ko: '상완골 대결절 중간면' },
    innervation: { nerves: { en: 'Suprascapular nerve (C5, C6)', ko: '견갑상신경 (C5, C6)' },
                   roots: ['C5', 'C6'] },
    actions: { en: 'External rotation of the humerus; glenohumeral stabilisation',
               ko: '상완골 외회전, 견관절 안정화' },
    synergists: ['supraspinatus'],
    antagonists: ['pectoralis major', 'latissimus dorsi'],
    dysfunction: null,
  }),
};

/**
 * One table, two files. The long-form entries win on a key collision, so adding an atlas
 * entry can never quietly replace a written-out one.
 */
export const MUSCLE_INFO = { ...MUSCLE_ATLAS, ...CORE };

export const MUSCLE_KEYS = Object.keys(MUSCLE_INFO);
