/**
 * Every interface string, en + ko. Retrofitting a third language onto this is easy;
 * retrofitting bilingual onto a monolingual app is not, which is why nothing here is
 * allowed to be a bare English literal in a template.
 */

/**
 * The four lines that must not move.
 *
 * neurolab had one — "this is a template brain, not the child's brain". This project
 * inherits it and adds three, and all four are rendered where the user actually is rather
 * than in a footer nobody scrolls to.
 */
export const DISCLAIMERS = [
  /* The title and the body-specific sentences are rewritten per body by
   * `templateDisclaimer()` in `bodies.js` — a female body must not carry a male body's
   * disclaimer. What stays here is the half that is true of any scanned person. */
  { key: 'template',
    en: { title: 'One template body, not yours',
          body: 'Everything you see is a reference anatomy, segmented from one scanned person and published as an atlas. It is not a scan of you. Muscle size, shape and attachment points vary between real people, and none of the proportions here are a measurement of your body.' },
    ko: { title: '한 사람의 표준 인체이며 당신의 몸이 아닙니다',
          body: '보이는 모든 것은 스캔된 한 사람에게서 분할되어 아틀라스로 공개된 참조 해부학입니다. 당신을 촬영한 것이 아닙니다. 근육의 크기, 형태, 부착 지점은 사람마다 다르며, 여기의 어떤 비율도 당신 몸의 측정값이 아닙니다.' } },
  { key: 'medical',
    en: { title: 'Not medical advice',
          body: 'Nothing here diagnoses, treats or prescribes. If you have pain, an injury, are pregnant, or have a medical condition, see a qualified professional before doing any of this. Every exercise carries its own contraindications and they are not optional reading.' },
    ko: { title: '의학적 조언이 아닙니다',
          body: '여기 어떤 내용도 진단, 치료, 처방이 아닙니다. 통증이나 부상이 있거나 임신 중이거나 질환이 있다면 실행 전에 전문가와 상담하십시오. 모든 운동에는 각각의 금기사항이 있으며 선택적으로 읽을 내용이 아닙니다.' } },
  { key: 'population',
    en: { title: 'Group averages, not a prediction about you',
          body: 'Every research finding here is an average across a group of people who were studied. "Aerobic exercise increases hippocampal volume" is a mean from a trial of sedentary 55-to-80-year-olds — it is not a promise about what will happen to you. The population and the effect size are shown with every claim for exactly this reason.' },
    ko: { title: '집단 평균이며 당신에 대한 예측이 아닙니다',
          body: '여기의 모든 연구 결과는 연구에 참여한 집단의 평균입니다. "유산소 운동이 해마 부피를 늘린다"는 55–80세 좌식 생활자를 대상으로 한 시험의 평균이며, 당신에게 일어날 일에 대한 약속이 아닙니다. 바로 이 때문에 모든 주장에 대상 집단과 효과 크기를 함께 표시합니다.' } },
  { key: 'evidence',
    en: { title: 'The strength of the evidence is shown, always',
          body: 'A finding from a meta-analysis and a finding extrapolated from mice do not get to look the same. Every claim carries a tier from A to E and the source it came from. Where the reasoning is inference rather than measurement — which is most of Pilates — it is labelled as inference.' },
    ko: { title: '근거의 강도를 항상 표시합니다',
          body: '메타분석에서 나온 결과와 생쥐 실험에서 외삽한 결과가 같아 보여서는 안 됩니다. 모든 주장에 A–E 등급과 출처를 표시합니다. 측정이 아니라 추론인 경우 — 필라테스의 대부분이 그렇습니다 — 추론이라고 명시합니다.' } },
];

export const UI = {
  title:        { en: 'Neuro Wellness', ko: '뉴로 웰니스' },
  subtitle:     { en: 'How exercise moves the body, and what it does to the brain',
                  ko: '운동이 몸을 어떻게 움직이고 뇌에 무엇을 하는가' },

  // panels
  tabExplore:   { en: 'Explore', ko: '탐색' },
  tabExercise:  { en: 'Exercises', ko: '운동' },
  tabEvidence:  { en: 'Evidence', ko: '근거' },
  tabAbout:     { en: 'About', ko: '정보' },

  // layers
  layers:       { en: 'Layers', ko: '레이어' },
  skeleton:     { en: 'Skeleton', ko: '골격' },
  muscles_superficial: { en: 'Muscles — superficial', ko: '근육 — 표층' },
  muscles_deep: { en: 'Muscles — deep', ko: '근육 — 심층' },
  organs:       { en: 'Organs', ko: '장기' },
  nervous:      { en: 'Nerves', ko: '신경' },
  brain:        { en: 'Brain', ko: '뇌' },

  // views
  views:        { en: 'View', ko: '시점' },
  anterior:     { en: 'Front', ko: '전면' },
  posterior:    { en: 'Back', ko: '후면' },
  lateral:      { en: 'Side', ko: '측면' },
  superior:     { en: 'Top', ko: '상면' },
  head:         { en: 'Head', ko: '머리' },
  wholeBody:    { en: 'Whole body', ko: '전신' },

  // controls
  atlasSlider:  { en: 'Colour-code structures', ko: '구조별 색상 표시' },
  sliceSlider:  { en: 'Slice through', ko: '단면 보기' },
  cutaway:      { en: 'Cutaway', ko: '단면' },
  xray:         { en: 'X-ray', ko: '투시' },
  labels:       { en: 'Labels', ko: '라벨' },
  rotate:       { en: 'Rotate', ko: '회전' },
  reset:        { en: 'Reset view', ko: '시점 초기화' },
  pathways:     { en: 'Pathways', ko: '경로' },
  register:     { en: 'Detail level', ko: '설명 수준' },
  regPlain:     { en: 'Plain', ko: '일반' },
  regClinical:  { en: 'Clinical', ko: '임상' },
  regBoth:      { en: 'Both', ko: '둘 다' },
  instruction:  { en: 'Show exercise instruction', ko: '운동 지도 내용 표시' },
  instructionOff: { en: 'Instruction hidden — anatomy and evidence only',
                    ko: '지도 내용 숨김 — 해부학과 근거만 표시' },

  // animation
  timeline:     { en: 'Movement', ko: '동작' },
  play:         { en: 'Play', ko: '재생' },
  pauseBtn:     { en: 'Pause', ko: '일시정지' },
  scrub:        { en: 'Scrub', ko: '탐색' },
  musclePaths:  { en: 'Muscle paths', ko: '근육 경로' },
  meshes:       { en: 'Muscle meshes', ko: '근육 메시' },
  noMotion:     { en: 'No movement clip for this exercise yet', ko: '이 운동의 동작 클립이 아직 없습니다' },
  handkeyed:    { en: 'Hand-keyed, not motion capture', ko: '수동 키프레임 · 모션캡처 아님' },
  handkeyedBody:{ en: 'These joint angles were authored against published movement descriptions and the joint definitions of the Rajagopal 2016 model. They are not motion capture and not inverse kinematics from measured data. The skeleton and the joint axes are published biomechanics; the pose over time is not. One thing about the rig is fitted rather than published: the rig and the body come from different projects, so each limb joint’s centre of rotation has been moved — by up to eleven centimetres, at the wrist — to the point that keeps this body’s own two bones together through the joint’s whole range. The rotation axes, the coupling and the published ranges are unchanged.',
                  ko: '이 관절 각도는 공개된 동작 기술과 Rajagopal 2016 모델의 관절 정의를 바탕으로 작성되었습니다. 모션캡처도, 측정 데이터로부터의 역운동학도 아닙니다. 골격과 관절 축은 공개된 생체역학이지만, 시간에 따른 자세는 그렇지 않습니다. 리그 중 한 가지는 공개 값이 아니라 이 신체에 맞춘 값입니다. 리그와 신체 모델은 서로 다른 프로젝트에서 만들어졌기 때문에, 각 사지 관절의 회전 중심을 이 신체의 두 뼈가 가동 범위 전체에서 맞물려 있도록 옮겼습니다(손목의 경우 최대 11 cm). 회전 축과 결합(coupling), 공개된 가동 범위는 그대로입니다.' },
  rigLimit:     { en: 'What this rig cannot show', ko: '이 리그가 표현할 수 없는 것' },
  meshWarn:     { en: 'Muscle meshes deform, but the weights were not authored',
                  ko: '근육 메시는 변형되지만 가중치는 저작된 값이 아닙니다' },
  meshWarnBody: { en: 'Muscle meshes are skinned to the rig, so a muscle crossing a joint bends with it instead of tearing open. The weights are not authored, though — the BodyParts3D meshes and the OpenSim rig were built by different projects and never met, so each vertex is weighted by its distance to the four nearest bones. That is a geometric approximation: it does not know about mesh connectivity, so it can bleed a little across a narrow gap between two structures that sit close together. Meshes are off by default here because seven hundred thousand triangles cost frames and because the muscle paths, not the meshes, are the source of truth for anything numeric.',
                  ko: '근육 메시는 리그에 스키닝되어 있어, 관절을 가로지르는 근육도 찢어지지 않고 함께 구부러집니다. 다만 가중치는 저작된 값이 아닙니다. BodyParts3D 메시와 OpenSim 리그는 서로 다른 프로젝트에서 만들어져 접점이 없으므로, 각 정점은 가장 가까운 네 개의 뼈까지의 거리로 가중됩니다. 이는 기하학적 근사이며 메시의 연결 구조를 알지 못해, 가까이 놓인 두 구조 사이의 좁은 틈에서 다소 번질 수 있습니다. 여기서 메시가 기본적으로 꺼져 있는 이유는 70만 개의 삼각형이 프레임을 소모하기 때문이며, 수치의 근거는 메시가 아니라 근육 경로이기 때문입니다.' },
  pathLength:   { en: 'Muscle–tendon length', ko: '근–건 길이' },
  pathRest:     { en: 'of its length at anatomical neutral', ko: '해부학적 중립 자세 대비' },
  maxForce:     { en: 'Max isometric force', ko: '최대 등척성 힘' },
  fiberLength:  { en: 'Optimal fibre length', ko: '최적 근섬유 길이' },
  pennation:    { en: 'Pennation angle', ko: '우모각' },
  osimSource:   { en: 'Muscle path model', ko: '근육 경로 모델' },
  breath:       { en: 'Breath', ko: '호흡' },
  phase:        { en: 'Phase', ko: '단계' },

  // structure detail
  does:         { en: 'What it does', ko: '하는 일' },
  sci:          { en: 'In clinical terms', ko: '임상 용어로' },
  feels:        { en: 'What it feels like', ko: '어떤 느낌인지' },
  origin:       { en: 'Origin', ko: '기시' },
  insertion:    { en: 'Insertion', ko: '정지' },
  innervation:  { en: 'Nerve supply', ko: '신경 지배' },
  actions:      { en: 'Actions', ko: '작용' },
  synergists:   { en: 'Works with', ko: '협력근' },
  antagonists:  { en: 'Opposed by', ko: '길항근' },
  dysfunction:  { en: 'When it goes wrong', ko: '문제가 생길 때' },
  travelUp:     { en: 'Follow the nerve to the brain', ko: '신경을 따라 뇌까지' },
  clinicalMore: { en: 'Clinical detail', ko: '임상 세부' },
  fmaId:        { en: 'FMA id', ko: 'FMA 식별자' },

  // exercise
  setup:        { en: 'Set-up', ko: '준비' },
  breath:       { en: 'Breath', ko: '호흡' },
  tempo:        { en: 'Tempo', ko: '템포' },
  faults:       { en: 'Common faults', ko: '흔한 오류' },
  contra:       { en: 'Contraindications', ko: '금기사항' },
  progressions: { en: 'Progressions', ko: '난이도 상승' },
  regressions:  { en: 'Regressions', ko: '난이도 하강' },
  focusCue:     { en: 'Cue', ko: '큐' },
  primeMovers:  { en: 'Prime movers', ko: '주동근' },
  synergistsEx: { en: 'Synergists', ko: '협력근' },
  stabilisers:  { en: 'Stabilisers', ko: '안정근' },
  /* Singular, for the tag on a label on the picture. The three above are panel headings over
   * a list and read wrong on one muscle. */
  roleTagPrime: { en: 'Prime mover', ko: '주동근' },
  roleTagSyn:   { en: 'Synergist', ko: '협력근' },
  roleTagStab:  { en: 'Stabiliser', ko: '안정근' },
  evEmg:        { en: 'measured by EMG', ko: '근전도로 측정됨' },
  evInferred:   { en: 'inferred from anatomy', ko: '해부학적 추론' },
  labAnalysis:  { en: 'What this exercise works', ko: '이 운동이 사용하는 것' },
  /* The 3D pair. Every caption on it has to say what kind of thing it is showing, because a
   * vertebra under a nerve root's name, or a joint centre under a muscle's, would be the quiet
   * substitution the whole panel exists to avoid. */
  /* Said in the connectome when a chosen region has no cells in it. The network is built from
   * the cortex's own vertices, so it has none for the cerebellum, the brainstem or any deep
   * structure — and a panel that showed nothing without saying that reads as broken. */
  labNoCells:   { en: 'not in this network. The cells are sampled from the cortex\u2019s own surface, so the cerebellum, the brainstem and the deep structures have none — they are separate meshes, not cortex.',
                  ko: '이 신경망에는 없습니다. 세포는 피질 표면 자체에서 추출하므로 소뇌, 뇌간, 심부 구조에는 세포가 없습니다. 이들은 피질이 아니라 별도의 메시입니다.' },
  labDetail:    { en: 'Every structure this exercise works, one at a time', ko: '이 운동이 쓰는 구조를 하나씩' },
  labDetPlay:   { en: 'Play through them', ko: '차례로 재생' },
  labDetPause:  { en: 'Stop here', ko: '여기서 멈춤' },
  labDetTurn:   { en: 'Drag either picture to turn it · scroll to zoom · click a name to jump to it',
                  ko: '두 그림 모두 끌어서 돌리고, 스크롤로 확대하며, 이름을 클릭하면 그 구조로 이동합니다' },
  labDetAlone:  { en: 'On its own', ko: '단독' },
  /* The joint's close view is the bones it articulates and nothing else — so the caption says
     so. It used to read "close on the joint, in the body", over a picture of the whole
     skeleton framed tightly, which is the wide view again at a shorter distance. */
  labDetClose:  { en: 'The bones this joint moves between', ko: '이 관절이 잇는 뼈' },
  labDetInBody: { en: 'Where it is, in the pose being held', ko: '현재 자세에서의 위치' },
  labDetPick:   { en: 'Click a muscle, a nerve, a cord level or a joint above and it is drawn here — by itself, and where it sits in the body.',
                  ko: '위에서 근육, 신경, 척수 분절, 관절을 클릭하면 여기에 그려집니다. 단독으로, 그리고 몸 안의 위치로.' },
  labDetLoading:{ en: 'Loading that layer \u2014 it is fetched the first time something in it is chosen.',
                  ko: '해당 레이어를 불러오는 중입니다. 그 안의 구조를 처음 선택할 때 가져옵니다.' },
  labDetNoMesh: { en: 'This model carries no separate shape for it, so there is nothing to draw.',
                  ko: '이 모델에는 이에 해당하는 별도의 형상이 없어 그릴 것이 없습니다.' },
  labDetMuscleW:{ en: 'A structure of this model, rendered from the loaded scene',
                  ko: '이 모델의 구조를 불러온 장면에서 렌더링' },
  labDetNerveW: { en: 'A nerve route of this model — Z-Anatomy, swept from its own curves',
                  ko: '이 모델의 신경 경로 — Z-Anatomy 곡선에서 생성' },
  labDetBrainW: { en: 'A brain structure of this model, in the frame the brain is placed in',
                  ko: '이 모델의 뇌 구조 — 뇌가 놓인 좌표계 기준' },
  labDetLevelW: { en: 'A nerve root is not a shape in this model, so this is the bone at that level',
                  ko: '신경근은 이 모델의 형상이 아니므로 해당 높이의 뼈를 보여줍니다' },
  labDetLevelOf:{ en: 'the vertebra at that level, not the root itself',
                  ko: '해당 높이의 척추뼈이며 신경근 자체가 아닙니다' },
  labDetJointW: { en: 'A joint is a centre of rotation, not a shape — so this is the bones it moves between, marked at that point. A regional spine coordinate drives every level of its region, and all of them are shown.',
                  ko: '관절은 형상이 아니라 회전 중심이므로, 그 관절이 잇는 뼈들을 회전 중심 표시와 함께 보여줍니다. 척추의 부위별 좌표는 그 부위의 모든 분절을 함께 움직이므로 전부 표시됩니다.' },
  labAnalPick:  { en: 'Choose an exercise and this fills in: the muscles it asks for, the joints it travels through, the nerves that supply those muscles, and the brain regions its own claims are about.',
                  ko: '운동을 선택하면 이곳이 채워집니다. 사용하는 근육, 움직이는 관절, 그 근육을 지배하는 신경, 그리고 그 운동의 주장이 다루는 뇌 영역이 표시됩니다.' },
  labAnalMuscles:{ en: 'Muscles', ko: '근육' },
  labAnalMusclesW:{ en: 'Share of the exercise\u2019s own authored activation curve, averaged across the movement. A role, not an EMG amplitude — the marker on each says whether a study measured that muscle here or it was reasoned from the anatomy. Click one to select it.',
                   ko: '이 운동에 기록된 활성 곡선을 동작 전체에 걸쳐 평균한 비율입니다. 근전도 진폭이 아니라 역할입니다. 각 항목의 표시는 해당 근육이 이 동작에서 실제로 측정되었는지, 해부학적으로 추론되었는지를 나타냅니다. 클릭하면 선택됩니다.' },
  labAnalJoints:{ en: 'Joints', ko: '관절' },
  labAnalJointsW:{ en: 'Measured off the clip: how far each joint travels from its lowest to its highest value through the movement, in degrees. A real measurement of this animation, which is hand-keyed against published range of motion and says so.',
                  ko: '동작 클립에서 직접 측정한 값입니다. 각 관절이 동작 중 최소에서 최대까지 몇 도를 움직이는지 나타냅니다. 이 애니메이션에 대한 실제 측정값이며, 애니메이션 자체는 공개된 가동범위에 맞춰 수작업으로 제작되었습니다.' },
  labAnalHeld:  { en: 'Nothing travels more than a degree — this exercise is a hold. The muscles are still loaded; look at the column to the left.',
                  ko: '1도 이상 움직이는 관절이 없습니다. 이 운동은 유지 동작입니다. 근육은 여전히 부하를 받고 있으니 왼쪽 열을 보십시오.' },
  labAnalRange: { en: 'from', ko: '범위' },
  labAnalNerves:{ en: 'Nerves and cord levels', ko: '신경과 척수 분절' },
  labAnalNervesW:{ en: 'The nerves that supply the muscles above, and the spinal roots they come from — quoted from Gray\u2019s Anatomy, muscle by muscle. This is anatomy, not activity: nothing in this application measures a nerve, so no nerve here carries a number. What it answers is which part of the nervous system has to be intact for this movement, and at which levels.',
                  ko: '위 근육들을 지배하는 신경과 그 신경이 나오는 척수 분절이며, 근육별로 그레이 해부학에서 인용했습니다. 활동이 아니라 해부학입니다. 이 앱은 신경을 측정하지 않으므로 어떤 신경에도 수치가 붙지 않습니다. 이 열이 답하는 것은 이 동작을 위해 신경계의 어느 부분이 어느 분절에서 온전해야 하는가입니다.' },
  labAnalNoNerve:{ en: 'No innervation is recorded for the muscles this exercise names.',
                  ko: '이 운동이 지목한 근육에 대해 기록된 지배신경 정보가 없습니다.' },
  /* The tour splits what the column joins, and it has to. A chip under a heading reading
     "Nerves" that draws a vertebra is a picture disagreeing with its label — "why do we have
     bones on the right instead of nerves?" was exactly that, asked about a T7 chip. A nerve
     here is a nerve; a cord level is a level, and its own picture and caption say that what
     is drawn is the bone at that level rather than the root. */
  labTourNerves:{ en: 'Nerves', ko: '신경' },
  labTourLevels:{ en: 'Cord levels — drawn as vertebrae',
                  ko: '척수 분절 — 척추뼈로 표시' },
  labAnalBrain: { en: 'Brain regions', ko: '뇌 영역' },
  labAnalBrainW:{ en: 'The regions this exercise\u2019s own brain claims are about, and how many of its claims name each one. A count of claims — not an activation, and not a measurement of anybody\u2019s brain. The letter is the strongest evidence tier among those claims. Click one to select it; they are marked in the brain view too.',
                  ko: '이 운동에 딸린 뇌 관련 주장이 다루는 영역과, 그 주장 중 몇 건이 각 영역을 지목하는지입니다. 주장의 개수이지 활성도가 아니며, 누군가의 뇌를 측정한 값도 아닙니다. 문자는 해당 주장들 중 가장 높은 근거 등급입니다. 클릭하면 선택되며, 뇌 화면에도 표시됩니다.' },
  labAnalNoBrain:{ en: 'This exercise carries no brain claims. That is a statement about the evidence, not about the exercise.',
                  ko: '이 운동에는 뇌 관련 주장이 없습니다. 이는 운동이 아니라 근거에 대한 진술입니다.' },
  labAnalWhy:   { en: 'The claims behind the brain column', ko: '뇌 영역 열의 근거가 되는 주장' },
  labBodyNone:  { en: 'Choose an exercise to see the body doing it', ko: '운동을 선택하면 몸이 그 동작을 하는 모습이 나옵니다' },
  labBodyLit:   { en: 'muscles lit', ko: '개 근육 점등' },
  labBodyMoving:{ en: 'joints moving', ko: '개 관절 이동' },
  labBodySame:  { en: 'the same scene as the main view, at the same instant — not a copy',
                  ko: '메인 화면과 동일한 장면을 같은 순간에 렌더링한 것이며 복사본이 아닙니다' },
  /* the instrument furniture — see hud.js. Every one of these reports something the app has
     actually loaded or is actually driving; none of them is a plausible-looking number. */
  trace:        { en: 'Network drive', ko: '신경망 구동' },
  traceNote:    { en: 'How hard this app is currently driving the cells you can see firing, 0 to 1, traced over the last few seconds. It rises when you select a region, run a scan, or load an exercise. It is a setting this animation is using — not a brain recording. There is no EEG or scanner anywhere in this application.',
                  ko: '지금 이 앱이 화면에서 발화하는 세포들을 얼마나 강하게 구동하고 있는지를 0에서 1까지로, 최근 몇 초간 기록한 것입니다. 영역을 선택하거나 스캔을 실행하거나 운동을 불러오면 올라갑니다. 이 애니메이션이 사용하는 설정값이지 뇌 기록이 아닙니다. 이 앱에는 뇌파도 장비도 스캐너도 없습니다.' },
  cellProbeLab: { en: 'Cell probe', ko: '세포 탐침' },
  sectCortexOnly: { en: 'outer surface only', ko: '바깥 표면만' },
  sectCortex:   { en: 'cortex — the folded outer sheet', ko: '피질 — 접힌 바깥층' },
  viewLeftLat:  { en: 'Left lateral view', ko: '좌측면' },
  viewRightLat: { en: 'Right lateral view', ko: '우측면' },
  viewAnt:      { en: 'Anterior view', ko: '전면' },
  viewPost:     { en: 'Posterior view', ko: '후면' },
  viewSup:      { en: 'Superior view', ko: '상면' },
  viewInf:      { en: 'Inferior view', ko: '하면' },
  frontRight:   { en: 'front at right', ko: '앞쪽이 오른쪽' },
  frontLeft:    { en: 'front at left', ko: '앞쪽이 왼쪽' },
  connHead:     { en: 'Region network', ko: '영역 네트워크' },
  connNone:     { en: 'The brain layer is off', ko: '뇌 레이어가 꺼져 있습니다' },
  connCount:    { en: 'regions', ko: '개 영역' },
  connLinks:    { en: 'links', ko: '개 연결' },
  labView:      { en: 'Lab view', ko: '실험실 보기' },
  labPanels:    { en: 'The lab, panel by panel', ko: '실험실 패널별 안내' },
  labTabCharts: { en: 'Charts', ko: '차트' },
  labTabRef:    { en: 'Reference', ko: '참고 자료' },
  aboutMore:    { en: 'Read the full reference', ko: '전체 참고 자료 보기' },
  aboutShort:   { en: 'Every control, every source and every number explained at length — in the Lab, where there is room for it.',
                  ko: '모든 조작·출처·수치에 대한 자세한 설명은 공간이 넉넉한 실험실 화면에 있습니다.' },
  body:         { en: 'Body', ko: '신체' },
  frameHeading: { en: 'Frame', ko: '좌표계' },
  frameBody:    { en: 'Body frame: origin at the ASIS midpoint, standing height',
                  ko: '신체 좌표계: 원점은 ASIS 중점, 선 자세 신장' },
  frameFit:     { en: 'Brain placed by a similarity transform fitted to structures present in both models — landmarks, mean and worst residual:',
                  ko: '뇌는 두 모델에 모두 있는 구조에 맞춘 상사 변환으로 배치됩니다. 기준점 수, 평균 및 최대 잔차:' },
  labTitle:     { en: 'Lab', ko: '실험실' },
  labSub:       { en: 'The network and the movement at full size. Every panel is drawn from what this application holds — there are no assessment scores here, and none have been invented.',
                  ko: '신경망과 동작을 전체 크기로 봅니다. 모든 패널은 이 앱이 실제로 가진 데이터로 그려집니다. 평가 점수는 여기에 없으며, 지어내지도 않았습니다.' },
  labConnectome:{ en: 'Neural connectome', ko: '신경 연결 지도' },
  labConnectomeNote: { en: 'Every cell placed on a ring by the region it came from, each parcel taking a share of the ring equal to its share of the cells; the chords are the axons that cross between parcels. Not tractography — these are this network’s own links, not measured fibre pathways. Hover an arc to trace what it connects; click to select that region in the model.',
                       ko: '모든 세포를 출신 영역에 따라 고리 위에 배치하며, 각 영역이 차지하는 호의 길이는 세포 비율과 같습니다. 현은 영역 사이를 건너는 축삭입니다. 신경섬유 추적이 아닙니다. 측정된 섬유 경로가 아니라 이 신경망 자체의 연결입니다. 호에 마우스를 올리면 무엇과 이어지는지 보이고, 클릭하면 모델에서 그 영역이 선택됩니다.' },
  labRegionMap: { en: 'Region map', ko: '영역 지도' },
  labRegionMapNote: { en: 'The same network with each region at its own position, on a lateral render of the brain itself — the fsaverage surface and every deep structure, drawn from the same geometry the main view uses. Front is right. Dot size is how many cells that region holds; line weight is how many links run between two of them.',
                      ko: '같은 신경망을 각 영역의 실제 위치에 놓고, 뇌 자체를 옆에서 렌더링한 그림 위에 얹었습니다. fsaverage 표면과 모든 깊은 구조를 메인 화면과 같은 지오메트리로 그린 것입니다. 오른쪽이 앞입니다. 점의 크기는 그 영역의 세포 수이고, 선의 굵기는 두 영역 사이 연결 수입니다.' },
  labJoints:    { en: 'Joint angles through the movement', ko: '동작 중 관절 각도' },
  labJointsNote:{ en: 'What each joint the clip drives is doing, in degrees, from the start of the exercise to the end. The dashed line is neutral; the coloured uprights are where the breath turns over. These are the angles the figure on screen is actually posed to — hand-keyed against published movement descriptions, not motion capture.',
                  ko: '클립이 움직이는 각 관절이 운동의 처음부터 끝까지 무엇을 하는지 도(度) 단위로 보여줍니다. 점선은 중립이고, 색이 있는 세로선은 호흡이 바뀌는 지점입니다. 화면 속 인물이 실제로 취하는 각도이며, 공개된 동작 기술을 바탕으로 수동 입력한 값이지 모션캡처가 아닙니다.' },
  labMuscles:   { en: 'Muscle role through the movement', ko: '동작 중 근육 역할' },
  labMusclesNote: { en: 'The busiest six muscles across the clip. The vertical axis is a role — prime mover, synergist, stabiliser — taken from the exercise record. It is not EMG amplitude, not a percentage of maximum, and not a measurement of any person.',
                    ko: '클립 전체에서 가장 활발한 근육 여섯 개입니다. 세로축은 역할(주동근·협력근·안정근)이며 운동 기록에서 가져온 값입니다. 근전도 진폭도, 최대치 대비 백분율도, 특정인에 대한 측정값도 아닙니다.' },
  labEvidence:  { en: 'How strong the evidence is', ko: '근거의 강도' },
  labTraceHint: { en: 'Click a cell in the plot above to trace that one', ko: '위 그래프에서 세포를 클릭하면 그 세포를 추적합니다' },
  labTraceCell: { en: 'The cell you picked', ko: '선택한 세포' },
  /* Opening on a cell rather than on an empty panel, so the heading has to say who chose it
   * and on what. The count is of this model's own fibres and nothing else — see `hubOf`. */
  labTraceAutoCell: { en: 'Opened on this region\u2019s most connected cell', ko: '이 영역에서 연결이 가장 많은 세포로 시작' },
  labTraceAt:   { en: 'at', ko: '위치' },
  labTraceFibres: { en: 'fibres leave it, nearest first', ko: '개 섬유가 나갑니다 (가까운 순)' },
  labTraceReaches: { en: 'It reaches', ko: '도달 영역' },
  labTraceOther:{ en: 'other regions', ko: '개 (다른 영역)' },
  labTraceLocal:{ en: 'Every fibre lands in its own region — most of this network is local.',
                  ko: '모든 섬유가 자기 영역 안에 도달합니다. 이 신경망은 대부분 국소 연결입니다.' },
  labTraceMore: { en: 'more', ko: '개 더' },
  labTraceClaims:{ en: 'claims attached to this region', ko: '개 주장이 이 영역에 연결됨' },
  labTraceBest: { en: 'best evidence', ko: '최고 근거 등급' },
  labTraceDash: { en: 'dashed = a long-range fibre', ko: '점선 = 장거리 섬유' },
  labTraceSpeedH:{ en: 'How fast the band moves', ko: '띠의 이동 속도' },
  labTraceCross:{ en: 'to cross a fibre', ko: '에 섬유 하나를 통과' },
  labTraceOnScreen:{ en: 'on screen', ko: '(화면 기준)' },
  labTraceSpeedNote:{ en: 'That is the animation\u2019s own rate — the number this application draws the band with. It is not a conduction velocity and nothing here measured one. A real cortical axon conducts at roughly 0.5 m/s unmyelinated to 120 m/s myelinated (Kandel et al., Principles of Neural Science, 5th ed.), which would cross a fibre this long in well under a millisecond: about a million times faster than what you are watching. The band is slowed to the point of being visible, which is the only reason it is on the screen at all.',
                     ko: '이것은 애니메이션 자체의 속도이며, 이 앱이 띠를 그리는 데 쓰는 숫자입니다. 전도 속도가 아니고, 여기서 전도 속도를 측정한 적도 없습니다. 실제 피질 축삭은 무수초의 경우 약 0.5 m/s, 유수초의 경우 최대 120 m/s로 전도하며(Kandel 외, Principles of Neural Science 5판), 이 정도 길이의 섬유는 1밀리초도 걸리지 않고 통과합니다. 지금 보고 있는 것보다 약 100만 배 빠릅니다. 띠는 눈에 보이도록 느리게 만든 것이며, 그것이 화면에 있는 유일한 이유입니다.' },
  labTraceClear:{ en: 'Click empty space in the plot above to clear', ko: '위 그래프의 빈 곳을 클릭하면 해제됩니다' },
  labNoParcel:  { en: 'unparcellated cortex', ko: '분할되지 않은 피질' },
  labSections:  { en: 'The cuts, and what they show', ko: '단면과 그 의미' },
  sectWhatLineH:   { en: 'A bright line', ko: '밝은 선' },
  sectWhatLine:    { en: 'is where the flat plane crosses a surface. It is a cut edge — the outline you would see if you sliced the model there and looked straight down at the cut face. Nothing has been removed; the line is computed where the surface and the plane meet.',
                     ko: '평면이 표면과 만나는 곳입니다. 잘린 가장자리, 즉 모델을 그 자리에서 잘라 절단면을 정면에서 봤을 때 보이는 윤곽입니다. 실제로 잘라낸 것은 없으며, 선은 표면과 평면이 만나는 지점에서 계산됩니다.' },
  sectWhatBrightH: { en: 'A brighter patch', ko: '더 밝은 부분' },
  sectWhatBright:  { en: 'is several surfaces crossing the plane close together. The outer sheet of the brain is folded back on itself over and over, so one cut passes through it many times in a small space, and those crossings add up. Bright means densely folded, not more active.',
                     ko: '여러 표면이 가까이서 평면을 가로지르는 곳입니다. 뇌의 바깥 껍질은 몇 번이고 접혀 있어서 한 번의 절단이 좁은 공간에서 그것을 여러 번 통과하며, 그 교차가 누적됩니다. 밝다는 것은 촘촘히 접혀 있다는 뜻이지 더 활동적이라는 뜻이 아닙니다.' },
  sectWhatDarkH:   { en: 'Black', ko: '검은 부분' },
  sectWhatDark:    { en: 'is where the plane crosses no surface at that depth — the fluid spaces inside the brain, the gap between two folds that face each other, and everything outside the head. It is an absence of surface, not an absence of tissue: this model holds surfaces and not a filled volume, so the inside of a solid structure is as black as the air around it.',
                     ko: '그 깊이에서 평면이 어떤 표면과도 만나지 않는 곳입니다. 뇌 안의 뇌척수액 공간, 마주 보는 두 주름 사이의 틈, 그리고 머리 바깥 전부가 여기에 해당합니다. 조직이 없다는 뜻이 아니라 표면이 없다는 뜻입니다. 이 모델은 채워진 부피가 아니라 표면만 가지고 있어서, 단단한 구조물의 내부도 주변 공기와 똑같이 검게 보입니다.' },
  sectWhatColourH: { en: 'The colours', ko: '색' },
  sectWhatColour:  { en: 'name the structure. Each one is drawn in its own colour — the same colour it wears everywhere else in this application — so a bright shape in a cut identifies itself. The list under each picture names what that cut actually passes through, measured off this model rather than quoted from an atlas.',
                     ko: '구조를 구분합니다. 각 구조는 이 앱의 다른 화면에서와 같은 자기 색으로 그려지므로, 단면의 밝은 모양이 스스로 무엇인지 알려줍니다. 각 그림 아래 목록은 그 절단이 실제로 지나는 구조이며, 아틀라스에서 인용한 것이 아니라 이 모델에서 측정한 것입니다.' },
  sectWhatNumberH: { en: 'The number', ko: '숫자' },
  sectWhatNumber:  { en: 'is how far that cut is from the middle of the cortex, in millimetres, measured along the direction of the cut. Zero is the centre. These are distances in the fsaverage brain this surface was built from.',
                     ko: '그 절단이 피질 중심에서 얼마나 떨어져 있는지를 절단 방향으로 잰 밀리미터 값입니다. 0이 중심입니다. 이 표면을 만든 fsaverage 뇌에서의 거리입니다.' },
  /* The picture is the control now, so this says so first: pointing at a shape names it and
   * clicking it chooses it. Naming the key and the rest of the app second, because a reader
   * looking at a bright shape is asking about *that shape*. */
  labSectChoose:{ en: 'Point at any shape in a cut to name it, and click it to choose it — or pick one from the key above, or anywhere in the app. Whatever is chosen is lit in every cut that passes through it, and the line here says which cuts those are. Clicking a picture anywhere else moves the big plane to that depth.',
                  ko: '단면 속 아무 모양이나 가리키면 이름이 나오고, 클릭하면 선택됩니다. 위 범례나 앱 어디에서든 골라도 됩니다. 선택된 구조는 그것을 지나는 모든 단면에서 밝게 표시되고, 여기 문장이 어느 단면인지 알려줍니다. 그림의 다른 곳을 클릭하면 큰 평면이 그 깊이로 이동합니다.' },
  labSectIn:    { en: 'is in the cut at', ko: '다음 단면에 있습니다:' },
  labSectInPl:  { en: 'is in the cuts at', ko: '다음 단면들에 있습니다:' },
  labSectSpans: { en: 'running from', ko: '범위는' },
  labSectTo:    { en: 'to', ko: '~' },
  labSectThick: { en: 'across', ko: '두께' },
  labSectBetween:{ en: 'sits between', ko: '위치는' },
  labSectMissed:{ en: 'none of these five cuts happens to land inside it. Switch the plane, or drag the scan slider in the main view to that depth.',
                  ko: '이 다섯 단면 중 어느 것도 그 안에 들어가지 않습니다. 절단 방향을 바꾸거나, 메인 화면의 스캔 슬라이더를 그 깊이로 옮겨 보세요.' },
  labSectNoMesh:{ en: 'is not one of the structures this series can cut: the cuts are through the brain, and this is elsewhere in the body.',
                  ko: '이 시리즈가 자를 수 있는 구조가 아닙니다. 이 단면은 뇌를 자른 것이고, 이 구조는 몸의 다른 곳에 있습니다.' },
  sectWhatPointH:  { en: 'What it is for', ko: '무엇에 쓰는가' },
  sectWhatPoint:   { en: 'A section answers the one question the outside of a brain cannot: what is at this depth, and in what order. Deep structures — the thalamus, the hippocampus, the ventricles — are invisible from any angle outside, and a cut through the middle is where they appear. Click a picture to move the big plane in the main view to that depth.',
                     ko: '단면은 뇌를 바깥에서 보아서는 답할 수 없는 질문에 답합니다. 이 깊이에 무엇이 있고, 어떤 순서로 있는가입니다. 시상, 해마, 뇌실 같은 깊은 구조는 바깥의 어느 각도에서도 보이지 않으며, 가운데를 자른 단면이 그것들이 나타나는 곳입니다. 그림을 클릭하면 메인 화면의 큰 평면이 그 깊이로 이동합니다.' },
  labFibres:    { en: 'Every cell, every fibre', ko: '모든 세포, 모든 섬유' },
  labFibreX:    { en: 'back  ←   millimetres from the centre of the cortex   →  front',
                  ko: '뒤  ←   피질 중심에서의 밀리미터   →  앞' },
  labFibreY:    { en: 'down  ←   millimetres   →  up', ko: '아래  ←   밀리미터   →  위' },
  labFibreCount:{ en: 'fibres drawn', ko: '개 섬유' },
  labFibreLR:   { en: 'right  ←   millimetres across the midline   →  left',
                  ko: '오른쪽  ←   정중선 기준 밀리미터   →  왼쪽' },
  labFibreLR2:  { en: 'right  ←   millimetres across the midline   →  left',
                  ko: '오른쪽  ←   정중선 기준 밀리미터   →  왼쪽' },
  fibViewSide:  { en: 'From the side', ko: '옆에서' },
  fibViewAbove: { en: 'From above', ko: '위에서' },
  fibViewFront: { en: 'From the front', ko: '앞에서' },
  fibReset:     { en: 'Reset', ko: '초기화' },
  labCellNo:    { en: 'Cell', ko: '세포' },
  labRegionCells:{ en: 'The cells of one region', ko: '한 영역의 세포들' },
  labRegionPick: { en: 'Choose a region — click one in the plot above, in the map, or in the 3D view',
                   ko: '영역을 고르세요 — 위 그래프나 지도, 3D 화면에서 클릭하면 됩니다' },
  labRegionNoCells:{ en: 'That structure holds no cells in this model — the network samples the folded outer sheet only',
                     ko: '이 모델에서 해당 구조에는 세포가 없습니다 — 신경망은 접힌 바깥 껍질만 표본으로 삼습니다' },
  labRcWithin:  { en: 'fibres inside it', ko: '개 내부 섬유' },
  labRcOut:     { en: 'leaving it', ko: '개 외부 연결' },
  labRcPick:    { en: 'click a cell to trace it', ko: '세포를 클릭하면 추적합니다' },
  labFibrePick: { en: 'click a cell to trace it', ko: '세포를 클릭하면 추적합니다' },
  labCellKey:   { en: 'One cell, traced', ko: '세포 하나, 추적' },
  labRoster:    { en: 'Cells by region', ko: '영역별 세포 수' },
  keySoma:      { en: 'cell body', ko: '세포체' },
  keyArbor:     { en: 'its branches', ko: '가지' },
  keyFibre:     { en: 'fibre between them', ko: '둘을 잇는 섬유' },
  keyBand:      { en: 'the travelling band', ko: '이동하는 띠' },
  keyTarget:    { en: 'the cell it reaches', ko: '도달하는 세포' },
  labOf:        { en: 'of', ko: '중' },
  labEffect:    { en: 'How big', ko: '효과 크기' },
  labWho:       { en: 'Who was tested', ko: '시험 대상' },
  labSpecies:   { en: 'In whom', ko: '대상 종' },
  labOver:      { en: 'Over what time', ko: '기간' },
  labSpHuman:   { en: 'people', ko: '사람' },
  labSpAnimal:  { en: 'animals only', ko: '동물 한정' },
  labTsAcute:   { en: 'one session', ko: '단회 운동' },
  labTsChronic: { en: 'weeks to months of training', ko: '수 주–수 개월 훈련' },
  labCaveat:    { en: 'What it does not show', ko: '이 근거로 말할 수 없는 것' },
  labAbout:     { en: 'About', ko: '관련 부위' },
  tierPlainA:   { en: 'Many people tested, results pooled', ko: '다수를 대상으로 시험하고 결과를 종합' },
  tierPlainB:   { en: 'One good human trial', ko: '사람 대상 양질의 시험 1건' },
  tierPlainC:   { en: 'Seen in people, but small', ko: '사람에게서 관찰되었으나 소규모' },
  tierPlainD:   { en: 'Only shown in animals', ko: '동물에서만 확인' },
  tierPlainE:   { en: 'Reasoned, not tested', ko: '추론일 뿐 검증되지 않음' },
  labEvidenceNote: { en: 'Every brain claim in this library, in full, grouped by how well it is established — with the effect size, who was tested, what the study does not show, and the paper it came from. This is the least flattering panel here and it is the one that most has to exist: a screen of luminous graphs invites you to take all of it as established, and this says in the same visual language how much of it is not. Nothing here was measured on you.',
                     ko: '이 라이브러리의 모든 뇌 관련 주장을 전문 그대로, 근거의 확립 정도별로 묶었습니다. 효과 크기, 시험 대상, 그 연구로는 말할 수 없는 것, 출처 논문이 함께 있습니다. 여기서 가장 돋보이지 않는 패널이지만 가장 필요한 패널입니다. 빛나는 그래프로 가득한 화면은 모든 것이 확립된 사실인 것처럼 믿게 만들고, 이 패널은 그중 얼마나 많은 것이 그렇지 않은지를 같은 시각 언어로 말합니다. 여기 있는 어떤 것도 당신에게서 측정된 것이 아닙니다.' },
  labClaims:    { en: 'Brain claims', ko: '뇌 관련 주장' },
  labExercises: { en: 'Exercises', ko: '운동' },
  labCells:     { en: 'cells', ko: '개 세포' },
  labHoverHint: { en: 'Hover an arc', ko: '호 위에 마우스를 올리세요' },
  c3dHint:      { en: 'Drag to turn · scroll to zoom · click a cell to select its region', ko: '드래그로 회전 · 스크롤로 확대 · 세포를 클릭하면 그 영역이 선택됩니다' },
  labLeftHemi:  { en: 'fibres starting left', ko: '좌반구에서 출발하는 섬유' },
  labRightHemi: { en: 'fibres starting right', ko: '우반구에서 출발하는 섬유' },
  labNoClip:    { en: 'Choose an exercise to plot its movement', ko: '운동을 선택하면 동작이 표시됩니다' },
  labNoMotion:  { en: 'This clip holds its joints still', ko: '이 클립은 관절을 고정한 채 유지합니다' },
  labAnterior:  { en: 'front', ko: '앞' },
  labPosterior: { en: 'back', ko: '뒤' },
  hudStructures:{ en: 'Structures', ko: '구조' },
  hudRegions:   { en: 'Regions', ko: '영역' },
  hudNodes:     { en: 'Cells', ko: '세포' },
  hudFocus:     { en: 'Focus', ko: '초점' },
  /* the scan plane. Named for the section each one produces, which is the convention in
     imaging and the opposite of naming it for the plane's own normal. */
  scan:         { en: 'Scan plane', ko: '스캔 평면' },
  scanOff:      { en: 'Off', ko: '끔' },
  scanSagittal: { en: 'Sagittal', ko: '시상면' },
  scanCoronal:  { en: 'Coronal', ko: '관상면' },
  scanAxial:    { en: 'Axial', ko: '수평면' },
  scanSweep:    { en: 'Sweep', ko: '스윕' },
  cutSagittal:  { en: 'left | right', ko: '좌 | 우' },
  cutCoronal:   { en: 'front | back', ko: '앞 | 뒤' },
  cutAxial:     { en: 'top | bottom', ko: '위 | 아래' },
  brainLookLab: { en: 'Brain look', ko: '뇌 표현' },
  lookTissue:   { en: 'See-through', ko: '투과' },
  lookAnatomical: { en: 'Solid atlas', ko: '불투명 아틀라스' },
  lookNeurons:  { en: 'Cells only', ko: '세포만' },
  helpPlain:    { en: 'What it does', ko: '하는 일' },
  helpTech:     { en: 'What it is', ko: '기술적 설명' },
  readingHead:  { en: 'Reading the instrument', ko: '계기 읽는 법' },
  readingIntro: { en: 'Every control and every readout in this application, in both registers. Which of the two you see is set by Detail level below; choose Both to see them side by side.',
                  ko: '이 앱의 모든 조작과 표시값을 두 가지 방식으로 설명합니다. 어느 쪽을 볼지는 아래의 상세 수준에서 정하며, 둘 다를 고르면 나란히 표시됩니다.' },
  sections:     { en: 'Sections', ko: '단면' },
  sectionsNote: { en: 'Sections of the model’s own surfaces, cut where the plane crosses them. Not an MRI — there is no imaging data in this application. Click one to move the plane.',
                  ko: '이 모델 표면을 평면이 지나는 지점에서 자른 단면입니다. MRI가 아니며, 이 앱에는 영상 데이터가 없습니다. 하나를 클릭하면 평면이 이동합니다.' },
  scanAt:       { en: 'Position', ko: '위치' },
  /* The one per-cell number that is real: what the shader has this soma doing right now.
     Called a state rather than a measurement, because that is what it is. */
  cellFiring:   { en: 'Firing', ko: '발화' },
  difficulty:   { en: 'Difficulty', ko: '난이도' },
  apparatus:    { en: 'Apparatus', ko: '기구' },

  /* the label filter — four hundred structures share two lanes, so a reader has to be able
   * to ask for one system at a time */
  showLabels:   { en: 'Label', ko: '이름표' },
  labelHint:    { en: 'Choose which systems are named on the picture.',
                  ko: '그림에 어느 계통의 이름을 표시할지 고르세요.' },
  kindBone:     { en: 'Bones', ko: '뼈' },
  kindMuscle:   { en: 'Muscles', ko: '근육' },
  kindNerve:    { en: 'Nerves', ko: '신경' },
  kindOrgan:    { en: 'Organs', ko: '장기' },
  kindBrain:    { en: 'Brain', ko: '뇌' },
  seeInside:    { en: 'See inside', ko: '내부 보기' },
  seeInsideOff: { en: 'Solid', ko: '불투명' },

  /* the library browser — two hundred entries need finding, not scrolling */
  searchEx:     { en: 'Search exercises', ko: '운동 검색' },
  searchHint:   { en: 'Name, Sanskrit, family or muscle', ko: '이름, 산스크리트, 계열, 근육' },
  filterAll:    { en: 'All', ko: '전체' },
  filterDisc:   { en: 'Discipline', ko: '분야' },
  filterApp:    { en: 'Equipment', ko: '기구' },
  filterActive: { en: 'Filtering by', ko: '적용 중' },
  filterFamily: { en: 'Family', ko: '계열' },
  filterProps:  { en: 'Props', ko: '도구' },
  filterLevel:  { en: 'Level', ko: '난이도' },
  clearFilters: { en: 'Clear filters', ko: '필터 초기화' },
  noMatches:    { en: 'Nothing matches those filters.', ko: '조건에 맞는 운동이 없습니다.' },
  showingN:     { en: 'showing', ko: '표시' },
  ofN:          { en: 'of', ko: '/' },
  composedNote: { en: 'Written from a structured record',
                  ko: '구조화된 기록에서 작성됨' },
  composedBody: { en: 'This entry’s prose is composed from a record of the exercise — the joints it moves and through what range, the muscles in each role with their evidence marker, the contraindication classes, the breath pattern — through a shared vocabulary, in both languages. The animation is built from the same joint angles, so the picture and the text cannot disagree. The record is the content; the sentences are a rendering of it.',
                  ko: '이 항목의 문장은 운동의 구조화된 기록에서 작성되었습니다. 어떤 관절이 어느 범위로 움직이는지, 각 역할의 근육과 근거 표시, 금기 분류, 호흡 패턴을 공유 어휘를 통해 두 언어로 구성합니다. 애니메이션도 같은 관절 각도에서 만들어지므로 그림과 글이 어긋날 수 없습니다. 기록이 곧 내용이며 문장은 그 표현입니다.' },
  sanskrit:     { en: 'Sanskrit', ko: '산스크리트' },
  jointRanges:  { en: 'Where each joint limit comes from', ko: '각 관절 한계의 출처' },
  jointRangesBody: { en: 'Every joint in the rig records whether its range is the OpenSim model’s own or a published one. Six coordinates take published goniometry rather than the model’s: the model was built to simulate walking, and walking never lifts an arm overhead, folds a knee past 120 degrees or a hip past 120, so those caps describe the search the solver was given rather than the joint. The 24 vertebral joints have no model limits at all — the model has one lumbar joint — so all of them are published. Nothing the model actually measures has been widened.',
                     ko: '리그의 모든 관절은 그 가동범위가 OpenSim 모델 자체의 값인지 공표된 값인지를 기록합니다. 6개 좌표는 모델 대신 공표된 관절각 측정값을 사용합니다. 이 모델은 보행 시뮬레이션을 위해 만들어졌고, 보행에서는 팔을 머리 위로 들거나 무릎을 120도 이상 굽히거나 고관절을 120도 이상 접는 일이 없으므로, 그 상한은 관절이 아니라 해석에 주어진 탐색 범위를 나타냅니다. 24개 척추 관절은 모델에 상응하는 한계가 아예 없으므로(모델의 요추 관절은 하나뿐입니다) 전부 공표된 값입니다. 모델이 실제로 측정한 값은 넓히지 않았습니다.' },
  playPhases:   { en: 'Play phases', ko: '단계 재생' },
  pause:        { en: 'Pause', ko: '일시정지' },
  notReviewed:  { en: 'Not yet reviewed by a qualified instructor',
                  ko: '아직 전문 지도자의 검토를 받지 않았습니다' },
  notReviewedBody: { en: 'The cueing, faults and contraindications on this exercise have been written from published anatomy and biomechanics but have not been signed off by a certified instructor. Treat them as a description of the movement, not as instruction to perform it.',
                     ko: '이 운동의 큐, 오류, 금기사항은 공개된 해부학과 생체역학을 바탕으로 작성되었으나 자격을 갖춘 지도자의 검토를 거치지 않았습니다. 수행 지시가 아니라 동작에 대한 설명으로 받아들이십시오.' },
  reviewedBy:   { en: 'Reviewed by', ko: '검토' },

  // activation legend
  activation:   { en: 'Muscle role', ko: '근육 역할' },
  activationNote: { en: 'This scale shows the role a muscle plays in the movement — prime mover, synergist or stabiliser — not a measured activation level. It is not EMG amplitude and it is not a percentage of maximum. Where a role was measured, the muscle carries an EMG marker.',
                    ko: '이 척도는 근육이 동작에서 맡는 역할(주동근·협력근·안정근)을 나타내며 측정된 활성 수준이 아닙니다. 근전도 진폭도 최대치 대비 백분율도 아닙니다. 측정된 역할에는 근전도 표시가 붙습니다.' },
  chartHead:    { en: 'Muscle role across the movement', ko: '동작 전체에 걸친 근육 역할' },
  chartNote:    { en: 'Each line is one muscle through the clip, read from the same values the picture is using — the clip states a role at each keyframe and the curve between them is interpolated, not sampled. The busiest six are drawn; the rest are in the lists below. The vertical axis is the role scale above, so it is not an EMG amplitude, not a percentage of maximum, and not a measurement of anyone. The upright line is where the body on screen is in the movement.',
                  ko: '각 선은 클립 전체에 걸친 하나의 근육이며, 화면의 그림이 사용하는 것과 같은 값을 읽은 것입니다. 클립은 각 키프레임에서 역할을 명시하고, 그 사이의 곡선은 측정이 아니라 보간된 값입니다. 가장 활발한 여섯 개만 그려지며 나머지는 아래 목록에 있습니다. 세로축은 위의 역할 척도이므로 근전도 진폭도, 최대치 대비 백분율도, 특정인에 대한 측정값도 아닙니다. 수직선은 화면 속 신체가 동작의 어느 지점에 있는지를 나타냅니다.' },
  chartNone:    { en: 'This clip names no muscle values', ko: '이 클립에는 근육별 값이 없습니다' },

  // evidence
  tier:         { en: 'Evidence tier', ko: '근거 등급' },
  claim:        { en: 'Claim', ko: '주장' },
  mechanism:    { en: 'Mechanism', ko: '기전' },
  effect:       { en: 'Effect size', ko: '효과 크기' },
  population:   { en: 'Who was studied', ko: '연구 대상' },
  caveat:       { en: 'What this does not show', ko: '이것이 보여주지 않는 것' },
  source:       { en: 'Source', ko: '출처' },
  human:        { en: 'Human', ko: '인체' },
  animal:       { en: 'Animal', ko: '동물' },
  acute:        { en: 'Single bout', ko: '단회 운동' },
  chronic:      { en: 'Over a programme', ko: '프로그램 기간' },

  // pathway
  pathSchematic: { en: 'These arcs are a diagram, not a traced nerve',
                   ko: '이 곡선은 도식이며 추적한 신경이 아닙니다' },
  pathSchematicBody: { en: 'The endpoints are real — a measured brain region, a real vertebral level, a real muscle. The curve between them is drawn to show the connection, not traced from imaging. The source atlas contains no peripheral nervous system, and drawing one would mean inventing anatomy.',
                       ko: '끝점은 실제입니다. 측정된 뇌 영역, 실제 척추 분절, 실제 근육입니다. 그 사이의 곡선은 연결을 보여주기 위해 그린 것이지 영상에서 추적한 것이 아닙니다. 출처 아틀라스에는 말초신경계가 없으며, 그것을 그리는 것은 해부학을 지어내는 일입니다.' },

  // misc
  loading:      { en: 'Loading anatomy…', ko: '해부 모델 불러오는 중…' },
  explore:      { en: 'Click anything', ko: '아무거나 클릭해 보세요' },
  exploreBody:  { en: 'Every bone, muscle and organ here is individually selectable. Pick one to see what it does, what moves it, and which nerve carries the command.',
                  ko: '여기 모든 뼈, 근육, 장기를 개별적으로 선택할 수 있습니다. 하나를 골라 무슨 일을 하고 무엇이 움직이며 어떤 신경이 명령을 전달하는지 확인하세요.' },
  noContent:    { en: 'No written entry for this structure yet',
                  ko: '이 구조에 대한 설명이 아직 없습니다' },
  noContentBody:{ en: 'It is in the model with its FMA identifier and it is selectable, but nobody has written the anatomy up yet. The named muscles in the exercise library all have entries.',
                  ko: 'FMA 식별자와 함께 모델에 포함되어 있고 선택도 가능하지만 아직 해부학 설명이 작성되지 않았습니다. 운동 라이브러리에서 언급되는 근육은 모두 설명이 있습니다.' },
  sources:      { en: 'Sources and licences', ko: '출처 및 라이선스' },
  bodiesHeading:{ en: 'Bodies', ko: '인체 모델' },
  bodyShown:    { en: 'shown now', ko: '현재 표시 중' },
  bodyShow:     { en: 'show this body', ko: '이 인체 보기' },
  report:       { en: 'Print take-home', ko: '요약 인쇄' },
  reportBlocked:{ en: 'The print window was blocked. Allow pop-ups for this page and try again.',
                  ko: '인쇄 창이 차단되었습니다. 이 페이지의 팝업을 허용한 뒤 다시 시도하세요.' },
  close:        { en: 'Close', ko: '닫기' },
  structures:   { en: 'structures', ko: '개 구조' },
};
