"""Fit BodyParts3D 4.0 onto BodyParts3D 3.0, so the two halves of this atlas agree.

The taught body comes from release 3.0 (`build_body.py`); everything else -- the vessels,
the airways, the cartilage, the finer detail, and the whole complete atlas -- comes from
release 4.0 (`build_detail.py`). They are the same cadaver, but the two releases are not
delivered in the same frame, and this project's two build paths did not put them in one.

Measured over the 179 bones that carry the same name in both, the complete atlas sits
**14 mm low on average and 44 mm low at the foot**, because the offset grows down the leg.
On screen that is a second leg inside the first: the taught skeleton and the 4.0 arteries,
veins and nerves at the ankle are four centimetres apart, and the foot appears twice.

So this solves one similarity -- rotation, uniform scale, translation, by Umeyama, the same
method `build_nervous.py` uses to bring Z-Anatomy in -- from every shared bone, and writes it
where the loader can apply it. Nothing is removed and nothing is redrawn: the 4.0 geometry is
moved onto the body the rig, the exercises, the Korean names and the nerves are all keyed to.

    python3 scripts/fit_atlases.py [--write]

Run it again whenever either half is rebuilt.
"""
import argparse
import json
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from derive_frame import umeyama

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, 'src', 'generated', 'structures.json')
OUT = os.path.join(ROOT, 'src', 'generated', 'atlas_fit.js')

#: The taught body, from release 3.0. The frame everything else is moved onto.
TAUGHT = 'skeleton'
#: Its counterpart in the complete atlas, and the only layer with names to match on.
COMPLETE = 'bones_full'
#: Every layer `build_detail.py` emits -- all of them carry the 4.0 frame, which is why
#: correcting it fixes the vessels and the cartilage as well as the complete atlas.
FITTED = ('arteries', 'veins', 'airways', 'connective', 'nerves_cranial',
          'heart_detail', 'detail', 'bones_full', 'muscles_full', 'organs_full')

SIDED = re.compile(r'^(left|right)\s+', re.I)


def pairs(rows):
    """Bones present in both releases, keyed by name and side.

    The complete atlas sides its pieces -- "left talus" against 3.0's fused "talus", which
    carries a centroid per side -- so the side is part of the key and the prefix is stripped
    to match. A long bone's centroid moves when the two releases cut it differently, which
    is why the fit is over 179 of them rather than the handful `build_nervous.py` needs.
    """
    taught, complete = {}, {}
    for r in rows:
        for side, c in (r.get('perSide') or {}).items():
            nm = r['name'].lower()
            if r['layer'] == TAUGHT:
                taught[(nm, side)] = c
            elif r['layer'] == COMPLETE:
                complete[(SIDED.sub('', nm), side)] = c
    keys = sorted(set(taught) & set(complete))
    return keys, np.array([complete[k] for k in keys]), np.array([taught[k] for k in keys])


def fit(rows):
    keys, source, target = pairs(rows)
    if len(keys) < 12:
        raise SystemExit(f'only {len(keys)} shared bones -- not enough to fit a frame')
    scale, rot, trans = umeyama(source, target)
    moved = (scale * (rot @ source.T)).T + trans
    before = np.linalg.norm(source - target, axis=1)
    after = np.linalg.norm(moved - target, axis=1)
    m = np.eye(4)
    m[:3, :3] = scale * rot
    m[:3, 3] = trans
    return keys, m, before, after, target


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true', help='write src/generated/atlas_fit.js')
    args = ap.parse_args()

    doc = json.load(open(TABLE))
    keys, m, before, after, target = fit(doc['structures'])

    foot = target[:, 1] < -0.45
    print(f'{len(keys)} shared bones')
    print(f'  before   mean {before.mean() * 1000:5.1f} mm   '
          f'rms {np.sqrt((before ** 2).mean()) * 1000:5.1f}   max {before.max() * 1000:5.1f}')
    print(f'  after    mean {after.mean() * 1000:5.1f} mm   '
          f'rms {np.sqrt((after ** 2).mean()) * 1000:5.1f}   max {after.max() * 1000:5.1f}')
    print(f'  at the foot ({foot.sum()} bones)   '
          f'{before[foot].mean() * 1000:5.1f} mm -> {after[foot].mean() * 1000:5.1f} mm')

    if not args.write:
        print('\n(dry run -- pass --write to update src/generated/atlas_fit.js)')
        return

    rows = ',\n  '.join(', '.join(f'{v:+.8f}' for v in row) for row in m)
    OUT_TEXT = f'''/* Generated by scripts/fit_atlases.py -- do not edit.
 *
 * The transform that puts BodyParts3D 4.0 onto BodyParts3D 3.0. Solved by Umeyama over the
 * {len(keys)} bones named in both releases; see that script for why it is needed.
 *
 * Measured residual over those bones:
 *   before   mean {before.mean() * 1000:.1f} mm, max {before.max() * 1000:.1f} mm
 *   after    mean {after.mean() * 1000:.1f} mm, max {after.max() * 1000:.1f} mm
 *   at the foot, where it showed:  {before[foot].mean() * 1000:.1f} mm -> {after[foot].mean() * 1000:.1f} mm
 *
 * Row-major, ready for THREE.Matrix4.set.
 */
export const ATLAS_FIT = [
  {rows},
];

/** The layers `build_detail.py` emits, which are the ones carrying the 4.0 frame. */
export const FITTED_LAYERS = {json.dumps(list(FITTED))};
'''
    open(OUT, 'w').write(OUT_TEXT)
    print(f'\nwrote {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
