"""Stamps every model file with a content hash, so a rebuilt model is never served stale.

The models are fetched by a plain path — `models/organs_full.glb` — and a browser is
entitled to keep that file for as long as its cache headers allow. That is normally what
you want and it is exactly wrong the moment a build changes the file: the skin was removed
from the atlas, the structure table that came with it said so, and the browser went on
serving the *old* geometry beside the *new* table. Region ids had shifted by one, so the
skin was still drawn and clicking it reported "spleen" -- a fault with no symptom that
points at its cause, on a machine nobody debugging it can see.

A content hash in the query string ends that: the URL for a file that changed is a
different URL, so there is nothing to serve from cache, and the URL for a file that did
not change is identical, so nothing is re-downloaded for no reason.

Run after any build that writes into models/.  `npm run stamp`.
"""
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
MODELS = os.path.join(WEB, 'models')
OUT = os.path.join(WEB, 'src', 'generated', 'assets.js')


def digest(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()[:10]


def main():
    stamps = {}
    for name in sorted(os.listdir(MODELS)):
        if name.endswith('.glb'):
            stamps[name] = digest(os.path.join(MODELS, name))
    body = json.dumps(stamps, indent=1, sort_keys=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(
            '/* Generated by scripts/stamp_assets.py -- do not edit.\n'
            ' *\n'
            ' * A content hash per model file. `assetUrl` in bodies.js appends it to every\n'
            ' * model URL so that a rebuilt file can never be served from a browser cache\n'
            ' * beside a structure table that has moved on without it. See that script for\n'
            ' * what went wrong without it.\n'
            ' */\n'
            f'export const ASSET_STAMP = {body};\n')
    print(f'{len(stamps)} models stamped -> {os.path.relpath(OUT, WEB)}')


if __name__ == '__main__':
    main()
