/** Disposable local finding → plan → real atlas selection → Student → phase/complete acceptance.
 * Uses native visible structure-list clicks in the rendered atlas; no forged events/messages.
 * MOTION_BASE_URL=http://127.0.0.1:8151 CHROMIUM=/path/to/chrome node test/program-finding-atlas.browser.mjs
 */
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
const base=process.env.MOTION_BASE_URL||'http://127.0.0.1:8151';
assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname),'Run only on a disposable local workspace.');
const key=process.env.MOTION_DEMO_KEY||randomBytes(16).toString('hex');
const name='Finding and anatomy acceptance '+key.slice(0,6);
const rationale='This saved client finding led the coach to choose a supported movement and explain its body targets.';
const browser=await chromium.launch({...(process.env.CHROMIUM?{executablePath:process.env.CHROMIUM}:{}),
  args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-gpu-sandbox','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
page.setDefaultTimeout(60000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const report={base,fixture:'Fictional persisted demo assessment; real atlas structure labels and native WebGL renderer'};
const info=async(path)=>page.evaluate(async path=>{const r=await fetch('/platform/'+path,{credentials:'same-origin'});if(!r.ok)throw Error(path+' '+r.status);return r.json();},path);
const save=async(reason)=>{
  await page.locator('[name=change_reason]').fill(reason);
  const pending=page.waitForResponse(r=>r.url().endsWith('/platform/save')&&r.request().postDataJSON()?.collection==='programs');
  await page.getByRole('button',{name:'Save',exact:true}).click();const r=await pending;
  assert.equal(r.status(),200,await r.text());const value=await r.json();
  await page.locator('dialog').waitFor({state:'hidden'});return value;
};
const waitClient=async(id)=>page.locator('.client-context').filter({hasText:'Sarah Kim'}).waitFor({timeout:180000});
const alignAtlas=async()=>page.locator('.pd-atlas').evaluate(el=>{
  const dialog=el.closest('dialog');
  dialog.scrollTop+=el.getBoundingClientRect().top-(dialog.getBoundingClientRect().top+100);
});
const atlasSelection=async(structure,region)=>{
  await alignAtlas();
  const frame=page.frameLocator('.pd-atlas');
  await frame.locator('#rail [data-pop="explore"]').waitFor({timeout:180000});
  const open=await frame.locator('#rail [data-pop="explore"]').getAttribute('aria-pressed');
  if(open!=='true')await frame.locator('#rail [data-pop="explore"]').click();
  await frame.locator('#anatQ').fill(structure);
  // The atlas search debounces and redraws its result list as geometry finishes loading.
  await page.waitForTimeout(750);
  const label=frame.locator('#panelBody [data-id][title="'+structure+'"]').first();
  await label.waitFor({state:'visible',timeout:180000});const selectedId=Number(await label.getAttribute('data-id'));
  await frame.locator('#panel').evaluate(el=>el.scrollTo(0,el.scrollHeight));
  await alignAtlas();
  await label.click();
  await page.locator('#pd-atlas-status').getByText(new RegExp('added to')).waitFor({timeout:180000});
  await page.waitForFunction(({region})=>document.querySelector(`#pd-target-picker [data-target="${region}"]`)?.getAttribute('aria-pressed')==='true',{region},{timeout:180000});
  const selected=await frame.locator('#stage').evaluate(async()=>{const m=await import('/src/main.js');const s=await import('/src/structures.js');
    return {id:m.app.selected,name:m.app.selected==null?null:s.nameOf(m.app.selected,'en'),canvas:document.querySelector('canvas')?.getBoundingClientRect().toJSON()};});
  assert.equal(selected.id,selectedId,'Clicking a visible real structure label must select that atlas structure.');
  assert.ok(selected.canvas.width>0&&selected.canvas.height>0);return selected;
};
try{
  await page.goto(base+'/workspace.html');await page.evaluate(k=>sessionStorage.setItem('motion-demo-key',k),key);
  await page.getByRole('button',{name:'Explore as coach',exact:true}).click();
  await page.getByRole('heading',{name:'Your coaching day',exact:true}).waitFor({timeout:180000});
  const coach=await info('me');const client=coach.students.find(s=>s.name==='Sarah Kim');assert.ok(client);
  let data=await info('client?id='+client.id);const originalAssignment=data.programs.find(p=>p.active);assert.ok(originalAssignment);
  const historical=await info('record?collection=programs&id='+originalAssignment.program_id);
  const assessment=data.analyses.find(a=>a.kind==='movement')||data.analyses[0];assert.ok(assessment);
  const assessmentRoute=base+'/workspace.html#'+new URLSearchParams({page:'report',id:assessment.id,client:client.id});
  await page.goto(assessmentRoute);await page.getByRole('button',{name:'Body regions',exact:true}).click();
  const plan=page.locator('a[href*="region=right_shoulder"]').filter({hasText:'Plan exercise →'}).first();await plan.waitFor();
  const planHref=await plan.getAttribute('href');const context=new URLSearchParams(planHref.slice(1));
  assert.equal(context.get('report'),assessment.id);assert.equal(context.get('client'),client.id);
  assert.ok(context.get('region'));assert.ok(context.get('finding'));
  report.finding={assessment:assessment.id,protocol:assessment.protocol,region:context.get('region'),finding:context.get('finding'),href:planHref};
  await plan.click();await page.locator('.pd-context-callout').waitFor();
  await page.getByRole('button',{name:'+ Create program',exact:true}).click();
  await page.locator('[name=name]').fill(name);await page.locator('[name=goal]').fill('Connect this finding to an explained, coach-selected movement.');
  const exercises=(await info('list?collection=exercises&q=Arm&limit=50')).items;assert.ok(exercises.length);
  const exercise=exercises.find(e=>/arm raise|shoulder/i.test(e.name))||exercises.find(e=>e.region_id==='right_shoulder')||exercises[0];
  const searchResult=page.waitForResponse(r=>new URL(r.url()).pathname==='/platform/list'&&new URL(r.url()).searchParams.get('q')==='Arm');
  await page.locator('[name=exercise_search]').fill('Arm');await searchResult;
  await page.waitForFunction(()=>document.querySelector('[name=exercise_id] option')?.textContent.includes('matches'));
  await page.waitForFunction(id=>[...document.querySelector('[name=exercise_id]').options].some(o=>o.value===id),exercise.id);
  await page.locator('[name=exercise_id]').selectOption(exercise.id);await page.locator('#pd-add-exercise').click();
  let card=page.locator('.pd-edit-step:not(.pd-edit-note)').first();await card.waitFor();
  await card.getByText('Configure movement',{exact:true}).click();await card.locator('[name=why_assigned]').fill(rationale);
  await card.locator('[name=student_instructions]').fill('Use the recorded demonstration and stay within a comfortable supported range.');
  const initialStepTargets=await card.locator('.pd-target.selected').evaluateAll(bs=>bs.map(b=>b.dataset.target));
  await page.getByText('Select on 3D anatomy',{exact:true}).click();
  console.log('Atlas loading for plan targets; finding:',report.finding);
  const whole=await atlasSelection('Left patella','left_knee');report.planSelection=whole;
  assert.ok(!initialStepTargets.includes('left_knee'));
  assert.equal(await card.locator('[data-target=left_knee]').getAttribute('aria-pressed'),'false','Whole-plan selection must not silently change every movement.');
  console.log('Real whole-plan structure selected:',whole.name,whole.id);
  // Keep Explore open; its header close button overlaps the rail in this compact iframe.
  await card.getByText('Body areas and evidence',{exact:true}).click();
  await card.getByRole('button',{name:'Select this movement’s body targets on 3D anatomy',exact:true}).click();
  const individual=await atlasSelection('Left radius','left_elbow');report.stepSelection=individual;
  assert.equal(await card.locator('[data-target=left_elbow]').getAttribute('aria-pressed'),'true');
  assert.equal(await card.locator('[data-target=left_knee]').getAttribute('aria-pressed'),'false');
  console.log('Real movement structure selected:',individual.name,individual.id);
  if(process.env.MOTION_ATLAS_SCREENSHOT)await page.screenshot({path:process.env.MOTION_ATLAS_SCREENSHOT});
  let saved=await save('Created from an actual saved finding and real atlas structure selections');
  const programId=saved.id;assert.notEqual(programId,historical.id);assert.equal(saved.detail.source_analysis_id,assessment.id);
  assert.equal(saved.detail.source_finding,context.get('finding'));assert.ok(saved.detail.target_region_ids.includes(context.get('region')));
  assert.ok(saved.detail.target_region_ids.includes('left_knee'));assert.ok(saved.detail.target_region_ids.includes('left_elbow'));
  assert.ok(saved.steps[0].detail.target_region_ids.includes('left_elbow'));assert.ok(!saved.steps[0].detail.target_region_ids.includes('left_knee'));
  assert.equal(saved.steps[0].detail.source.id,assessment.id);assert.equal(saved.steps[0].detail.why_assigned,rationale);
  report.saved={program:programId,version:saved.version,source:saved.detail.source_analysis_id,finding:saved.detail.source_finding,planTargets:saved.detail.target_region_ids,stepTargets:saved.steps[0].detail.target_region_ids};
  console.log('Saved source and distinct program/movement targets:',report.saved);
  const returnLink=page.locator('.pd-program-context a[href*="page=report"],.pd-program-summary a[href*="page=report"],.pd-context-callout a[href*="page=report"]').first();
  const allReportLinks=page.locator('#page-content a[href*="page=report"]');await allReportLinks.first().waitFor();
  const exactReturn=allReportLinks.filter({hasText:/assessment|source/i}).first();
  const returnHref=await exactReturn.getAttribute('href');assert.equal(new URLSearchParams(returnHref.slice(1)).get('id'),assessment.id);
  await exactReturn.click();await page.getByRole('button',{name:'Body regions',exact:true}).waitFor();
  assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('id'),assessment.id);report.returnToFinding=returnHref;
  const workspace=base+'/workspace.html#'+new URLSearchParams({page:'client',client:client.id,tab:'programs'});
  await page.goto(workspace);await page.locator('.pd-current-main h2').getByText(name,{exact:true}).waitFor();
  await page.getByText('More program actions',{exact:true}).click();await page.locator('#pd-new-phase').click();
  await page.waitForFunction(()=>document.querySelector('[name=current_program_phase]')?.value==='Phase 2');
  assert.equal(await page.locator('[name=current_program_phase]').inputValue(),'Phase 2');
  const rows=page.locator('.pd-phase-row');assert.equal(await rows.count(),2);
  assert.equal(await rows.last().locator('[name=phase_start]').inputValue(),'5');assert.equal(await rows.last().locator('[name=phase_end]').inputValue(),'8');
  saved=await save('Progressed this new assignment to its second phase');assert.equal(saved.id,programId);assert.equal(saved.version,2);
  assert.equal(saved.detail.phase,'Phase 2');assert.equal(saved.detail.source_analysis_id,assessment.id);
  await page.goto(workspace);await page.locator('.pd-current-facts').getByText('Phase 2',{exact:true}).waitFor();
  report.nextPhase={phase:saved.detail.phase,version:saved.version,start:saved.detail.phases[1].weeks_start,end:saved.detail.phases[1].weeks_end};
  console.log('Created next phase:',report.nextPhase);
  const studentLogin=page.waitForResponse(r=>r.url().endsWith('/platform/auth/demo')&&r.request().postDataJSON()?.role==='student');
  await page.locator('#demo-role').selectOption('student');assert.equal((await (await studentLogin).json()).role,'student');
  await page.getByRole('heading',{name:'Your practice, today',exact:true}).waitFor();
  const studentRoute=base+'/workspace.html#'+new URLSearchParams({page:'program',id:programId,client:client.id});await page.goto(studentRoute);await page.reload();
  const studentCard=page.locator('.pd-practice-card').first();await studentCard.locator('.pd-why').getByText(rationale,{exact:false}).waitFor();
  const bodyLink=studentCard.locator('a').filter({hasText:'Left Elbow region · View body'}).first();await bodyLink.waitFor();
  const bodyHref=await bodyLink.getAttribute('href');const bodyParams=new URLSearchParams(bodyHref.slice(1));assert.equal(bodyParams.get('region'),'left_elbow');assert.equal(bodyParams.get('client'),client.id);
  await bodyLink.click();await page.locator('#anatomy-status').getByText('Connected to').waitFor({timeout:180000});
  await page.locator('[name=anatomy-layer]').waitFor();await page.frameLocator('#atlas').locator('#labels button').first().waitFor({timeout:180000});
  assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('region'),'left_elbow');report.student={rationale,bodyLink:bodyHref,connected:'Student own Left Elbow anatomy reference loaded'};
  if(process.env.MOTION_STUDENT_SCREENSHOT)await page.screenshot({path:process.env.MOTION_STUDENT_SCREENSHOT});
  const coachLogin=page.waitForResponse(r=>r.url().endsWith('/platform/auth/demo')&&r.request().postDataJSON()?.role==='coach');await page.locator('#demo-role').selectOption('coach');assert.equal((await (await coachLogin).json()).role,'coach');
  await page.getByRole('heading',{name:'Your coaching day',exact:true}).waitFor();await page.goto(workspace);
  await page.getByText('More program actions',{exact:true}).click();await page.locator('#pd-complete-program').click();
  await page.locator('dialog [name=reason]').fill('Finite acceptance completed after next-phase and Student body review.');
  const retirement=page.waitForResponse(r=>r.url().endsWith('/platform/program/retire'));
  await page.locator('dialog').getByRole('button',{name:'Complete program',exact:true}).click();assert.equal((await retirement).status(),200);
  await page.locator('dialog').waitFor({state:'hidden'});await page.getByRole('heading',{name:'Build a plan for this client',exact:true}).waitFor();
  data=await info('client?id='+client.id);const completed=data.program_history.find(p=>p.program_id===programId);assert.ok(completed&&!completed.active);
  assert.ok(completed.notes.includes('Completed:'));assert.ok(!data.programs.some(p=>p.active));
  const retained=await info('record?collection=programs&id='+programId);assert.equal(retained.version,2);assert.equal(retained.steps.length,saved.steps.length);
  const historicalAfter=await info('record?collection=programs&id='+historical.id);assert.equal(historicalAfter.version,historical.version);assert.deepEqual(historicalAfter.steps,historical.steps);
  report.completed={program:programId,assignmentActive:completed.active,notes:completed.notes,retainedVersion:retained.version,historicalOriginalVersion:historicalAfter.version};
  assert.deepEqual(errors,[]);report.pageErrors=errors;report.result='PASS';console.log(JSON.stringify(report,null,2));
  if(process.env.MOTION_REPORT)await writeFile(process.env.MOTION_REPORT,JSON.stringify(report,null,2)+'\n');
}catch(error){console.error('FAIL:',error.stack);process.exitCode=1;if(process.env.MOTION_FAILURE_SCREENSHOT)await page.screenshot({path:process.env.MOTION_FAILURE_SCREENSHOT}).catch(()=>{});}
finally{await browser.close();}
