/** Region metadata (EN + KO). Ids 1-15 are cortical parcels baked into the mesh from the
  * Desikan-Killiany atlas. Ids 20+ are structures segmented out of aseg.mgz.
  *
  * Each region carries two registers of the same fact:
  *   does  — plain language, written to be read aloud to a parent
  *   sci   — the same structure in clinical terms, for a teacher who wants the real name
  * Both exist in en and ko. Nothing here is specific to any child.
  */
export const REGION_INFO = {
  1: { key:'frontal', color:'#4C8DF6', deep:false,
    en:{ name:'Frontal lobe', where:'Behind the forehead, the largest lobe.',
      does:'Planning, decisions, holding an idea in mind, and starting voluntary movement.',
      sci:'Prefrontal and premotor cortex. Executive control, working-memory maintenance and response selection; the frontal pole matures last of any cortex.',
      fact:'Keeps developing into the mid-twenties, later than any other lobe.' },
    ko:{ name:'전두엽', where:'이마 뒤쪽에 있는 가장 큰 엽입니다.',
      does:'계획을 세우고, 판단하고, 생각을 잠시 붙잡아 두고, 스스로 움직임을 시작하게 합니다.',
      sci:'전전두피질과 전운동피질. 실행 기능, 작업기억 유지, 반응 선택을 담당하며 전두극은 대뇌피질 중 가장 늦게 성숙합니다.',
      fact:'20대 중반까지 계속 발달하며, 이는 어떤 엽보다도 늦습니다.' } },
  2: { key:'parietal', color:'#28B487', deep:false,
    en:{ name:'Superior parietal', where:'Top and rear of the brain, above the angular and supramarginal gyri.',
      does:'Spatial awareness, guiding movement by sight, and directing attention.',
      sci:'Superior parietal lobule (BA 5/7). Visuospatial transformation between reference frames and top-down attentional orienting.',
      fact:'Right-sided damage can make a person ignore the whole left side of space.' },
    ko:{ name:'상두정소엽', where:'뇌 위쪽 뒤편, 모이랑과 모서리위이랑보다 위에 있습니다.',
      does:'공간을 파악하고, 눈으로 보면서 움직임을 조절하고, 주의를 어디에 둘지 정합니다.',
      sci:'상두정소엽(BA 5/7). 좌표계 간 시공간 변환과 하향식 주의 조절을 담당합니다.',
      fact:'오른쪽이 손상되면 왼쪽 공간 전체를 인식하지 못하는 편측무시가 나타날 수 있습니다.' } },
  3: { key:'temporal', color:'#E9A13B', deep:false,
    en:{ name:'Temporal lobe', where:'Beneath the lateral fissure, roughly behind the ear.',
      does:'Hearing, recognising objects and faces, and memory, with the hippocampus inside it.',
      sci:'Temporal lobe: auditory association cortex, the ventral visual stream for object identity, and the medial temporal memory system.',
      fact:'It holds a patch that responds to faces far more than to anything else.' },
    ko:{ name:'측두엽', where:'외측고랑 아래, 대략 귀 뒤쪽에 있습니다.',
      does:'듣기, 사물과 얼굴 알아보기, 기억을 담당하며 안쪽에 해마가 들어 있습니다.',
      sci:'측두엽: 청각연합피질, 사물 인식을 담당하는 배쪽 시각 경로, 내측측두 기억 체계를 포함합니다.',
      fact:'얼굴에만 유독 강하게 반응하는 영역(방추상 얼굴 영역)이 이 안에 있습니다.' } },
  4: { key:'occipital', color:'#A05BE8', deep:false,
    en:{ name:'Occipital lobe', where:'The very back of the brain.',
      does:'Vision. Signals from the eyes arrive here first.',
      sci:'Occipital lobe. Primary visual cortex (V1, BA 17) and extrastriate areas, organised retinotopically.',
      fact:'Mapped like a picture: neighbouring points in the world land on neighbouring neurons.' },
    ko:{ name:'후두엽', where:'뇌의 가장 뒤쪽입니다.',
      does:'시각을 담당합니다. 눈에서 온 신호가 가장 먼저 도착하는 곳입니다.',
      sci:'후두엽. 일차시각피질(V1, BA 17)과 선조외피질로 이루어지며 망막위상적으로 배열되어 있습니다.',
      fact:'그림처럼 배열되어 있어, 실제로 붙어 있는 두 지점은 뇌에서도 붙어 있는 뉴런에 도착합니다.' } },
  5: { key:'cerebellum', color:'#E255B4', deep:false,
    en:{ name:'Cerebellum', where:'Tucked under the back of the brain.',
      does:'Timing, balance and making movement smooth. Also supports fluent speech.',
      sci:'Cerebellum. Predictive timing and error-based motor correction through cerebro-cerebellar loops, including sequencing of speech articulation.',
      fact:'About a tenth of the brain by volume but over half its neurons.' },
    ko:{ name:'소뇌', where:'뇌 뒤쪽 아래에 자리잡고 있습니다.',
      does:'박자와 균형을 잡고 움직임을 매끄럽게 만듭니다. 말이 유창하게 나오도록 돕기도 합니다.',
      sci:'소뇌. 대뇌-소뇌 회로를 통한 예측적 타이밍 조절과 오차 기반 운동 교정을 담당하며 조음 순서 배열에도 관여합니다.',
      fact:'부피는 뇌의 약 10분의 1이지만 뉴런 수는 절반이 넘습니다.' } },
  6: { key:'brainstem', color:'#E2685F', deep:false,
    en:{ name:'Brainstem', where:'The stalk joining brain to spinal cord.',
      does:'Breathing, heart rate, swallowing, sleep and alertness.',
      sci:'Midbrain, pons and medulla. Cranial nerve nuclei and autonomic centres, plus the ascending reticular activating system that sets arousal.',
      fact:'The one part of the brain you cannot live without.' },
    ko:{ name:'뇌간', where:'뇌와 척수를 잇는 줄기 부분입니다.',
      does:'호흡, 심장 박동, 삼킴, 잠과 깨어 있음을 조절합니다.',
      sci:'중뇌·교뇌·연수. 뇌신경핵과 자율신경 중추, 각성 수준을 정하는 상행망상활성계가 있습니다.',
      fact:'없으면 생명 유지가 불가능한 유일한 부위입니다.' } },
  7: { key:'motor', color:'#1B4FC4', deep:false,
    en:{ name:'Motor cortex', where:'The precentral gyrus, a strip over the top of the brain.',
      does:'Sends the commands that move muscles, including lips, tongue and jaw for speech.',
      sci:'Precentral gyrus (BA 4). Somatotopically organised primary motor cortex; origin of the corticospinal and corticobulbar tracts that drive articulation.',
      fact:'The body map is out of scale: lips and hands take far more space than the back.' },
    ko:{ name:'운동피질', where:'중심앞이랑, 뇌 위쪽을 가로지르는 띠 모양입니다.',
      does:'근육을 움직이라는 명령을 보냅니다. 말할 때 쓰는 입술, 혀, 턱도 여기서 조절합니다.',
      sci:'중심앞이랑(BA 4). 신체부위별로 배열된 일차운동피질이며, 조음을 담당하는 피질척수로와 피질연수로가 시작됩니다.',
      fact:'신체 지도가 실제 비율과 달라서, 입술과 손이 등보다 훨씬 넓은 자리를 차지합니다.' } },
  8: { key:'somato', color:'#0E7C5A', deep:false,
    en:{ name:'Somatosensory cortex', where:'The postcentral gyrus, mirroring the motor strip.',
      does:'Receives touch, pressure, temperature and body position — including where the tongue is.',
      sci:'Postcentral gyrus (BA 1, 2, 3). Primary somatosensory cortex receiving thalamocortical input from the VPL and VPM nuclei.',
      fact:'Fingertips take an enormous share of it.' },
    ko:{ name:'체성감각피질', where:'중심뒤이랑, 운동 띠와 나란히 마주보고 있습니다.',
      does:'촉각, 압력, 온도, 몸의 위치를 받아들입니다. 혀가 지금 어디 있는지도 여기서 압니다.',
      sci:'중심뒤이랑(BA 1, 2, 3). 시상의 VPL·VPM 핵에서 오는 입력을 받는 일차체성감각피질입니다.',
      fact:'손끝이 차지하는 면적이 대단히 넓습니다.' } },
  9: { key:'broca', color:'#F2C230', deep:false,
    en:{ name:'Broca’s area', where:'Pars opercularis and pars triangularis of the left inferior frontal gyrus.',
      does:'Building speech: choosing words, putting them in order, and driving the movements that produce them.',
      sci:'Left inferior frontal gyrus, pars opercularis and pars triangularis (BA 44/45). Phonological encoding and syntactic assembly for speech output.',
      fact:'Damage here can leave someone understanding everything but speaking in short, effortful bursts.' },
    ko:{ name:'브로카 영역', where:'좌측 하전두이랑의 덮개부와 삼각부입니다.',
      does:'말을 조립합니다. 단어를 고르고, 순서를 정하고, 그것을 실제 발화 운동으로 이어줍니다.',
      sci:'좌측 하전두이랑 덮개부·삼각부(BA 44/45). 발화 산출을 위한 음운 부호화와 통사 조립을 담당합니다.',
      fact:'이곳이 손상되면 다 알아듣지만 짧고 힘겹게만 말하게 되는 경우가 있습니다.' } },
  10: { key:'wernicke', color:'#F07E26', deep:false,
    en:{ name:'Wernicke’s area', where:'Posterior superior temporal gyrus and the banks of the superior temporal sulcus, left side.',
      does:'Turning heard speech into meaning.',
      sci:'Left posterior superior temporal gyrus and banks of the superior temporal sulcus (BA 22). Lexical-semantic access from an acoustic signal.',
      fact:'Joined to Broca’s area by a thick fibre bundle, the arcuate fasciculus.' },
    ko:{ name:'베르니케 영역', where:'좌측 후상측두이랑과 상측두고랑 양안입니다.',
      does:'귀로 들어온 말을 의미로 바꿉니다.',
      sci:'좌측 후상측두이랑과 상측두고랑 양안(BA 22). 음향 신호로부터 어휘-의미 접근을 수행합니다.',
      fact:'궁상속이라는 굵은 신경섬유 다발로 브로카 영역과 연결되어 있습니다.' } },
  11: { key:'cingulate', color:'#7FB2A8', deep:false,
    en:{ name:'Cingulate cortex', where:'On the medial surface, curving above the corpus callosum.',
      does:'Effort, noticing mistakes, motivation and staying calm enough to keep going.',
      sci:'Cingulate cortex (BA 24/32). Conflict monitoring, error-related negativity, and allocation of cognitive effort.',
      fact:'It fires when you notice you have made a mistake, before you can say what it was.' },
    ko:{ name:'대상피질', where:'뇌 안쪽 면에서 뇌량 위를 활처럼 감싸고 있습니다.',
      does:'애쓰는 힘, 실수 알아차리기, 동기, 그리고 끝까지 해내는 정서 조절을 맡습니다.',
      sci:'대상피질(BA 24/32). 갈등 감시, 오류관련음전위, 인지적 노력 배분에 관여합니다.',
      fact:'무엇을 틀렸는지 말로 설명하기도 전에 "틀렸다"는 신호를 먼저 냅니다.' } },
  12: { key:'insula', color:'#C9A227', deep:false,
    en:{ name:'Insula', where:'Folded deep inside the lateral fissure.',
      does:'Awareness of the body from the inside, taste, and — at its front edge — coordinating the act of speaking.',
      sci:'Insular cortex. Interoceptive representation and gustatory processing; the anterior insula coordinates speech articulation.',
      fact:'It is the only lobe you cannot see from outside the brain.' },
    ko:{ name:'섬엽', where:'외측고랑 깊숙이 접혀 들어가 있습니다.',
      does:'몸 안쪽의 느낌과 맛을 담당하고, 앞부분은 말하는 동작을 조율합니다.',
      sci:'섬피질. 내수용 감각과 미각을 처리하며, 전측 섬엽은 조음 협응에 관여합니다.',
      fact:'바깥에서는 보이지 않는 유일한 엽입니다.' } },
  13: { key:'auditory', color:'#35C4A0', deep:false,
    en:{ name:'Auditory cortex', where:'Heschl’s gyrus, on the upper surface of the temporal lobe.',
      does:'The first stop in the cortex for sound. Separates one speech sound from another.',
      sci:'Heschl’s gyrus (BA 41/42). Tonotopically organised primary auditory cortex encoding the spectrotemporal detail that distinguishes phonemes.',
      fact:'Korean has no /r/ versus /l/ contrast, so that distinction has to be built here rather than inherited.' },
    ko:{ name:'청각피질', where:'측두엽 윗면의 헤슬이랑입니다.',
      does:'소리가 대뇌에서 가장 먼저 닿는 곳입니다. 비슷한 말소리를 서로 구별해 냅니다.',
      sci:'헤슬이랑(BA 41/42). 주파수순으로 배열된 일차청각피질로, 음소를 가르는 스펙트럼·시간 정보를 부호화합니다.',
      fact:'한국어에는 /r/과 /l/의 대립이 없어서, 이 구별은 물려받는 것이 아니라 여기서 새로 만들어야 합니다.' } },
  14: { key:'supramarg', color:'#5EC8F2', deep:false,
    en:{ name:'Supramarginal gyrus', where:'Just above the end of the lateral fissure, in the parietal lobe.',
      does:'Holds a string of unfamiliar sounds in mind long enough for the rest of the brain to learn it.',
      sci:'Supramarginal gyrus (BA 40). The phonological store of the working-memory loop, rehearsed by inferior frontal circuitry.',
      fact:'This is the phonological loop, the single strongest known predictor of second-language vocabulary growth.' },
    ko:{ name:'모서리위이랑', where:'두정엽에서 외측고랑이 끝나는 지점 바로 위입니다.',
      does:'낯선 소리의 배열을 잠시 붙잡아 두어, 뇌의 나머지 부분이 그것을 배울 시간을 벌어 줍니다.',
      sci:'모서리위이랑(BA 40). 작업기억 고리의 음운 저장소이며 하전두 회로가 되뇌기를 담당합니다.',
      fact:'이것이 음운 루프이며, 제2언어 어휘 성장을 예측하는 가장 강력한 단일 지표입니다.' } },
  15: { key:'angular', color:'#9B7BE8', deep:false,
    en:{ name:'Angular gyrus', where:'Behind the supramarginal gyrus, at the temporal-parietal junction.',
      does:'Links a word to everything you already know about the thing itself.',
      sci:'Angular gyrus (BA 39). Heteromodal convergence zone binding word form to distributed semantic knowledge.',
      fact:'This is why a word learned inside a real activity sticks better than one learned from a list.' },
    ko:{ name:'모이랑', where:'모서리위이랑 뒤쪽, 측두-두정 접합부에 있습니다.',
      does:'하나의 단어를 그 사물에 대해 이미 알고 있는 모든 것과 연결합니다.',
      sci:'모이랑(BA 39). 단어 형태와 분산된 의미 지식을 결합하는 다중감각 수렴 영역입니다.',
      fact:'단어를 목록으로 외울 때보다 실제 활동 속에서 배울 때 더 오래 남는 이유가 여기 있습니다.' } },
  20: { key:'hippocampus', color:'#39C2C9', deep:true,
    en:{ name:'Hippocampus', where:'Curved, buried inside each temporal lobe.',
      does:'Forms new memories and hands them over to the cortex to keep. Most of that handover happens during sleep.',
      sci:'Hippocampal formation. Encoding of episodic memory and systems consolidation to neocortex, largely during slow-wave sleep.',
      fact:'Named after the seahorse, which its curve resembles.' },
    ko:{ name:'해마', where:'양쪽 측두엽 안쪽에 굽은 모양으로 묻혀 있습니다.',
      does:'새 기억을 만들어 대뇌피질에 넘겨 보관하게 합니다. 그 인계는 대부분 잠자는 동안 일어납니다.',
      sci:'해마체. 일화기억의 부호화와 신피질로의 체계 공고화를 담당하며, 주로 서파수면 중에 이루어집니다.',
      fact:'굽은 모양이 해마(바다 생물)를 닮아 붙은 이름입니다.' } },
  21: { key:'amygdala', color:'#F2555A', deep:true,
    en:{ name:'Amygdala', where:'Almond-shaped, just in front of each hippocampus.',
      does:'Marks what matters. A lesson attached to feeling is remembered better than a neutral one.',
      sci:'Amygdaloid complex. Salience detection and modulation of hippocampal encoding through basolateral projections.',
      fact:'It can trigger fear faster than the part of you that consciously recognises danger.' },
    ko:{ name:'편도체', where:'각 해마 바로 앞에 아몬드 모양으로 있습니다.',
      does:'무엇이 중요한지 표시합니다. 감정이 실린 수업이 밋밋한 수업보다 더 잘 남는 이유입니다.',
      sci:'편도복합체. 현저성 탐지를 담당하며 기저외측 투사를 통해 해마의 부호화를 조절합니다.',
      fact:'의식적으로 위험을 알아차리는 부분보다 더 빨리 공포 반응을 일으킬 수 있습니다.' } },
  22: { key:'thalamus', color:'#7C9CF5', deep:true,
    en:{ name:'Thalamus', where:'A pair of egg-shaped structures at the centre of the brain.',
      does:'Relays almost everything the senses pick up on its way to the cortex, and decides what gets through.',
      sci:'Thalamus. Obligatory relay for ascending sensory pathways; the medial geniculate nucleus carries audition and the pulvinar gates attention.',
      fact:'Smell is the one sense that skips it.' },
    ko:{ name:'시상', where:'뇌 한가운데에 달걀 모양으로 한 쌍 있습니다.',
      does:'감각이 받아들인 거의 모든 정보를 대뇌피질로 중계하며, 무엇을 통과시킬지 조절합니다.',
      sci:'시상. 상행 감각 경로의 필수 중계핵이며, 내측슬상체가 청각을, 시상베개가 주의 조절을 담당합니다.',
      fact:'후각만이 시상을 거치지 않고 지나갑니다.' } },
  23: { key:'corpus', color:'#E9E4D8', deep:true,
    en:{ name:'Corpus callosum', where:'A thick curved sheet of fibres joining the hemispheres.',
      does:'Carries traffic between left and right so the two halves work as one brain.',
      sci:'Corpus callosum. Roughly 200 million commissural axons providing interhemispheric transfer; it continues myelinating through childhood.',
      fact:'About 200 million fibres cross it.' },
    ko:{ name:'뇌량', where:'좌우 반구를 잇는 두껍고 굽은 섬유판입니다.',
      does:'왼쪽과 오른쪽 사이의 정보를 실어 날라 두 반구가 하나의 뇌로 작동하게 합니다.',
      sci:'뇌량. 약 2억 개의 교련섬유로 반구 간 전달을 담당하며, 아동기 내내 수초화가 계속됩니다.',
      fact:'약 2억 개의 섬유가 이곳을 가로지릅니다.' } },
  25: { key:'basalganglia', color:'#C0A15E', deep:true,
    en:{ name:'Basal ganglia', where:'Caudate, putamen and pallidum, deep on either side of the thalamus.',
      does:'Turns something practised into something automatic. This is what repetition is actually building.',
      sci:'Caudate, putamen and globus pallidus. Cortico-striato-thalamo-cortical loops for action selection and procedural learning.',
      fact:'This is the circuitry that turns a practised sequence into something you no longer have to think about.' },
    ko:{ name:'기저핵', where:'시상 양옆 깊은 곳의 미상핵, 조가비핵, 창백핵입니다.',
      does:'연습한 것을 자동으로 나오게 바꿉니다. 반복 연습이 실제로 만들고 있는 것이 이것입니다.',
      sci:'미상핵·조가비핵·창백핵. 피질-선조체-시상-피질 회로를 통해 행동 선택과 절차 학습을 담당합니다.',
      fact:'연습한 동작을 더 이상 의식하지 않고도 할 수 있게 만드는 회로입니다.' } },
  24: { key:'ventricles', color:'#4FD1E8', deep:true,
    en:{ name:'Lateral ventricles', where:'C-shaped fluid spaces inside each hemisphere.',
      does:'Hold the fluid that cushions the brain and washes waste out of it, mostly during sleep.',
      sci:'Lateral ventricles. CSF-filled cavities produced by the choroid plexus; glymphatic clearance rises during sleep.',
      fact:'The fluid makes a 1.4 kg brain effectively weigh about 50 g.' },
    ko:{ name:'측뇌실', where:'각 반구 안쪽의 C자 모양 액체 공간입니다.',
      does:'뇌를 감싸 보호하고 노폐물을 씻어내는 액체가 들어 있습니다. 이 청소는 주로 잘 때 일어납니다.',
      sci:'측뇌실. 맥락얼기가 만든 뇌척수액이 채워진 공간이며, 수면 중 글림프 배출이 증가합니다.',
      fact:'이 액체 덕분에 1.4 kg의 뇌가 실질적으로 약 50 g처럼 떠 있게 됩니다.' } },
};

export const GROUPS = [
  { id:'lang',   en:'Language & speech',   ko:'언어와 말하기', ids:[9,10,13,14,15] },
  { id:'lobes',  en:'Lobes & major parts', ko:'엽과 주요 부위', ids:[1,2,3,4,5,6] },
  { id:'other',  en:'Other cortical areas',ko:'기타 피질 영역', ids:[7,8,11,12] },
  { id:'deep',   en:'Inside the brain',    ko:'뇌 안쪽 구조',   ids:[20,21,22,23,24,25] },
];

/** Each assessment system maps onto the anatomical parcel it is associated with. */

/**
 * The English-test half of neurolab is gone (docs/DECISIONS.md §3): SKILL_REGION,
 * SKILL_ORDER, SKILL_LABEL, SKILL_WHY, BANDS, sampleResult.js, src/assessment/ and the
 * score panel came out with it. What survives is REGION_INFO — the bilingual dual-register
 * content model whose shape MUSCLE_INFO copies — and GROUPS, which the browse list uses.
 *
 * The old PATHWAYS table (arcs for the journey of a word) is replaced by MOVEMENT_PATHWAY
 * in src/content/pathways.js, which does the same job for the journey of a movement.
 * Interface strings now live in src/content/strings.js.
 */
